### PR TITLE
Update server-configs.md - added Nginx

### PR DESCRIPTION
**Pull request by sergeycooper**

### CODE REVIEW

**Comment by mxstbr** [comment]
See https://github.com/mxstbr/react-boilerplate/pull/234#issuecomment-197621060, will merge as soon as the config is on the `v3.0.0` branch! Thanks so much!

**Comment by sergeycooper** [comment]
Welcome! It's funny.. Actually I found this repo just 30 min ago - I'm choosing a boilerplate for my React-based fron-end. So I opend issues and see PR welcome for Nginx confs which I'm very familiar with :) So thank you for this boilerplate too - I will definetly check this out! ;)

**Comment by mxstbr** [comment]
Awesome, glad to hear! Definitely check out the `v3.0.0` branch, it's so much better.

**Comment by sergeycooper** [comment]
I will! :)

**Comment by learntoswim** [comment]
Hey guys, I don't see `.nginx.conf` being added to the `/build` folder after running `npm run build`. I see `.htaccess`, though.

**Pull request merged**
