### PR TITLE
Adding global css documentation, take 2

### PR DESCRIPTION
**Pull request by bobkocisko**
Adding global css documentation per https://github.com/mxstbr/react-boilerplate/issues/741

Update: Trying this again.  I deleted some extraneous commits that somehow made their way into my fork and now the merge seems to be happy.  Please let me know if I need to do anything else.

### CODE REVIEW

**Comment by gihrig** [comment]
@bobkocisko It's looking _great_ 😃 

I hope to get time to try it out in a few hrs...

**Comment by bobkocisko** [comment]
Thanks Glen!  You know what, I just realized that I probably missed something in the setup part of the docs.  If you don't mind waiting till Monday I can verify at work and update this one last time.

**Comment by gihrig** [comment]
@bobkocisko No worries, do what's needed.

**Comment by bobkocisko** [comment]
Ok Glen it should be ready to go, although I must admit that I'm not entirely sure about the `:global` css usage part.  If anyone has experience using that in `react-boilerplate` it would be great to get them to weigh in on it.

**Comment by mxstbr** [comment]
This looks ace, I think this is good to go! @gihrig your thoughts?

**Comment by gihrig** [comment]
I haven't actually tried it out, but reading the doc it looks top-notch, so yeah 💯

**Comment by mxstbr** [comment]
Awesome, good job @bobkocisko! 🔥

**Comment by bobkocisko** [comment]
Thanks guys!  Glad to be able to help.  BTW, great job to you on `react-boilerplate`!  Being brand new to React, it was a huge help not only to sift through the React ecosystem but also to have the extra automation and production-quality tools available for free.  Keep up the top-notch work!

**Comment by kachkaev** [comment]
Thanks for this clarification @bobkocisko - a huge time saver!

Do you know by a chance how to reference bootstrap's CSS when DLL plugin is off? My app does now work in production mode when react-bootstrap is included, unfortunately Can't figure out where to exclude `bootstrap-css-only` if not in DLL config.

The reason why I had to switch DLL plugin off is because it's currently incompatible with WebWorkers in dev mode :–) https://github.com/mxstbr/react-boilerplate/issues/784

**Comment by bobkocisko** [comment]
Wow that's a weird error that I thankfully haven't run into.  I hope you can find a solution to get the dllPlugin going again.

The good news is that react-bootstrap should work fine without the dllPlugin.  The parts of the documentation referring to dllPlugin are only to **exclude** `bootstrap-css-only` from being built into dllPlugin.  If you don't have dllPlugin turned on then there should not be any problem.

If you're having a problem getting it going though I don't think I can offer any specific help since I've not run into having to remove dllPlugin.

Good luck!

**Comment by kachkaev** [comment]
Looks like I was able to figure out what was wrong. This actually had nothing to do with `bootstrap-css-only`.

The issue was with what webpack's `DedupePlugin` was doing with react-bootstrap in production. After removing the plugin from `webpack.prod.babel.js`, I got my app with mapbox's WebWorkers working again!

The cost of removing `DedupePlugin` for me was just extra 4KB in the build folder :–) 

This issue is probably relevant:
https://github.com/webpack/webpack/issues/959

**Comment by bobkocisko** [comment]
Great!

**Pull request merged**
