### PR TITLE
Global CSS vars color palette

### PR DESCRIPTION
**Pull request by sedubois**
I didn't change colors (only one slightly to simplify things), just put them into global variables to be able to easily edit colors globally. Works with HMR too.

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
@sedubois might I suggest naming the variables to something more descriptive than `color{n}`

**Comment by sedubois** [comment]
@GGAlanSmithee What would you suggest? I don't know what the best practices are, but the point of these vars is to be able to change colors easily. So it hardly helps to name them `--color-blue`, etc. 

NB: I intentionally ranked them from darker to lighter, though.

**Comment by GGAlanSmithee** [comment]
@sedubois I have no idea about CSS variable best practices either, and I agree that naming them after their respective color is somewhat pointless. My suggestion would be to name them after their intended use. Maybe something like `primary`, `secondary`, `accent`, or if you'd like to be more specific, `prmiary-indigo`, `accent-pink` etc. What do you think?

_inspired by https://material.google.com/style/color.html#color-color-schemes_

**Comment by sedubois** [comment]
Thanks for the link. This is beyond my expertise, but how about this?

**Comment by mydearxym** [comment]
is there a possibility to switch these color with javascript ?  that would make theme staff much easier ?

**Comment by sedubois** [comment]
@mydearxym could you precise your question?

**Comment by GGAlanSmithee** [comment]
Just like @sedubois my familiarity to CSS vars is limited, but what you want seems to be possible @mydearxym https://eager.io/blog/communicating-between-javascript-and-css-with-css-variables/

**Comment by mydearxym** [comment]
what i mean is if we manipulate those color with javascript ?

for example before: 

```js
:root {
  --color-primary: black;
  --color-primary-light: #CCC;
  --color-secondary: #FAFAFA;
  --color-secondary-light: #FFF;
  --color-accent: #41ADDD;
  --color-accent-light: #6CC0E5;
}
```

after some js magic : 

```js
:root {
  --color-primary: blue;
  --color-primary-light: #CCC;
  --color-secondary: #FAFAFA;
  --color-secondary-light: #FFF;
  --color-accent: #41ADDD;
  --color-accent-light: #6CC0E5;
}
```

it will be very useful to add some theme staff

**Comment by sedubois** [comment]
@mydearxym that should be possible somehow, e.g looking at https://github.com/este/este/blob/master/src/common/app/components/ThemeProvider.js. But that's out of scope of this PR so if needed, suggest to open separate issue.

**Comment by mydearxym** [comment]
@GGAlanSmithee  that solution is great, thanks!  but IE seems [not support it](http://caniuse.com/#feat=css-variables)

@sedubois  thanks, i will open a separate issue to discuss it.

**Comment by mxstbr** [comment]
Since we're going to switch to styled-components, this is no longer necessary – thanks for taking the time to do this though, it would've been much better!

**Comment by kopax** [comment]
@GGAlanSmithee thanks for the link. So I have read and yes, I suppose the way of the react boilerplate creator they suggest to go is to create independant templated component.

Does that mean we give up with the global styling ?

**Comment by mxstbr** [comment]
> Does that mean we give up with the global styling ? no more global variable etc... ? 

No, `styled-components` can still inject global styling with the `injectGlobal` helper. Also, global variables are now just JavaScript variables instead of relying on the wrong pre-processing of a future CSS feature!

**Pull request closed without merging**
