### PR TITLE
fix(generators, templates): add example app functionality into project templates and generators

### PR DESCRIPTION
**Pull request by jeremyadavis**
Implements recommendations from #1286 

The updates are slightly opinionated by including propTypes and styled-components. 
I considered replacing the <div> wrapping generated components with a ```styled.div``` Wrapper component, but was unsure if others would find it useful or annoying in the case they don't use them.

### CODE REVIEW

**Comment by gihrig** [comment]
I generated all three flavors of components and and both of containers. I get a `no-unused-vars' lint error on all three
image

After clearing those (and expected tests), all is good :smile:

**Comment by jeremyadavis** [comment]
Yeah, that was another reason why I considered making the Wrapper component to use the styled variable. 

Would you rather I just ```eslint-disable-line no-unused-vars``` on the styled-components import or go ahead and make the Wrapper component?

**Comment by gihrig** [comment]
That's a good question. In the example app:
8 of 15 components have no wrapper, styles are applied in index.js.
7 of 15 components have some type of wrapper file for styles, usually called "wrapper".

Given that:
1. The wrapper tag to be `styled.` can vary, `div`, `header`, `section`, `footer`, component, etc.
2. The balance between wrapped and un-wrapped is about even in the example app.
3. The wrapped vs un-wrapped balance is (mostly) "react components" vs styled html tags.
4. The components created are expected to be part of a finished app, not just an example.

My ideal would be to add a prompt to the generators "do you want styles?" and if yes, "do you want a style wrapper?" and build accordingly.

If that's more than you want to take on now, I would suggest to simply include the import, and comment it out.

```javascript
// import styled from 'styled-components';
```

I'm interested to hear what @mxstbr thinks about this.

**Comment by jeremyadavis** [comment]
I went with just commenting the import out for now since there was just work done to remove the 'do you want styles?' prompt.

For my projects I prefer to use a styled Wrapper on my components instead of a plain div so that I can easily start styling the component and leverage props and global styles if need be.

**Comment by gihrig** [comment]
Thanks @jeremyadavis! That's perfect 💯 

In the interest getting 3.4 shipped, I'm going to "Update branch"...

**Comment by gihrig** [comment]
@mxstbr LGTM, Comments?

**Comment by mxstbr** [comment]
Awesome, thank you!

**Pull request merged**
