### PR TITLE
Remove isparta

### PR DESCRIPTION
**Pull request by samit4me**
PR for #924.

Remove `isparta` as it appears to be no longer used.

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, thanks!

**Comment by mydearxym** [comment]
without `isparta` staff ,  may cause `npm run test `  build error.

```js
......
WARNING in ./app/components/Button/tests/index.test.js
Module build failed: Error: Line 5: Unexpected token
    at constructError (xxxxxxx/node_modules/esprima/esprima.js:2406:21)
    at createError 
....
```

**Comment by samit4me** [comment]
Hi @mydearxym , that's very unfortunate. I would love to try and help resolve the issue, but I was unable to replicate the issue on Win10 or OS X El Capitan.

Would you mind sharing further details, it would be greatly appreciated, things like:
- Environment; OS, node and npm versions?
- Did you get this error on the `dev` branch?
- Have you modified the `Button` tests? If so, can you share?
- Have you tried deleting the `node_modules` folder and running `npm install` again before running the tests?

**Comment by mydearxym** [comment]
@samit4me  sorry, this boilerplate dev branch is ok , the error is in [my own project](https://github.com/mydearxym/coder_club_frontend) which is basiclly the same to this boilerplate

env: node 5.12
       npm 3.8.6
       macOS 10.11


when i rm the `isparta` in webpack.test.babel.js i got those error (i reinstalled the deps by `npm install`):

```js
WARNING in ./app/components/Button/tests/index.test.js
Module build failed: Error: Line 5: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$

WARNING in ./app/components/Footer/index.js
Module build failed: Error: Line 1: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$

WARNING in ./app/components/Footer/tests/index.test.js
Module build failed: Error: Line 1: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$

WARNING in ./app/components/H1/index.js
Module build failed: Error: Line 3: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$

WARNING in ./app/components/H1/tests/index.test.js
Module build failed: Error: Line 1: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$

WARNING in ./app/components/H2/index.js
Module build failed: Error: Line 3: Unexpected token
    at constructError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta/lib/instrumenter.js:68:39)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/isparta-loader/index.js:18:25)
 @ ./app ^^((?!(app|reducers|routes)).)*\.js$


 and lots more ...
```

**Comment by samit4me** [comment]
Thank you for all the details @mydearxym . Yes, applying this PR manually to a fork of `master`, like [your project](https://github.com/mydearxym/coder_club_frontend/tree/master/app), would certainly cause issues like you have described. 

**Why?** This PR can be seen as part 2 to #795 , where `isparta` was replaced with `istanbul`,  in that commit `isparta` was left behind but no longer used, so this PR removed it. Further details available in the [Issue](https://github.com/mxstbr/react-boilerplate/issues/924) #924 for this PR.

Once this PR and all the other PR's are merged to `master` you should be able to merge them into your project without the issues you described.

Sorry about the confusion and I hope this answers your questions?

**Comment by mydearxym** [comment]
@samit4me  thanks for the patience!  i manually merge the #795 and everything works fine !
sorry for I did not look carefully, thanks again!

**Pull request merged**
