### PR TITLE
chore(setup): remove LGTM config files

### PR DESCRIPTION
**Pull request by Dattaya**
We got extra lucky this time, just as we started using LGTM github hook, it became discontinued 😛:
    lgtm main page

Two alternatives that I'm aware of:
- Use github's own system (@gihrig's idea), that will enforce one approved review. We can require at least two reviews by convention, I'll gladly contribute `Maintainers.md` file with these instructions.
protecte branch

- Switch to https://about.pullapprove.com which is free for OSS and has a lot of features.

### CODE REVIEW

**Comment by Dattaya** [comment]
@mxstbr, you'll need to disable it, I think on Webhooks' page in repo's settings.

**Comment by mxstbr** [comment]
Disabled, that's a huge shame! Let's just use GitHub's built-in feature then, as that's only going to get better 😎

**Comment by mxstbr** [comment]
Disabled LGTM.co, enabled PR reviews!

**Comment by mxstbr** [comment]
CI fails due to unrelated reasons, any idea what's going on there?

**Comment by gihrig** [comment]
```
ERROR in ./~/react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' in '/home/travis/build/mxstbr/react-boilerplate/node_modules/react-addons-test-utils'
 @ ./~/react-addons-test-utils/index.js 1:17-56
 @ ./~/react-element-to-jsx-string/index-dist.js
 @ ./~/chai-enzyme/build/assertions/contain.js
 @ ./~/chai-enzyme/build/index.js
 @ ./internals/testing/test-bundler.js
```
I think this is fixed in `dev` by tracking `react-addons-test-utils`as a dependency. `3.3.3` does not track this dependency and with `react` and `react-dom` pinned at `15.3.2` we have a broken build in master as result of this dep being updated (just what pinning dependencies was supposed to fix). 😦 

A hot fix patch to master tracking `"react-addons-test-utils": "15.3.2",` should fix this and allow the build to proceed. I say "should" because I have not tested this today, I did work through it when it first occurred (Nov 19).

**Comment by Dattaya** [comment]
>  let's add a MAINTAINERS.md in the .github/ folder and link to it from CONTRIBUTING.md. We'll send it to everybody that gets commit access!

Done! Also added initial 'Collaborating guidelines', please let me know what can be improved. 
Should I make every maintainer's nickname in `MAINTAINERS.md` a link to their profile page, maybe include their name in parenthesis?

**Comment by gihrig** [comment]
Shouldn't this PR target `dev`? Just as a matter of 'form'.

**Comment by Dattaya** [comment]
> Shouldn't this PR target dev? Just as a matter of 'form'.

There are no .lgtm and `Maintainers` files (which I removed) in dev, so not entirely possible, but I can send `Collaboration guidelines` to dev.

**Comment by gihrig** [comment]
> Shouldn't this PR target dev? Just as a matter of 'form'.

> There are no .lgtm and Maintainers files (which I removed) in dev

3.4 release happened...

Well, there are now 😁 

Also changed base to `dev`, in spite of this scary message:

>Are you sure you want to change the base?
Some commits from the old base branch may be removed from the timeline, and old review comments may become outdated.

We'll see where that leaves things 😨

**Comment by gihrig** [comment]
This got missed for 3.4 😢  It can be the first in 3.4.1 😄

**Comment by Dattaya** [comment]
Thank you, @gihrig, for your review and approval.

> This got missed for 3.4 😢 It can be the first in 3.4.1 😄

That's fine, it's primarily for collaborators' usage anyway. I'm going to add @KarandikarMihir to the list of maintainers before it's merged.

**Comment by gihrig** [comment]
@Dattaya 
>  I'm going to add @KarandikarMihir to the list of maintainers

Oh, good catch 😄  I'll watch for it...

**Comment by Dattaya** [comment]
done 😃 
Something's still wrong with Appweyor: `AppVeyor failed to assign job to 'gce' build environment after 3 attempt(s). The envronment is either unavailable or there are no free workers, however alternate build environment was not configured by the system administrator. Please try again later.`

**Comment by mxstbr** [comment]
Thanks @Dattaya!

**Pull request merged**
