### PR TITLE
chore(lgtm): update maintainers

### PR DESCRIPTION
**Pull request by Dattaya**
I did miss someone, turns out @jwinn is also a collaborator 😃

### CODE REVIEW

**Comment by gihrig** [comment]
````bash
ERROR in ./~/react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' in '/home/travis/build/mxstbr/react-boilerplate/node_modules/react-addons-test-utils'
````

3.3.3 will not build until `  "react-addons-test-utils": "15.4.0",` is added to `package.json`.

I think this is eligible to be a hotfix and version bump 3.3.4 on master, especially since it's a build-braking bug in master.

On the other hand, this change should be made to `dev` as well.

**Comment by Dattaya** [comment]
Yeah, this change is obviously not at fault here. We shouldn't worry about the dev branch too much, because `lgtm` plugin reads the config files only from master.
I have some bad news though, according to their [website](lgtm.co), lgtm service is being discontinued:
image

**Comment by gihrig** [comment]
Hmmm...

GitHub has a sort of halfway competitor in repo "Settings".

image

**Comment by Dattaya** [comment]
That's one way to do it—require one approved review, another option— https://about.pullapprove.com/, the service is free for OSS.

**Pull request closed without merging**
