### PR TITLE
log coverage during npm test

### PR DESCRIPTION
**Pull request by ccorcos**
```
START:
19 05 2016 11:53:20.971:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 05 2016 11:53:20.984:INFO [launcher]: Starting browser Chrome
19 05 2016 11:53:22.416:INFO [Chrome 49.0.2623 (Mac OS X 10.11.3)]: Connected on socket /#rNoswUWdY2L5DopLAAAA with id 7918641
ERROR: 'Warning: Failed propType: Required prop `href` was not specified in `A`.'
  <A />
    ✔ should render its children
ERROR: 'Warning: Failed propType: Required prop `children` was not specified in `A`.'
    ✔ should adopt the className
    ✔ should adopt the href
    ✔ should adopt the target
  <Button />
    ✔ should render its children
ERROR: 'Warning: Failed propType: Required prop `children` was not specified in `Button`.'
    ✔ should adopt the className
    ✔ should render an <a> tag if no route is specified
    ✔ should render a button to change route if the handleRoute prop is specified
    ✔ should handle click events
  <Footer />
    ✔ should render the copyright notice
    ✔ should render the credits
  <H1 />
    ✔ should render its text
  <H2 />
    ✔ should render its text
  <H3 />
    ✔ should render its text
  <Img />
    ✔ should render an <img> tag
    ✔ should have an alt attribute
  <IssueIcon />
    ✔ should render a SVG
  <List />
    ✔ should render the component if no items are passed
    ✔ should render the items
  <ListItem />
    ✔ should adopt the className
    ✔ should render the content passed to it
  <LoadingIndicator />
    ✔ should render 14 divs
  App Actions
    loadRepos
      ✔ should return the correct type
    reposLoaded
      ✔ should return the correct type and the passed repos
    repoLoadingError
      ✔ should return the correct type and the error
ERROR: 'Warning: Failed propType: Invalid prop `src` of type `object` supplied to `Img`, expected `string`.'
  <App />
    ✔ should render the logo
    ✔ should render its children
    ✔ should render the footer
  appReducer
    ✔ should return the initial state
    ✔ should handle the loadRepos action correctly
    ✔ should handle the reposLoaded action correctly
    ✔ should handle the repoLoadingError action correctly
  selectGlobal
    ✔ should select the global state
  selectCurrentUser
    ✔ should select the current user
  selectLoading
    ✔ should select the loading
  selectError
    ✔ should select the error
  selectRepos
    ✔ should select the repos
  selectLocationState
    ✔ should select the route as a plain JS object
  <FeaturePage />
    ✔ should render its heading
    ✔ should link to "/"
  Home Actions
    changeUsername
      ✔ should return the correct type and the passed name
  <HomePage />
    ✔ should render the loading indicator when its loading
    ✔ should render an error if loading failed
    ✔ should render the repositories if loading was successful
    ✔ should link to /features
  homeReducer
    ✔ should return the initial state
    ✔ should handle the changeUsername action correctly
  getGithubData Saga
    ✔ should dispatch the reposLoaded action if it requests the data successfully
LOG: undefined
    ✔ should call the repoLoadingError action if the response errors
  selectHome
    ✔ should select the home state
  selectUsername
    ✔ should select the username
  <NotFound />
    ✔ should render the Page Not Found text
    ✔ should render a button
    ✔ should link to "/"
  <RepoListItem />
    ✔ should render a ListItem
    ✔ should not render the current username
    ✔ should render usernames that are not the current one
    ✔ should render the repo name
    ✔ should render the issue count
    ✔ should render the IssueIcon
  hooks
    getHooks
      ✔ given a store, should return all hooks
    helpers
      injectAsyncReducer
        ✔ given a store, it should provide a function to inject a reducer
      injectAsyncSagas
        ✔ given a store, it should provide a function to inject a saga
  request
    stubbing successful response
      ✔ should format the response correctly
    stubbing error response
      ✔ should catch errors
----------------------------------------|----------|----------|----------|----------|----------------|
File                                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------------|----------|----------|----------|----------|----------------|
 app/                                   |      100 |    96.15 |      100 |      100 |                |
  reducers.js                           |      100 |      100 |      100 |      100 |                |
  store.js                              |      100 |    91.67 |      100 |      100 |                |
 app/components/A/                      |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/A/tests/                |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/Button/                 |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/Button/tests/           |      100 |      100 |     87.5 |      100 |                |
  index.test.js                         |      100 |      100 |     87.5 |      100 |                |
 app/components/Footer/                 |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/Footer/tests/           |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/H1/                     |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/H1/tests/               |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/H2/                     |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/H2/tests/               |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/H3/                     |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/H3/tests/               |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/Img/                    |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/Img/tests/              |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/IssueIcon/              |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/IssueIcon/tests/        |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/List/                   |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/List/tests/             |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/ListItem/               |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/ListItem/tests/         |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/components/LoadingIndicator/       |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
 app/components/LoadingIndicator/tests/ |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/containers/App/                    |      100 |    92.86 |      100 |      100 |                |
  actions.js                            |      100 |      100 |      100 |      100 |                |
  constants.js                          |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
  reducer.js                            |      100 |      100 |      100 |      100 |                |
  selectors.js                          |      100 |       50 |      100 |      100 |                |
 app/containers/App/tests/              |      100 |      100 |      100 |      100 |                |
  actions.test.js                       |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
  reducer.test.js                       |      100 |      100 |      100 |      100 |                |
  selectors.test.js                     |      100 |      100 |      100 |      100 |                |
 app/containers/FeaturePage/            |    96.72 |      100 |    85.71 |    85.71 |                |
  index.js                              |    96.72 |      100 |    85.71 |    85.71 |          96,97 |
 app/containers/FeaturePage/tests/      |      100 |    83.33 |      100 |      100 |                |
  index.test.js                         |      100 |    83.33 |      100 |      100 |                |
 app/containers/HomePage/               |    94.38 |    93.55 |    81.48 |    90.63 |                |
  actions.js                            |      100 |      100 |      100 |      100 |                |
  constants.js                          |      100 |      100 |      100 |      100 |                |
  index.js                              |    93.26 |     97.3 |    72.22 |    83.33 |... 126,127,140 |
  reducer.js                            |      100 |      100 |      100 |      100 |                |
  sagas.js                              |    92.86 |    84.21 |      100 |      100 |                |
  selectors.js                          |      100 |      100 |      100 |      100 |                |
 app/containers/HomePage/tests/         |      100 |    95.45 |      100 |      100 |                |
  actions.test.js                       |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |    83.33 |      100 |      100 |                |
  reducer.test.js                       |      100 |      100 |      100 |      100 |                |
  sagas.test.js                         |      100 |      100 |      100 |      100 |                |
  selectors.test.js                     |      100 |      100 |      100 |      100 |                |
 app/containers/NotFoundPage/           |       90 |      100 |       60 |    83.33 |                |
  index.js                              |       90 |      100 |       60 |    83.33 |          35,36 |
 app/containers/NotFoundPage/tests/     |      100 |    83.33 |      100 |      100 |                |
  index.test.js                         |      100 |    83.33 |      100 |      100 |                |
 app/containers/RepoListItem/           |    98.36 |      100 |    90.91 |    94.12 |                |
  index.js                              |    98.36 |      100 |    90.91 |    94.12 |             66 |
 app/containers/RepoListItem/tests/     |      100 |      100 |      100 |      100 |                |
  index.test.js                         |      100 |      100 |      100 |      100 |                |
 app/utils/                             |      100 |      100 |      100 |      100 |                |
  hooks.js                              |      100 |      100 |      100 |      100 |                |
  request.js                            |      100 |      100 |      100 |      100 |                |
 app/utils/tests/                       |      100 |      100 |      100 |      100 |                |
  hooks.test.js                         |      100 |      100 |      100 |      100 |                |
  request.test.js                       |      100 |      100 |      100 |      100 |                |
----------------------------------------|----------|----------|----------|----------|----------------|
All files                               |    98.82 |    97.49 |    95.94 |    98.53 |                |
----------------------------------------|----------|----------|----------|----------|----------------|


Finished in 0.33 secs / 0.161 secs

SUMMARY:
✔ 65 tests completed
```

### CODE REVIEW

**Comment by mxstbr** [comment]
I like this, but think we should make it optional. What about a second command like `npm run test:cov`?

**Comment by mxstbr** [comment]
_ping_

> What about a second command like npm run test:cov?

**Comment by ccorcos** [comment]
Hey! Sorry, been pretty busy. That works for me -- I'd prefer if it were the default, but up to you... Tests passing doesnt really mean anything without seeing the coverage of those tests, you know?

**Comment by mxstbr** [comment]
That's true, but showing all the information seems a bit much. Is there maybe a compact formatter?

**Comment by ccorcos** [comment]
```
  request
    stubbing successful response
      ✔ should format the response correctly
    stubbing error response
      ✔ should catch errors

=============================== Coverage summary ===============================
Statements   : 98.82% ( 1175/1189 ), 40 ignored
Branches     : 97.49% ( 350/359 ), 64 ignored
Functions    : 95.94% ( 260/271 ), 5 ignored
Lines        : 98.53% ( 737/748 )
================================================================================

Finished in 0.393 secs / 0.237 secs

SUMMARY:
✔ 65 tests completed
```

**Comment by mxstbr** [comment]
This is awesome! Thanks @ccorcos! :+1:

**Comment by ccorcos** [comment]
of course! and thanks for the boilerplate :)

**Pull request merged**
