### PR TITLE
Added react-optimize to package.json

### PR DESCRIPTION
**Pull request by azampagl**
Removed a few "babel-plugin-transform-react-*" packages as they are already included in the optimize package.

### CODE REVIEW

**Comment by mxstbr** [comment]
We already have #360, which has the same problem as this PR. Do you have any idea why the CI fails?

**Comment by azampagl** [comment]
Not sure that I do... Mine passed and built successfully locally. The only "major" difference I see is that I'm running node 6.x, while the continuous integration environments are 5.x. What version is @Aweary running?

**Comment by Aweary** [comment]
@azampagl it passed locally for me as well, and I tried it on 5.x and 6.x

**Comment by SilentCicero** [comment]
@Aweary @azampagl @mxstbr getting the same failed travis/appveyor errors as well on my PR. It's very hard to recreate this environment locally. All tests pass locally and on the travis support. Anyone have any thoughts on this?

**Comment by SilentCicero** [comment]
Re: `travis-ci/appveryor errors` -- https://github.com/mxstbr/react-boilerplate/pull/391#issuecomment-222334520 @mxstbr @Aweary @azampagl

**Comment by mxstbr** [comment]
I'll close this as a duplicate of #360, thanks for taking the time to submit this PR @azampagl, sorry you were those few minutes too late! Appreciate it! :+1:

**Pull request closed without merging**
