### PR TITLE
Fix the generator only works when indentation is 2.

### PR DESCRIPTION
**Pull request by ZhuGongpu**
Remove the magic numbers and the problem is solved.

### CODE REVIEW

**Comment by mxstbr** [comment]
Why use `\s{0,}` vs. `\s*`? Don't they achieve the same thing?

**Comment by ZhuGongpu** [comment]
`\s*` may contain other characters.

**Comment by mxstbr** [comment]
I've restarted TravisCI, waiting for it to finish then I'll merge this. Thanks @ZhuGongpu!

**Comment by mxstbr** [comment]
Thanks @ZhuGongpu, this is great! :tada:

**Pull request merged**
