### PR TITLE
Improve formatting.

### PR DESCRIPTION
**Pull request by kxxoling**
Just some formatting improvement.

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks good, would you mind rebasing onto master please?

**Comment by mxstbr** [comment]
Deploy preview ready!

Built with commit bf1ac8cc64ef21572444c8eefa6629feaa82137f

http://deploy-preview-867.react-boilerplate.netlify.com

**Comment by kxxoling** [comment]
Hello @mxstbr , rebasing finished and all checks has passed.

**Comment by mxstbr** [comment]
Awesome, thanks!

**Comment by kxxoling** [comment]
:)

**Pull request merged**
