### PR TITLE
Add a key property to IntlProvider

### PR DESCRIPTION
**Pull request by andregoncalvesdev**
Add a key property to IntlProvider which persuades React that the component has been modified, so when we use changeLocale it automatically re-renders.

### CODE REVIEW

**Comment by mxstbr** [comment]
Good catch, thanks!

**Comment by mxstbr** [comment]
Awesome, thanks so much!

**Comment by sedubois** [comment]
@mxstbr was it intended to merge to `master`?

**Comment by mxstbr** [comment]
God dammit, my bad. Can you revert this and merge it into dev? Thanks!

**Pull request merged**
