### PR TITLE
** React-intl #391 via @SilentCicero

### LINKED ISSUE #377: i18n support: react-intl
Internationalization is a huge part of Apps that scale. Without efficient i18n support an app has to hard code all language into separate builds by hand. What is everyone's thoughts on integrating i18n support?

Perhaps:
https://github.com/yahoo/react-intl
https://github.com/ratson/react-intl-redux

This package looks to be the most reasonable with a provider design. This module also provides pluralization support which is necessary for most apps.

I can provide a PR if we feel we should move forward with this.

Language files could be implemented with the same approach we take to constants:

For example, FeaturePage Scaffolding Text:

`boilerplate.containers.FeaturePage.scaffolding.header` = "Quick scaffolding"
`boilerplate.containers.FeaturePage.scaffolding.message` = "Automate the creation of components, containers, routes, selectors and sagas - and their tests - right from the CLI!"

That looks like this:
```
          <li className={styles.listItem}>
            <p className={styles.listItemTitle}>
              <FormattedMessage
                id="boilerplate.containers.FeaturePage.scaffolding.header"
                defaultMessage={`
                  Quick scaffolding
                `}
              />
            </p>
            <p>
              <FormattedMessage
                id="boilerplate.containers.FeaturePage.scaffolding.message"
                defaultMessage={`
                  Automate the creation of components, containers, routes, selectors
                  and sagas - and their tests - right from the CLI!
                `}
              />
            </p>
          </li>
```

The Intl Provider looks something like this in the app/app.js:

```
ReactDOM.render(
  <Provider store={store}>
    <IntlProvider locale="en">
      <Router
        history={history}
        routes={rootRoute}
        render={
          // Scroll to top when going to a new page, imitating default browser
          // behaviour
          applyRouterMiddleware(
            useScroll(
              (prevProps, props) => {
                if (!prevProps || !props) {
                  return true;
                }

               .....
```

### PR DESCRIPTION
**Pull request by justingreenberg**
## #391 via @SilentCicero (Continued)

The other pull request was getting too difficult to track and sync with master, and @SilentCicero has been busy this week. This PR includes all original contributions (~80 commits) by @SilentCicero, @benjaminlgt-littlelives and myself so credit is given to original contributors ❤️ 

Resolves #377... one final push to get this merged! 

So much work has gone into it by so many people. I added the script animations and synced everything with master, so it feels like we are really on verge of shipping  🎉 

So, @mxstbr [most recent code review](https://github.com/mxstbr/react-boilerplate/pull/391#issuecomment-232287102):

To be reviewed:
 1. [x] Should we run npm run `extract-intl` after generating a language so the .json is filled with something? (**Done in 61376a3**)
 1. [x] after running npm run clean the i18n.js still references german a few times, but not everywhere (**Done in 702b88c, 4f34213, 4f34213**)
 1. [x] When cleaning completely replace the LanguageProvider, like the other containers. Simply leaving it be won't work since people might've played around/changed the example, and if they changed/broke the LanguageProvider they'll still have those changes after cleaning, which is a no-go! (**Done in 2efa7c3**)

Done:
 1. [x] In German, the "Features" page has one title and description inverted (13ca2c9)
 1. [x] Insert empty last line into the JSON files when running npm run extractIntl, otherwise there's unnecessary git changes (7c5d57b, df53309)
 1. [x] npm run extractIntl should show progress indicator like other scripts (334d2e4) _note: i updated script and docs to be `extract-intl` for our linux friends_ 

cc/ interested parties: @gihrig @breandr @rog @joeblew99 @chaintan17

### CODE REVIEW

**Comment by chaintan17** [comment]
Hi all, 
for the first item (run `extract-intl` after generate new langauge)
I've done it. These are the changes
https://github.com/chaintan17/react-boilerplate/commit/61376a3f49720247761c9bd82e509f1f9ee60180

Moreover, last issue also mentioned that there is an extra line in `i18n.js` file when generate new langauge.
I also fix it in this commit
https://github.com/chaintan17/react-boilerplate/commit/df533097b067000c0bef45740d79f2e90291d438

I have no write access to this pull request, so please review it in the above link instead.

Thank you everybody, you guys have done really amazing jobs!

**Comment by mxstbr** [comment]
@chaintan17 you can submit those changes as Pull Requests against https://github.com/justingreenberg/react-boilerplate! Then they'll pop up here as soon as they're merged.

**Comment by chaintan17** [comment]
@mxstbr i tried but it now create another pull request
https://github.com/mxstbr/react-boilerplate/pull/787

not sure if i did something wrong 😕

**Comment by chaintan17** [comment]
Actually, i find a bug.
after run `npm run clean`, the javascript console log throw below error
`index.js:1069 [React Intl] Missing locale data for locale: "undefined". Using default locale: "en" as fallback.`

Because after the project get cleaned, it accidentally remove the combined reducer for language.
I will push the commit for fix this issue.

**Comment by justingreenberg** [comment]
Thank you @chaintan17, commits look solid! I have merged them in for you :)

**Comment by mxstbr** [comment]
Reviewing now!

**Comment by mxstbr** [comment]
Oh. my. god.

Dare I say it.

🎉 IT'S PERFECT 🎉

Thanks so much everybody for pulling through with this, I couldn't be more excited about having this included in the boilerplate. Fuck yeah, give yourself a pat on the back everyone, this is amazing! 🎉

**Comment by mxstbr** [comment]
The eagle has landed, the eagle has landed!

**Comment by chaintan17** [comment]
Hoorayyyy!!  Feeling good to be a tiny part of this enormous and vital feature :)

**Comment by chaintan17** [comment]
please check this https://github.com/mxstbr/react-boilerplate/pull/790/files

**Pull request merged**
