### PR TITLE
Istanbul

### LINKED ISSUE #274: Switch to Babel for code coverage
http://dev.topheman.com/es6-code-coverage-with-babel-plugin/

Looks like isparta not maintained anymore. Above article suggest an alternative.

### PR DESCRIPTION
**Pull request by FezVrasta**
This PR replaces the isparta coverage reported (not maintained anymore) with Istanbul instrumenter.

Please carefully check that everything still works as expected, I've not a lot of experience with coverage reports.

Closes #274

### CODE REVIEW

**Comment by FezVrasta** [comment]
https://github.com/mxstbr/react-boilerplate/pull/579#issuecomment-227095304 at least it seems to work 🙃

**Comment by mxstbr** [comment]
This looks solid, all the tests still run!

Need to check the coverage report locally, give me a few minutes…

**Comment by mxstbr** [comment]
Also, how is this different/better/worse than the approach with Babel as detailled in the article in #274?

**Comment by mxstbr** [comment]
Two small problems with this:

1. It shows the coverage in babel-compiled ES5 code, while we want our original ES6 source code. (see screenshot below, source maps are missing)

  screen shot 2016-06-20 at 17 10 28

2. It still covers test files, and also covers `internals/testing/` on top of that.

Any idea how to fix those?

**Comment by mxstbr** [comment]
_ping_ any updates here?

**Comment by FezVrasta** [comment]
Hey, sorry, I guess we should close this. I've implemented a new one using nyc now, but I've not time right now to prepare a PR.

**Pull request closed without merging**
