### PR TITLE
feat(ci): allow for linting of the templates

### PR DESCRIPTION
**Pull request by Dattaya**
Depends on:
  - [x] #1221
  - [x] #1234
  - [x] #1327
  - [x] #1329

TODO
 - [x] Add comment at the top describing the purpose of `generate-all-templates.js`
 - [x] Add inline comments where necessary
 - [x] `exit` in case of an error generating code from a template?
 - [x] Update `yarn.lock`

What do you folks think about it, do we need to lint and check for errors of the generators themselves and generated code?

### CODE REVIEW

**Comment by mxstbr** [comment]
Yes I'd love to land this! We really really need it!

**Comment by gihrig** [comment]
@Dattaya Re: merge conflict:
image

I presume the eslint disable was a temporary measure? Or are you suggesting a different  handling?

The conflict is with #1327 which this PR "depends" on. My thought is that since we are generating a stub to be completed by the end user (developer), the eslint disable is more confusing, it looks more like there might be a reason for it that the dev will not immediately grasp. The `return null` is fine until one looks at a real sagas.js in the example app and sees there is no need for the return.

Now that I have looked at this more closely, maybe a better approach would be to remove the truly useless return and replace it with an informative comment e.g.

> // See example project containers/HomePage/sagas.js

That eliminates the lint error and makes the project more usable all at the same time :smile:

I have edited the conflict with that solution, feel free to disagree 😉

**Comment by Dattaya** [comment]
@gihrig, many thanks for merging those two PRs and looking into this one ❤️, that means I will be able to finish it today. 

> I presume the eslint disable was a temporary measure?

Yes, that's correct, and I prefer your solution, because it's conciser, either way a dev would delete it.

> Now that I have looked at this more closely, maybe a better approach would be to remove the truly useless return and replace it with an informative comment e.g.

Sounds like a good idea to me.

**Comment by Dattaya** [comment]
> Coverage increased (+0.007%) 

Good one, coveralls, 😁
Now my TODO list is empty, except the one TODO you can see in `generate-templates-for-linting` file, but it's not a big deal, `console.error` is synchronous on Mac according to the Node.js docs, but it also behaves synchronously on Windows in my experience, all error messages were successfully flushed into the terminal, it can be left as is until we experience any issues with it. 

Should be ready for review. If you have any questions about this PR, don't hesitate to ask them.

**Comment by gihrig** [comment]
I imported your branch `lint-generated-templates` (88f35e95fd332ffaaeaa3dc4602e1ab5d5a74a30) into my RBP local project.

I pushed to my GitHub repo (setup for Coveralls, Travis and AppVeyor).

Both Travis and AppVeyor successfully completed the build.

**Pull request merged**
