### PR TITLE
FIX 852, 1074 - Add doc about local caching issue in the FAQ.

### PR DESCRIPTION
**Pull request by Vadorequest**
## Add doc about local caching issue in the FAQ

Add documentation to the FAQ about the F5/Ctrl+F5 AKA local caching issue.
See https://github.com/mxstbr/react-boilerplate/issues/852#issuecomment-252037351

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
A couple of question, if you don't mind :)

Is this only a problem when running locally, or would you get the same problem when deploying under the same circumstances? Also, is the cache-related problem only present when updating during the same browser session?

Thanks!

**Comment by Vadorequest** [comment]
@gihrig Done! Btw you can edit directly the file from github, faster than asking for review when it's just typos ;)

**Comment by gihrig** [comment]
>  Btw you can edit directly the file from github, faster than asking for review when it's just typos ;)
@Vadorequest Didn't know that, thanks!

**Comment by gihrig** [comment]
@GGAlanSmithee These are great questions, but I would like to have them in #1074 where others are more likely to find them when searching.

Please add to #1074, just copy and paste.

**Comment by gihrig** [comment]
Great job @Vadorequest Thanks! 🎉

**Pull request merged**
