### PR TITLE
v3.2.0

### PR DESCRIPTION
**Pull request by mxstbr**
*It's been two weeks since the last release, so I figured we might as well prepare a new one!*

# Changelog

- Use `babel-plugin-istanbul` for more accurate code coverage (thanks to @kane-c!)
- Move `cross-env` and `minimist` to `dependencies` so `npm install --production` works (thanks @Dattaya!)
- Update dependencies (thanks @gihrig!)
- Fix indentation of `Helmet` when generating a container (thanks @Dattaya!)
- Fix intl polyfill race condition (thanks @kachkaev!)
- Fix container template (thanks @tbash!)
- Fix spelling errors around the codebase (thanks @stevenspiel!)
- Fix reducers stacking up (thanks @justingreenberg!)
- Fix new linting errors due to eslint upgrade and enable stricter linting (thanks @peter-mouland!)
- Fix test warnings in example (thanks @samit4me!)

### CODE REVIEW

**Comment by kachkaev** [comment]
Is there anything else left to do before the release?

**Comment by kachkaev** [comment]
Actually there might be an issue with a dependency now.

```bash
git clone --branch dev --depth 1 git@github.com:mxstbr/react-boilerplate.git
cd react-boilerplate
git --no-pager log --pretty=oneline --all
# 2cd4751d0526dd55e316561d646b2a8710c18dd0 Merge branch 'master' into dev
say "have some coffee" && npm run setup && say "now put your coffee away"
npm run clean
npm start
```

screen shot 2016-09-03 at 17 34 24


On top of this, the currently chosen source maps do not work out of the box in Chrome 54 on OSX. Can be webpack-related. Discussion here: https://github.com/webpack/webpack/issues/2145

**Comment by gihrig** [comment]
I have confirmed @kachkaev 's findings, both the error and the **UPD**

> UPD: The problem went away after removing the DLL plugin section from package.json.

All that was required after removal of `package.json` `dllPlugin` section was a server restart and the app loads as expected no error.

Restoring the `DllPlugin` section and restarting the server brings back the error.

Chrome: Version 53.0.2785.89 (64-bit)
OS X: 10.11.6
npm: 3.10.6
node: 6.4.0

**Comment by gihrig** [comment]
The error reported by @kachkaev seems to be resolved by updating to `webpack@2.1.0-beta.21`

But that update triggers an error reported in #922 which is fixed by updating to `react-router-scroll@0.3.2` and changing 

`import useScroll from 'react-router-scroll'` -> `import { useScroll } from 'react-router-scroll'` 

In: `/app/app.js and /internals/templates/app.js`

Thanks @timgaines [#922 (comment)](https://github.com/mxstbr/react-boilerplate/pull/922#issuecomment-243001753) and @jwyuen #950

@mxstbr I think these updates are OK in the weekly dependency update, as opposed to a separate PR. 

Your thoughts?

**Comment by gihrig** [comment]
The updates mentioned above touch off a chain reaction of breaking dependency updates and configuration changes.

IMO, dev is _not_ ready for v3.0.2!

@mxstbr It seems that releasing dev HEAD as master is asking for trouble. Latest relatively untested commits...

But at what point is dev stable, two weeks old commit? This kind of thing is the reason for feature freezes and release branches, etc. That adds a degree of complexity that IMO discourages some degree of testing. ie: do people work on the dev branch to add features, find and fix bugs, or do they work on a release branch to make it solid enough to become a release?

After spending most of my day chasing expanding dependency related issues I'm not sure what's the best way forward... :-/

**Comment by gihrig** [comment]
Considering the chain reaction nature of updates and errors I have experienced, I think the above error should be corrected before any further updates are committed. So, I have not opened a PR for dependency updates.

**Comment by gihrig** [comment]
Reopening #950 to work on this.

Partial solution in PR #952

**Comment by gihrig** [comment]
Once #952 has been merged, this should be OK. @mxstbr @kachkaev can you guys test?

**Comment by kachkaev** [comment]
Thanks @gihrig! A shallow check of this was successful for me:

```bash
git clone --branch webpack-imported --depth 1 git@github.com:gihrig/react-boilerplate.git
cd react-boilerplate
git --no-pager log --pretty=oneline --all
# 8174382fb6f7db095940a8b9c199f470b65c4247 Merge pull request #1 from Dattaya/webpack-imported
npm run setup
npm run clean
npm start
```

**Comment by mxstbr** [comment]
Is this ready, and should we merge the latest dep rollup (#956) before releasing? @gihrig

**Comment by gihrig** [comment]
> should we merge the latest dep rollup (#956)

Yes, that's in progress, will merge it (#956) as soon as ready, Then this should be good.

**Comment by gihrig** [comment]
@mxstbr Have tested using the test script I use for dependency updates - All pass 😄 

Looks good to me!

Node 6.4.0
npm 3.10.6
Mac OS 10.11.6
Chrome 53.0.2785.101 (64-bit)

**Comment by mxstbr** [comment]
### Plan

#### Land before v3.2 release

- #976 (needs testing)
- #967 (can merge manually before releasing)

#### Nice to have, but not necessary

- #894: Need to review this
- #931: I need to think a bit more about how the API works, get some feedback on what users think and play with it myself before merging it.  (/cc @chaintan17)

#### Future (prob v3.3)

- #811: Still waiting for docs of `PureComponent` as far as I'm aware? (/cc @justingreenberg)
- #980: Needs Jest to support generator functions, currently blocked (/cc @dimitriiabramov)

**Comment by justingreenberg** [comment]
> 811: Still waiting for docs of PureComponent as far as I'm aware?

👍 exactly, keeping this on my radar

**Comment by mxstbr** [comment]
This LGTM – @gihrig @justingreenberg you happy with this release?

**Comment by gihrig** [comment]
> This LGTM – @gihrig @justingreenberg you happy with this release?

One minor issue 😦 

Tested with update-deps test script - OK

> -- Test script --
> npm run setup
> Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
> npm run clean
> npm run generate component TestComp /w defaults
> npm run generate container TestPage /w defaults
> use TestComp on TestPage
> npm run generate route TestPage - /test
> npm start > localhost:3000/test
> git add .
> git commit -m "testing..."
> 
>   Node 6.4.0
> npm 3.10.6
> Mac OS 10.11.6
> Chrome 53.0.2785.101 (64-bit)
> 

Tested for #949 issue - OK
Tested for #978 issues - Lint error on generated container:

```bash
/Users/glen/Documents/JavaScript/Research/react-bp/app/containers/TestPage/selectors.js
  6:36  error  Expected parentheses around arrow function argument  arrow-parens
```

Looks like internals need some attention.  The specific error is in [`selectors.js.hbs`](https://github.com/mxstbr/react-boilerplate/blob/master/internals/generators/container/selectors.js.hbs#L6) but there are likely others. My test script only covers creation of components and containers with the default choices.

**Comment by peter-mouland** [comment]
hey all - sorry, i missed this comment.. but I'm on it now (the linting)

**Comment by peter-mouland** [comment]
I had a quick look but i'm uncomfortable changing those templates blind.

@gihrig how have you generated those files?  I guess you then updated the linting command to point to the generated folders?

If you are wanting generated files to be tested for linting errors, should we raise a ticket for that?  I feel like it is a separate issue as the current test-suite does not test generated code.

Not trying to come across as lazy, it just feels like a new feature to test generated files.  Once generated files are also put under the microscope other test `failures` may be uncovered.

thoughts?

**Comment by gihrig** [comment]
@peter-mouland Are you familiar with the project's [generator](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/commands.md#generators) feature?

This is the part of the test script (mentioned [above](https://github.com/mxstbr/react-boilerplate/pull/948#issuecomment-246541141)) I followed in discovering the error:

> npm run generate component TestComp /w defaults
> npm run generate container TestPage /w defaults
> use TestComp on TestPage
> npm run generate route TestPage - /test
> npm start > localhost:3000/test

If you need more detail than that (which is totally OK) please open a new issue and reference it here.

**Comment by peter-mouland** [comment]
I wasn't aware of the generators (looks cool though!).
I have raised a new issue : https://github.com/mxstbr/react-boilerplate/issues/988

**Comment by mxstbr** [comment]
Fixed the linting error, tried all the generators and this was the only one I found.

As soon as CI passes here we're good to 🚢!

**Comment by mxstbr** [comment]
Getting this error trying to start the app now:

```
app.js?2de9:126 Uncaught TypeError: __webpack_require__.i(...) is not a function
    at render (eval at <anonymous> (main.js:1347), <anonymous>:134:194)
    at eval (eval at <anonymous> (main.js:1347), <anonymous>:161:3)
    at Object.<anonymous> (main.js:1347)
    at __webpack_require__ (main.js:620)
    at fn (main.js:103)
    at Object.<anonymous> (main.js:2636)
    at __webpack_require__ (main.js:620)
    at main.js:699
    at main.js:702
```

Any ideas what's happening here?

**Comment by kachkaev** [comment]
Can you try to remove DLL section in package.json?

**Comment by gihrig** [comment]
@mxstbr I'm not seeing the error you listed above.

> Getting this error trying to start the app now:
> app.js?2de9:126 Uncaught TypeError: __webpack_require__.i(...) is not a function
> 

Maybe something in Chrome or npm cache?

I cloned a new copy, checked out `dev` branch
- Generate new container, `npm lint` - no errors closes #988 
- `npm test` Has test 'errors' and expected test failures.
- Merge #923 into `dev` - No test 'errors', expected test failures.

Looks like everything works. Would be nice to merge #923, hopefully that would be the last tweak to tests before conversion to Jest 😄 

Remove generated container to eliminate test failures.
- `npm run start:production` - works as expected, no errors.
- Merge `dev` into `master`, remove `node_modules`, `npm install`.
- `npm start` and `npm run start:production` work as expected no errors.

**Comment by mxstbr** [comment]
Hmm, will try again @gihrig, thanks for double checking me!

Merged #923, thanks @samit4me, will release this as soon as CI passes and I've managed to start the example!

**Pull request merged**
