### PR TITLE
fix(intl): polyfill for safari when clean the sample project

### PR DESCRIPTION
**Pull request by chaintan17**
After user run `npm run clean`
The clean project didn't implement polyfill for safari browser
and make the website unrendered.

### CODE REVIEW

**Comment by gihrig** [comment]
@chaintan17 Could you provide more description on the problem this PR solves?

**Comment by chaintan17** [comment]
Hi @gihrig , sorry for didn't mention it clearly.
I edit and update the description of this pull request.

**Comment by mxstbr** [comment]
Good catch @chaintan17! There's one semicolon missing then we can merge this:

```
/home/travis/build/mxstbr/react-boilerplate/internals/templates/app.js
  71:2  error  Missing semicolon  semi
```

**Comment by chaintan17** [comment]
i think i found another bug, let me check closely and will push another commit

```
[Error] [React Intl] Error formatting number.
ReferenceError: No locale data has been provided for this object yet.
	formatNumber
	formatNumber ([native code], line 0)
	render
	_renderValidatedComponentWithoutOwnerOrContext
	_renderValidatedComponent
	performInitialMount
	mountComponent
	mountComponent
	performInitialMount
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	performInitialMount
	mountComponent
	mountComponent
	performInitialMount
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	performInitialMount
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	performInitialMount
	mountComponent
	mountComponent
	mountChildren
	_createInitialChildren
	mountComponent
	mountComponent
	_mountChildAtIndex
	_updateChildren
	updateChildren
	_updateDOMChildren
	updateComponent
	receiveComponent
	receiveComponent
	updateChildren
	_reconcilerUpdateChildren
	_updateChildren
	updateChildren
	_updateDOMChildren
	updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	performUpdateIfNecessary
	performUpdateIfNecessary
	runBatchedUpdates
	perform
	perform
	perform
	flushBatchedUpdates
	(anonymous function) ([native code], line 0)
	closeAll
	perform
	batchedUpdates
	enqueueUpdate
	enqueueUpdate
	enqueueSetState
	setState
	handleChange
	handleChange ([native code], line 0)
	dispatch
	(anonymous function)
	(anonymous function)
	dispatch
	(anonymous function)
	flush
	asap
	runPutEffect
	runEffect
	next
	currCb
	run
	(anonymous function)
	flush
```

**Comment by mxstbr** [comment]
Thanks @chaintan17!

**Comment by chaintng** [comment]
Yes, i'm on commit `3515b78`
Safari version 9.1.2 😕

**Pull request merged**
