### PR TITLE
removing psi, pagespeed, and doc references

### PR DESCRIPTION
**Pull request by fisch0920**
Addresses #893

### CODE REVIEW

**Comment by gihrig** [comment]
@fisch0920 please describe why this change is needed? What problems does it solve?

Also see: [CONTRIBUTING.md](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)

**Comment by mxstbr** [comment]
Hey, would you mind rebasing this to remove merge conflicts? Then we can land this!

**Comment by KarandikarMihir** [comment]
Closing since no response from the author. Feel free to reopen.

**Comment by gihrig** [comment]
@fisch0920 Thanks for the PR! much appreciated! 🎉 

This has been fixed and merged in #1352.

**Comment by KarandikarMihir** [comment]
Mobile version doesn't show you this. I apologize! @fisch0920 Thanks for all the great work :)
screenshot from 2017-01-24 09 36 25

**Pull request closed without merging**
