### PR TITLE
Add if and if-else to container to link selector

### PR DESCRIPTION
**Pull request by tbash**
Modifies internals/generators/container/index.js.hbs with:
* if statment wrapped around selector include
* if and if-else wrapped around mapSateToProps add

If these are added and no selector is generated, this error is thrown: `Module not found: Error: Can't resolve './selectors`

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks reasonable, will review asap! Thanks @tbash!

**Comment by tbash** [comment]
Awesome, sounds good! You're welcome @mxstbr!

**Comment by mxstbr** [comment]
Much better, thanks @tbash! :tada:

**Comment by tbash** [comment]
Happy to help @mxstbr

**Pull request merged**
