### PR TITLE
Script to check the npm version before install

### PR DESCRIPTION
**Pull request by rogr**
If the npm version is lower to 3, then `npm install` doesn't start and show an error that says:
[`[ERROR: React Boilerplate] You need npm version @>=3`
](https://travis-ci.org/rogr/react-boilerplate/jobs/133679428#L276)
Otherwise if the version is major or equal to 3 `npm install` runs.

This helps with issues like #412, #385, ...etc.

### CODE REVIEW

**Comment by rogr** [comment]
Wait a moment I think I'm just complicated my self.
I only need to exec `npm -v`

**Comment by mxstbr** [comment]
Hmm, not 100% convinced this is a good idea.

We won't need `npm@>=3` forever, just until the react v15 and the webpack v2 update mania have died down and peer dependencies are normal again…

**Comment by rogr** [comment]
I can delete it when webpack v2 is updated.
What is your concern the extra file on `internals` ?

**Comment by mxstbr** [comment]
You're right! :grin: I like the solution you found, thanks @rogr!

**Pull request merged**
