### PR TITLE
Fix comment about how to use custom middlewares

### LINKED ISSUE #562: Adding your own custom backend-api is in the wrong place.
Started with this boilerplate to try it out. 
Just a note that I noticed that could confuse someone, when trying to add an api in the project. This is not the place to add an api because app is undefined. see: https://github.com/mxstbr/react-boilerplate/blob/master/server/index.js#L13

It needs to be in the frontendMiddleware or maybe middlewares directory needs a index.js file to structure different middlewares?

My solution for playing around at the moment has been to add an api directory in middlewares and require in frontendMiddleware.js and add `app.use('/api', api);` here: https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L64

### PR DESCRIPTION
**Pull request by SimonSelg**
This fixes #562

### CODE REVIEW

**Comment by SimonSelg** [comment]
The CI Build should work w/o errors once #572 gets merged or the bug is fixed by other means.

**Comment by mxstbr** [comment]
Nice one! Could you rebase onto master, then we'll get this merged!

**Comment by alikhani** [comment]
hmm.. @SimonSelg will that work? The reason I put in here [L64](https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L64) in In the frontendMiddleware is because of [L34](https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L34)

That line is going to swallow all request which means that you'll receive a 404 when requesting /api, right? Or am I missing something?

**Comment by SimonSelg** [comment]
@mxstbr: Done!

@alikhani: Good catch! Accidentally placed it in the wrong line. Fixed now. Thanks.

**Comment by mxstbr** [comment]
Thank you!

**Pull request merged**
