### PR TITLE
Add Gitter badge on Readme.

### PR DESCRIPTION
**Pull request by rogr**

### CODE REVIEW

**Comment by rogr** [comment]
not sure why the TravisCI failed, I only edited the Readme 😖

**Comment by mxstbr** [comment]
What would you think about adding another `<div align="center">` with the code-unrelated badges? (Sponsors, Backers & Gitter) This looks like a lot of stuff at the moment:

screen shot 2016-05-31 at 10 02 17

This is what we could change it to imo:

screen shot 2016-05-31 at 17 40 14

What do you think?

**Comment by SilentCicero** [comment]
@rogr the travisci fails due to whitespace issues: it's fixed in my PR @mxstbr: https://github.com/mxstbr/react-boilerplate/pull/391

**Comment by rogr** [comment]
@mxstbr: Yeah, looks nicer!

**Comment by mxstbr** [comment]
Nice one, thanks @rogr!

**Pull request merged**
