### PR TITLE
1st draft of a more feature-focused approach. Addresses #188

### PR DESCRIPTION
**Pull request by oliverturner**
Less about the implementation, more about the value that the features add.

I've tried to keep it punchy and minimal with enough detail for the curious. Writing style is always a matter of taste: I'll completely understand if you have different ideas.

The final "but wait..." section is just a stub: I'm a newcomer to this project, so I'm unaware of many of the goodies you've baked in. Please suggest more of the value-adds - linting is one I just saw - I've missed.

### CODE REVIEW

**Comment by mxstbr** [comment]
Great start, thanks for kicking things off!

I think we can get rid of the _via_s in the README, and mention the specific tools to achieve certain features in `docs/general/features.md`. We should definitely mention our new generators feature (ref #152), which is something that makes this boilerplate a lot nicer to use than others.

In the `but wait...` section, we could drop in "highly scalable" (or maybe "Build for scale" or something like that) and that we take care of a lot of details to make this a solid foundation.

I'll have to write down my thoughts about Domain Driven Development soon, and will add that later on as well!

Again, thanks for kicking things off and helping out!

**Comment by mxstbr** [comment]
Oooh I just noticed you worked on the `master` branch. That branch is ~200 commits behind the `v3.0.0` branch – could you submit a new PR against that one? Thanks!

**Comment by mxstbr** [comment]
I'm going to close this because this is not being merged, but thanks for the effort and please resubmit a PR against the `v3.0.0` branch!

**Comment by oliverturner** [comment]
No problem: will make the needed amends and resubmit on the correct branch :smile:

**Comment by grabbou** [comment]
That entire diff makes me feel like I have little english knowledge :o Looks really impressive!

**Comment by oliverturner** [comment]
@grabbou so about that...

1. Your English is great.
1. Even for a native speaker it's really hard to verbally convey the value of the ideas behind this project and the way they've been structured in a way that's honest, informative and brief.

Thanks for the kind words: freshly inspired to give this another go :)

**Pull request closed without merging**
