### PR TITLE
Fix typo in container generator

### PR DESCRIPTION
**Pull request by simonacca**
I agree to allow the project owners to license your work under the terms of the [MIT License](https://github.com/mxstbr/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by Dattaya** [comment]
Thanks, @simonacca, one more approval needed before we can :shipit:

**Comment by Dattaya** [comment]
ping @gihrig, @samit4me, can't merge without you

**Comment by samit4me** [comment]
LGTM

**Comment by gihrig** [comment]
Late to the party, sorry 😞  but what/who caused `LGTM` check to pass? There seems to be only one.

Anyway, thanks @simonacca, good catch and welcome to the project 🎉

**Comment by samit4me** [comment]
@gihrig I believe it is LGTM || `:shipit:`, https://github.com/mxstbr/react-boilerplate/blob/master/.lgtm

**Comment by gihrig** [comment]
I see. Thanks @samit4me

**Pull request merged**
