### PR TITLE
Updated all deps

### PR DESCRIPTION
**Pull request by oliverturner**
In honour of React v15 being released I went nuts and upgraded all the things :)

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, did you test all commands?

**Comment by oliverturner** [comment]
Not yet...

**Comment by mxstbr** [comment]
I'm about 99% ready to merge this, but does this conflict with @7rulnik's efforts in #254?

**Comment by oliverturner** [comment]
@mxstbr I honestly don't know: it might. I haven't checked because #254 always seemed as though it was on the cusp of being fixed/merged and my plan was to merge subsequently

More concerned about the state of the commands right now: haven't had a chance to validate all permutations

**Comment by mxstbr** [comment]
Fair enough, let's leave this one as blocked for now and merge #254 first!

**Comment by mxstbr** [comment]
Can you update to newest, fix the merge conflicts and then we'll merge this too! :tada:

**Comment by oliverturner** [comment]
Quite a number of changes due to additions to linting presets. Worth reviewing before merge @mxstbr

**Comment by mxstbr** [comment]
Will do, looks awesome! Thanks so much!!

**Comment by oliverturner** [comment]
Also... we _still_ need to do a full run-through of any issues arising with generators. May be worth getting #278 checked in first, merging result into this and then going for it...

**Comment by mxstbr** [comment]
Merged #278, merged into this branch. Testing most functionality now...

**Comment by mxstbr** [comment]
Upgraded everything, deleted unused dependencies and tried the most important commands, which are all working.

I'd say we merge this as soon as CI passes, and then if a command doesn't work as expected we'll know soon enough!

**Comment by mxstbr** [comment]
Fixed the linting problem, lets hope CI passes now!

**Comment by oliverturner** [comment]
Thanks for doing that :)

**Comment by mxstbr** [comment]
Doing some more small improvements and cleanup, tighter linting and such. Will merge as soon as I'm finished!

**Comment by mxstbr** [comment]
Added `eslint-plugin-jsx-a11y` as recommended in #290, and it's awesome!

**Pull request merged**
