### PR TITLE
Should not commit code for users.

### PR DESCRIPTION
**Pull request by jeregrine**
I did this on accident and lost a load of staged changes. Feels really bad.

### CODE REVIEW

**Comment by gihrig** [comment]
Please explain more about the steps that caused you to lose staged files. 

I made changes, staged them then executed `git add . --all` and `git commit -qm "Remove default example"` My changes were committed to my local repo as expected.

OS X 10.11.5
git version 2.7.4 (Apple Git-66)

**Comment by mxstbr** [comment]
> I did this on accident and lost a load of staged changes. Feels really bad.

I'm very very sorry, but I'm not 100% clear on how this made you loose any changes? Why would you run `npm run clean` after you've made changes to your app?

**Comment by jeregrine** [comment]
@mxstbr because I assumed it cleaned the build folder :P not remove all files. I will admit it was dumb to not read the code of the thing first.

@gihrig this command deletes all files that are non-generated, then commits. 

Just really bad practice to ever commit without user consent.

**Comment by jeregrine** [comment]
To be specific if you look at this https://github.com/mxstbr/react-boilerplate/pull/657/files#diff-0643478c0f20dbb3ca2bf263399d5963L27 it removes everything, then re-creates it.

**Pull request closed without merging**
