### PR TITLE
Deduplicated postcss webpack config

### PR DESCRIPTION
**Pull request by jskorepa**
Since postcss config were the same in both dev and prod I moved them to base config

see #947

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview failed.

Built with commit 55da66302b72f94c9ee8d455a49b17dfbacd40a8

https://app.netlify.com/sites/react-boilerplate/deploys/57d40e1c66867435ce5e6b4d

**Comment by kachkaev** [comment]
This section of the docs needs changing too I guess:
https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/postcss.md#adding-a-new-postcss-plugin

**Comment by kachkaev** [comment]
Great, thanks @jskorepa!

**Comment by mxstbr** [comment]
Awesome, this looks good to me!

**Comment by mxstbr** [comment]
Arrgggg I merged this into master 😓  @gihrig my bad!

**Comment by gihrig** [comment]
@mxstbr Heh, I noticed but decided not to comment 😉 

I have not tried [this](http://ohshitgit.com/?utm_source=Hashnode%20Times%20037&utm_medium=email&utm_campaign=Hashnode%20Weekly#accidental-commit-wrong-branch), but it looks like it _**should**_ do the trick.

**Comment by mxstbr** [comment]
It's fine, see #948 – we just prematurely released this fix 😁

**Pull request merged**
