### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by aried3r**
"safe fonts" instead of "save fonts".

### CODE REVIEW

**Comment by mxstbr** [comment]
I'm no longer merging anything into the `master` branch since version three is very far advanced! Thanks very much though for submitting this PR, it is very appreciated, and have a look at the `v3.0.0` branch!

**Comment by aried3r** [comment]
Ah, I didn't see that mentioned anywhere. Thanks for pointing it out!

**Comment by mxstbr** [comment]
It isn't actually mentioned anywhere. We should really add a notice to the master README that the `v3.0.0` branch exists and is a lot better... Do you maybe want to do that?

**Comment by aried3r** [comment]
If I can include the typo fix, sure ;)

**Comment by mxstbr** [comment]
Hah yeah definitely!

**Pull request closed without merging**
