### PR TITLE
Add new logs and styling #81

### PR DESCRIPTION
**Pull request by 7rulnik**
I encountered some problems with git. So, it's new pull request (lol).
Old request — https://github.com/mxstbr/react-boilerplate/pull/83

Preview:
https://monosnap.com/file/XsJtEYCF6w1kzLCDJAjfo4ElC21KXD
https://monosnap.com/file/GxvvVZrTq4Rx4U5S1iwmDfbfDFou1G

### CODE REVIEW

**Comment by mxstbr** [comment]
Yeah it's because I changed things in the server files, my bad, sorry about that. 

Looks amazing, thank you so much! Good work!

**Comment by mxstbr** [comment]
@7rulinik would you like to take a look at the logs from `npm run initProject` (which runs the `webpack/init` file) and the `npm run pagespeed` (which runs the `webpack/pagespeed` file) or should I do it?

**Comment by mxstbr** [comment]
@7rulnik would you like to update the logs from `npm run initProject` (which runs the `webpack/init` file) and `npm run pagespeed` (which runs the `webpack/pagespeed` file) or should I do it?

Really digging the styling you added, looks amazing!

**Comment by 7rulnik** [comment]
I can do it after thursday :+1:

**Comment by mxstbr** [comment]
Amazing mate, looking forward!

**Comment by 7rulnik** [comment]
@mxstbr sorry for delay.
I will do it today.

**Comment by mxstbr** [comment]
@7rulnik don't worry about it, looking forward!

**Pull request merged**
