### PR TITLE
add redux devtools

### PR DESCRIPTION
**Pull request by carloscuatin**
add redux devtools render in development 

### Development
image

### Production
image

### CODE REVIEW

**Comment by carloscuatin** [comment]
#197 solution issue

**Comment by knowbody** [comment]
lgtm!

**Comment by mxstbr** [comment]
Hey Carlos, thanks so much for the help, this is very appreciated!

This PR currently has the same problem as #173, which is that you only *hide* the DevTools in production.

screen shot 2016-03-03 at 12 50 07

This is a screenshot of a newly built bundle, fresh from your branch. As you can see, there's still references to the `DevTools` in there. That means that **the code for the DevTools is still included in the production bundle**. This is a no-go, as the code is unused and shouldn't be in the bundle!

Do you have any idea how to not include the code for the DevTools in the production bundle?

**Comment by carloscuatin** [comment]
use files different for compilation provider and store

**Comment by mxstbr** [comment]
Could you implement that @carloscuatin?

**Comment by carloscuatin** [comment]
@mxstbr  ok :+1:

**Comment by luandro** [comment]
I've been using redux devtools for a while. I found that using [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) is way easier to implement (a single line and no additional packages), and less obtrusive.

**Comment by carloscuatin** [comment]
@luandro yes exactly is another solution

**Comment by mxstbr** [comment]
That sounds much more reasonable, would you mind implementing that? :+1:

**Comment by mxstbr** [comment]
I'll close this issue because I can't see this being merged (thanks so much though @carloscuatin!), lets add the extension instead!

**Pull request closed without merging**
