### PR TITLE
Added node 7 support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
Will GitHub allow this tho?

**Comment by mxstbr** [comment]
Talked to @sedubois, he'll try doing this tomorrow 😉

**Comment by sedubois** [comment]
@amilajack appveyor failed with `node  x86 package not found` for node 7, did you see somewhere it's supposed to be available? I'll relaunch the build

**Comment by sedubois** [comment]
Same issue again: `node  x86 package not found`

**Comment by amilajack** [comment]
Its probably a travis ci cache? I'm 90% sure that travis uses nvm for node installations. But i know that nvm supports installing node 7. So maybe its a cache?

**Comment by sedubois** [comment]
Maybe, once again I don't know about those things, please go ahead if you know how to investigate 😊

**Comment by samit4me** [comment]
It looks like CI support has now been added, see #1197

**Pull request closed without merging**
