### PR TITLE
Remove history dependency

### PR DESCRIPTION
**Pull request by brandondurham**
It seems the project no longer uses the `history` dependency, so I’ve removed it.

### CODE REVIEW

**Comment by mxstbr** [comment]
The [preview](http://deploy-preview-879.react-boilerplate.netlify.com/) looks and works alright, that's good! I don't really see any reason we shouldn't merge this, but will leave it open for now to see if others want to chime in.

**Comment by mxstbr** [comment]
(by the way, your local committer is set to the @hoeflercomain account, so you won't be credited for this fix…)

**Comment by brandondurham** [comment]
Yeah… I realized this after the PR was created. I don’t mind if you don’t mind. :)

**Comment by gihrig** [comment]
While "`from 'history'`" does not appear anywhere in a project wide search, expressly importing it has created a problem which surfaced in examining `npm shrinkwrap` see #873.

`npm ERR! peer invalid: history@^1.12.1 || ^2.0.0, required by scroll-behavior@0.7.0`

While this is only one of several problems with `npm shrinkwrap` it demonstrates the problem well.

So, yeah, I vote for removal of `history` from `package.json`, let npm decide how to install the requested dependencies.

**Comment by mxstbr** [comment]
Awesome, let's :shipit: then! Can you merge it please @gihrig? Thanks!

**Comment by gihrig** [comment]
@brandondurham Please merge `dev` branch to bring this up to date and we'll land this!

@mxstbr Will do!

**Comment by gihrig** [comment]
@brandondurham I see there are several other commits included with this one. That may be just because it's out-of-date with the base branch, or maybe something else is wrong?

In any case, I'm "including" the removal of history in this week's dependency update, and closing this PR.

Thanks for bringing this issue, and helping to make this project awesome 🎉

**Pull request closed without merging**
