### PR TITLE
chore(generators): clean up generator templates

### PR DESCRIPTION
**Pull request by Dattaya**
Follow up to #1260

### CODE REVIEW

**Comment by Dattaya** [comment]
This is a trivial change, @gihrig, could you take a look at this?

**Comment by gihrig** [comment]
@Dattaya I just pulled your repo and

```
npm run clean
npm run generate component TestComp /w defaults
npm run generate container TestPage /w defaults
npm run generate route TestPage - /test
use TestComp on TestPage
npm start > localhost:3000/test
```
All works as expected.

But, the lint phase of 

```
npm test (expect test failures due to incomplete tests)
```

Produces a ton of errors, all matching this:
image

I don't see that this could be related to your change, I'm investigating further...

**Comment by Dattaya** [comment]
> I don't see that this could be related to your change, I'm investigating further...

It is not, but 106 errors is a bit too much 😱. I'll try to finish #1223 during the weekend which will prevent these stuff from happening ever again.

**Comment by gihrig** [comment]
I am currently unable to build a fresh `dev`. I think this PR should wait until that is fixed so it can be tested against a solid base.

**Comment by gihrig** [comment]
Problem discovered, see [1205 comment](https://github.com/mxstbr/react-boilerplate/pull/1205#issuecomment-265881061).

**Pull request merged**
