### PR TITLE
Added node_modules caching for appveyor ci

### PR DESCRIPTION
**Pull request by amilajack**
Since we'll have 4 CI builds running in parallel, thought some caching might speed things up

### CODE REVIEW

**Comment by sedubois** [comment]
Maybe adding an `npm prune` (or whatever the yarn equivalent is), to avoid bad surprises?

**Comment by amilajack** [comment]
If i remember correctly, `npm prune` strips out all unused deps?

**Comment by sedubois** [comment]
Yes, `npm prune` prunes all deps which are in node_modules but not referenced in package.json.

OTOH it seems like yarn intends to prune automatically, but there might be a [bug](https://github.com/yarnpkg/yarn/issues/696) currently. Maybe we could live with it for the time being, knowing the issue could fix itself "soon".

**Comment by amilajack** [comment]
Should this be added to `travis.yml` as well>

**Comment by sedubois** [comment]
I'm not familiar with the current CI setup. As I mentioned in previous comment, if test automation is done using `yarn` instead of `npm`, maybe we can forget about prune completely?

**Comment by amilajack** [comment]
I think we should use yarn when its more stable

**Comment by sedubois** [comment]
@amilajack any idea why coveralls got stuck on this branch and others?

**Comment by amilajack** [comment]
I was wondering the same. I'm not sure. I don't have any experience with it.

**Comment by sedubois** [comment]
@amilajack I have no handle on its configuration so can't do anything myself

**Comment by mxstbr** [comment]
This LGTM, thanks!

**Pull request merged**
