### PR TITLE
Remove webpack DedupePlugin

### PR DESCRIPTION
**Pull request by samit4me**
Wanting to remove the webpack DedupePlugin for the following reasons:

- sokra is wanting to remove it in this [webpack issue #3266](https://github.com/webpack/webpack/pull/3266)
- It resolves issue #1210 regarding `material-ui`

As a bonus it appears to have minimal impact on output file size (if any)!

### CODE REVIEW

**Comment by jontro** [comment]
Also it solves this issue I just encounterd https://github.com/webpack/webpack/issues/959

**Comment by samit4me** [comment]
UPDATE: DedupePlugin has now been removed from webpack!

**Comment by alanimgur** [comment]
Please do this! It took me hours to implement Material-UI and to track down bug #1210 👎

**Comment by Dattaya** [comment]
I can see that LGTM github hook is working in 1275, is it because of a new message?

**Comment by mxstbr** [comment]
LGTM

**Pull request merged**
