### PR TITLE
Update README, point users to the v3.0.0 branch

### PR DESCRIPTION
**Pull request by aried3r**
Hope the wording is ok? Could't help myself but to include the typo fixes. I can of course quickly remove them if you don't want them.

### CODE REVIEW

**Comment by mxstbr** [comment]
Let's not scare people off by first stating this isn't developed anymore, I reckon many just stop reading right there.

What about

"Version 3.0 is actively being developed on the [v3.0.0 branch], please check it out and leave feedback! (PR on `master` are not going to be merged)"

(The typo fixes are fine of course, thanks very much!)

**Comment by aried3r** [comment]
Ah, that's much better. Give me a second

**Comment by mxstbr** [comment]
Sorry, one small request before I merge, lets get rid of the heading – I don't think it's necessary. Thank you very much!

**Comment by aried3r** [comment]
Should be ok now.

**Comment by mxstbr** [comment]
Awesome, thank you very much!

**Pull request merged**
