### PR TITLE
Update Redux DevTools Extension's usage according to new API

### PR DESCRIPTION
**Pull request by zalmoxisus**
[`window.devToolsExtension` is being deprecated](https://github.com/zalmoxisus/redux-devtools-extension/issues/220) in favour of a more clear API. There's no need for `window.devToolsExtension.updateStore` workaround anymore, which invokes misconceptions like https://github.com/zalmoxisus/redux-devtools-extension/issues/231.

[Here](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83)'s a blog post with more details. Also [there's an npm package](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) to make things even easier.

### CODE REVIEW

**Comment by sedubois** [comment]
I changed the target to `dev`, could you switch to that branch?

**Comment by zalmoxisus** [comment]
@sedubois, thx for changing the base branch! If there are any actions required from my side here, let me know.

**Comment by sedubois** [comment]
Yes, I changed the _target_ branch to `dev`, but you need to change the _base_ yourself, AFAIK. Right now you're based on `master`.

**Comment by zalmoxisus** [comment]
@sedubois, I'm confused 😌
I changed the base branch of the fork, but don't see how it could affect the pr (unless I'll pull another one). Isn't changing the target branch enough? Wouldn't it be merged in `dev`? I didn't use this new feature before, so would like to know more about that.

**Comment by sedubois** [comment]
You have originally created your branch based on `react-boilerplate:master` instead of `react-boilerplate:dev`. To fix this, I see two methods (there are possibly others): either create a new branch based on `dev` and `git cherry-pick` your commit to there, or go to your current branch and `git rebase -i HEAD~8` and delete all the commits except your own, then `git push --force` to your branch. The first approach is probably better because I see that you've been doing this on your fork's master directly, which isn't ideal.

**Comment by zalmoxisus** [comment]
@sedubois, thanks for the detailed explanation. I made [another PR](https://github.com/mxstbr/react-boilerplate/pull/1129) based on `dev`. Sorry for the noise!

**Pull request closed without merging**
