### PR TITLE
ISSUE-732 - Fix default selector test template to pass

### PR DESCRIPTION
**Pull request by chaintan17**
https://github.com/mxstbr/react-boilerplate/issues/732

### CODE REVIEW

**Comment by gihrig** [comment]
What is the status of this? Work in progress? Working fix?

**Comment by chaintan17** [comment]
@gihrig it's my working solution.

I get your idea that error would remind programmer to include the test.
Anyway, it look the error i found is a mistake in coding.
I think we should fix this first, because newbie like me would take a lot of time try to figure it out what's went wrong during the test.

**Comment by chaintan17** [comment]
Update default generated unit test to throw error to user that he/she didn't specify test case yet.

image

**Comment by mxstbr** [comment]
This looks very reasonable, thanks so much @chaintan17! 🎉

**Pull request merged**
