### PR TITLE
Add AWS documentation to deployment.md

### PR DESCRIPTION
**Pull request by kelsonic**
Complete #1439 for AWS S3 bucket deployment.

### CODE REVIEW

**Comment by kelsonic** [comment]
@gihrig I added docs for AWS S3 bucket deployment and [deployed an example](http://react-redux-material-ui-boilerplate.s3-website-us-east-1.amazonaws.com/) using the steps described.

**Comment by kelsonic** [comment]
@gihrig What are you using to measure the speed? Happy to hear that! 🎉

**Comment by gihrig** [comment]
@kelsonic Just my subjective sense of speed 😁

**Comment by gihrig** [comment]
OK, so it's not really faster, but first load with empty cache in under 3 seconds, reload with cache under 1.5 seconds. Not bad...

image

image

image

**Pull request merged**
