### PR TITLE
Add image compression to webpack process

### PR DESCRIPTION
**Pull request by Ndpnt**
https://github.com/mxstbr/react-boilerplate/issues/489

### CODE REVIEW

**Comment by Ndpnt** [comment]
I open this PR too quickly, documentation is missing. I close it until I add related documentation

**Comment by mxstbr** [comment]
Awesome, thanks @Ndpnt!

**Comment by Ndpnt** [comment]
The way I add this feature, it optimizes images both in development and production mode.
@mxstbr do you think it is a good idea as it allows us to see how images are compressed during our development process and potentially adjust settings or do you think it could slowdown things and it's better to compress images only for production?

**Comment by mxstbr** [comment]
> do you think it is a good idea as it allows us to see how images are compressed during our development process and potentially adjust settings or do you think it could slowdown things and it's better to compress images only for production?

Hmm, good question actually, would you mind opening a new issue to discuss this?

**Comment by Ndpnt** [comment]
Yes, I going to do this :)

**Pull request closed without merging**
