### PR TITLE
Nitrous.io Quickstart button

### PR DESCRIPTION
**Pull request by yeouchien**
Added Nitrous Quickstart files so anyone can quickly spin up a free, cloud dev environment to start using this repo. Clicking the Quickstart button will automatically clone this repo and will install and configure any required packages.

### CODE REVIEW

**Comment by mxstbr** [comment]
We appreciate you taking the time to submit this PR, but I don't think we'll be merging this. `react-boilerplate` isn't meant to be looked at, it's meant to be used for projects. :blush:

**Comment by jbinto** [comment]
>  react-boilerplate isn't meant to be looked at, it's meant to be used for projects. 

@mxstbr I don't understand? Nitrous.io is a cloud based IDE, which definitely qualifies as "using for projects".

**Comment by aeman1** [comment]
O
Open bowl

**Comment by mxstbr** [comment]
Oh, my bad, I misunderstood Nitrous.io's purpose from simply looking at the website @jbinto!

I'd love for react-boilerplate to be on there, but I'm still not sure if we want to advertise it hugely in the README. What do you think?

**Comment by yeouchien** [comment]
Hi @mxstbr, I can replace that chunk of text in `README.md` with:
`If you don’t want to install anything locally, you can setup the project in one click on Nitrous using this <a href="https://www.nitrous.io/quickstart">link</a>.`.
What do you think?

**Pull request closed without merging**
