### PR TITLE
Add babel-watch and es6 support on the server

### PR DESCRIPTION
**Pull request by harijoe**
This PR proposes the addition of `[babel-watch](https://github.com/kmagiera/babel-watch)`, which brings two improvements:
- The tool reloads very quickly the server on every file change, (this is a necessary condition to allow people to extend the express server and make an API out of it as suggested in `index.js`, today only used to handle HMR)
- The tool allows the usage of ES6 in the server by transpiling the code on the fly

Notice: `babel-watch` should not be used in production. The server should be built with babel, shipped and then run with only just node. This has not been implemented and suggestions are very welcome to address it :)

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks like a solid start, I'm not yet 100% sure we really want to introduce another build step.

*Would fix #349*

**Comment by harijoe** [comment]
I think this build step is necessary to grant auto restart of the server. May you try it and notice it is actually very fast. 

What would be the downside of adding such another build step ?

**Comment by mxstbr** [comment]
No, I mean another build step when compiling for production, I don't mind the development. :grin:

**Comment by harijoe** [comment]
Okay, I understand. What would be the next step to see this PR merged ? Other reviews ?

**Comment by mxstbr** [comment]
Yeah, I'm not really a server person so I have no idea if this is reasonable or not to be honest.

*Let's ping some that chimed into the initial Express.js discussion in #175 and the related PRs: @grabbou @amorino @oliverturner*

**Comment by oliverturner** [comment]
My practice has been to run nodemon watching for file changes in `/app` and `/server` and restarting the server accordingly.

Since the client state is unaffected this has no impact on the time taken to recompile via babel: it's effectively a background operation. It's simple, robust and doesn't add further complexity to our babel config.

**Comment by oliverturner** [comment]
No slight intended on your approach btw @harijoe: this is simply my approach and rationale

**Comment by oliverturner** [comment]
A big difference is that typically I'm not running webpack as server middleware though... `babel-watch` may be a better fit for this environment. Wd love to hear from @grabbou on his perspective...

**Comment by grabbou** [comment]
Hey, great work here! I am not using Babel on Node.js side of things recently, mainly because I am running on 6.x that has a decent support for almost all features.

As @oliverturner proposed, I am also using `nodemon` as an opt-in to reload app on code changes. As far as I am aware of kmagiera module, it's a more performant way to reload server when you have to recompile it with babel. So it seems like a good solution if there's transpilation going on on the server side of things.

Having said so, I am not really sure if ES6/beyond are needed on the server side here as an extra step given that the scope of it is rather small. But I can see some use-cases for that, esp. when the app grows a bit.

**Comment by harijoe** [comment]
@grabbou As this project is meant to be a strong base for new projects, I think it makes sense to enable ES6 on server side. I guess many users will want to enrich the provided server at some point. I find it cool to provide them the right tools to do so.

**Comment by mnickkk** [comment]
This project is definitely missing this feature, however I don't think that this PR resolves this correctly. 
Backend changes cause whole frontend rebuild (and remember that initial build takes time). Should probably spawn two separable tasks (maybe use https://github.com/kimmobrunfeldt/concurrently I've seen this approach in one boilerplate for sure)?
These two packages might be useful:
https://github.com/jlongster/monkey-hot-loader
https://github.com/ericclemmons/webpack-hot-server-example

**Comment by jolyonruss** [comment]
If it seems this PR is too prescriptive, maybe it should be closed and the docs updated to show usage of Nodemon, Superviser or Forever?

**Comment by mxstbr** [comment]
Since there is quite a bit of discussion left to do before we can merge something like this and this PR is quite outdated I'll close this for now. Thank you @harijoe for providing this great reference implementation, that's definitely much appreciated! Sorry we didn't merge it.

**Comment by ithinco** [comment]
This feature is fine to merge, though I'm looking for a method to add this feature as a configure file maybe "webpack.server.babel.js".

**Comment by rclai** [comment]
Has there been any new developments on this?

**Comment by harijoe** [comment]
I think it's better to wait for #1236 to be merged first. This branch can still be used as an implementation reference for anyone not willing to wait though.

**Comment by rclai** [comment]
I don't know if anyone is running into this but why is it that code like this on the server:

```
router.get('/test', async (req, res) => {
  res.json({ hello: 'world' });
});
```

Runs fine in dev mode (`npm start`) but then it will give me an error in production mode (`npm run start:prod`) _even_ though I changed this line from `package.json` from this:

`"start:prod": "cross-env NODE_ENV=production node server`

to this

`"start:prod": "cross-env NODE_ENV=production babel-watch server --presets es2015 react stage-0 --plugins transform-runtime",`

**Comment by Kr1an** [comment]
@rclai, or anyone else who has this problem when node code works in dev(with different features of es6/beyond - import/export/async/await/...) and does not work with the same stack in production:
You need to understand that in development its normal to use such tools as bable-watch bable-node, but in production these tools are't effective enough. So in production, code should be native. To make it native, you should do same process that you do with front-end code - transpile it to version thats supported by node6+(current).
If your server-side code locates in **server** directory, run script `babel server --out-dir dist --presets es2016` It will compile all unsupported features and create new version in **dist** folder. and then you just run `node dist/index.js`.

Actually, this approach has its cons: new code is less suitable for debugging because sometimes easy to read new feature transforms to horrible staff, but if you need it only for production, than its normal, i suppose.

In case of react-boilerplate, you just need to change start:production script with the steps from above. I think it does not brake any relative connections because transpiled folder locates on same level.
Good luck with it.

**Comment by rclai** [comment]
I can't remember anymore why I was using babel-watch in production. It kind of baffles me now that I think about it, but I'm not doing that anymore. I decided to make the server code run on a separate project.

**Pull request closed without merging**
