### PR TITLE
Code coverage reports using isparta

### LINKED ISSUE #148: Code coverage reports using isparta

### PR DESCRIPTION
**Pull request by jbinto**
Partially fixes #148.

**Usage:**

Run `npm run test`.

Coverage report will be in `./coverage/html/index.html`.

LCOV report (for services like https://coveralls.io/) is in `./coverage/lcov/lcov.info`.

**Changes:**

* Add `coverage` to `.eslintignore` and `.gitignore`.

* `test-bundler.js`: Include all code files (except `app.js`), not just tests. Otherwise, isparta/istanbul will only report on the code files it executed as a result of a test.

* `test-bundler.js`: Import `babel-polyfill` for generator support in the browser.

* `webpack.test.babel.js`: 

  * Add `isparta` preloader.
  * Use `null-loader` for images. (Since we're including more untested components in the test now, these errors start cropping up.)
  * Copy-paste `modulesDirectories` from base config. 

**Major caveat:**

The redux-saga code depends on generators, and the output from isparta for the saga files is totally broken. I'm using `babel-polyfill`, and from what I could tell `facebook/regenerator` doesn't have source map support, so this may not be fixable right now.

### CODE REVIEW

**Comment by mxstbr** [comment]
Thanks so much Jesse, this is looking great!

Do you think this is worth including even though Sagas horrendously mess it up?

**Comment by mxstbr** [comment]
I get an error when trying to run `npm run test`, it's saying

> "Module not found: Error: Cannot resolve 'file' or 'directory' sinon/pkg/sinon"

Any ideas what's happening here?

**Comment by jbinto** [comment]
Hmm, did you `npm install`? Works on my machine (and Travis).

If it's still not working can you paste the full output of `npm run test`?

**Comment by jbinto** [comment]
> Do you think this is worth including even though Sagas horrendously mess it up?

I'm not sure to be honest, since I haven't spent much time looking at `redux-saga`. I'm surprised such a core feature of ES6 (generators) doesn't have source map support. 

FWIW, code coverage still "works" on files with generators, but the report is broken (it displays the original source file, but performs coverage analysis on the generated code from `regenerator`).

**Comment by mxstbr** [comment]
@jbinto I did, this is the full output:

```sh
ERROR in ./webpack/test-bundler.js
Module not found: Error: Cannot resolve module 'sinon/pkg/sinon' in /path/react-boilerplate/webpack
 @ ./webpack/test-bundler.js 10:13-29
09 02 2016 21:20:48.731:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
09 02 2016 21:20:48.754:INFO [launcher]: Starting browser Chrome
09 02 2016 21:20:52.658:INFO [Chrome 48.0.2564 (Mac OS X 10.11.2)]: Connected on socket /#YAclL-xneYi13BL7AAAA with id 5837231
Chrome 48.0.2564 (Mac OS X 10.11.2) ERROR
  Uncaught Error: Cannot find module "sinon"
  at /path/react-boilerplate/webpack/test-bundler.js:56 <- null:0:0
```

**Comment by jbinto** [comment]
Ah, you're running npm2. Ran into this on Travis with one of my projects. npm3 gets sinon via enzyme, but npm2 needs it to be explicitly listed in package.json.

I'll fix this and also add Node 4 back to `.travis.yml`, since it's how I caught it in my project. (My previous assumption about only needing one Node version is clearly wrong.)

**Comment by mxstbr** [comment]
Nope, running npm3:

```sh
$ npm -v
3.3.9
```

but adding Sinon to the `package.json` still sounds like a reasonable idea and might fix the issue :+1:

**Comment by mxstbr** [comment]
`npm install sinon` fixed the problem for me, it now works perfectly! I looked into it but couldn't figure out how to integrate coveralls.io into the ci process - could you look into that?

**Comment by jbinto** [comment]
Rebased and fixed `package.json`. This should work now.

**Comment by jbinto** [comment]
> I looked into it but couldn't figure out how to integrate coveralls.io into the ci process - could you look into that?

It's pretty straightforward, but it requires you (project owner) to do some travis stuff. I can PR the rest.

[ ] sign up for coveralls.io account, acquire token
[ ] add coveralls token to your Travis environment variables

--

[ ] install `coveralls` npm package 
[ ] add an npm script to submit coverage data to coveralls 
[ ] add a post-deploy hook to travis.yml to run that npm script
[ ] add a badge in README

**Comment by mxstbr** [comment]
Alright, let me check out and merge this PR and then lets get to coveralls.io, see #168!

**Comment by mxstbr** [comment]
Perfect, this works now – thanks so much for your work Jesse!

**Comment by mxstbr** [comment]
We should probably include that in the docs in `commands.md` where we explain `npm run test`!

**Comment by chungchiehlun** [comment]
Hello, @mxstbr  @jbinto  :+1: 
Good coverage test PR but I could not figure out why we included all '.js' files under 'app' but 'app.js'.
Why not merely including all js file ?

```js
// Include all .js files under `app`, except app.js
// This is for isparta code coverage
const context = require.context('../../app', true, /^((?!app).)*\.js$/);
context.keys().forEach(context);
```

**Comment by mxstbr** [comment]
Because we cannot test anything in `app.js` since it's just setup code, so checking the code coverage of that is kind of moot. :+1:

**Comment by chungchiehlun** [comment]
I see what you mean. Thanks

**Pull request merged**
