### PR TITLE
chore(deps): update deps roll-up Oct-29-2016

### PR DESCRIPTION
**Pull request by gihrig**
-- Test script --
npm run setup && npm start
Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate component TestComp /w defaults
npm run generate container TestPage /w defaults
npm run generate route TestPage - /test
use TestComp on TestPage
npm start > localhost:3000/test
npm test (expect test failures due to incomplete tests)
git add .
git commit -m "testing..."

 Node 6.6.0
npm 3.10.8
Mac OS 10.11.6
Chrome 54.0.2840.71 (64-bit)

chore(deps): update deps roll-up Oct-29-2016
 react-router                2.8.1  →   3.0.0 
 react-router-scroll         0.3.2  →   0.3.3 
 babel-cli                  6.16.0  →  6.18.0 
 babel-core                 6.17.0  →  6.18.0 
 babel-eslint                7.0.0  →   7.1.0 
 babel-loader                6.2.5  →   6.2.7 
 babel-plugin-istanbul       2.0.1  →   2.0.3 
 enzyme                      2.4.1  →   2.5.1 
 eslint                      3.8.0  →   3.9.0 
 eslint-config-airbnb-base   8.0.0  →   9.0.0 
 eslint-plugin-redux-saga    0.1.4  →   0.1.5 
 html-webpack-plugin        2.22.0  →  2.24.0 
 lint-staged                 3.1.0  →   3.2.0 
 postcss-loader             0.13.0  →   1.1.0 
 shelljs                     0.7.4  →   0.7.5 
 stylelint                   7.4.2  →   7.5.0 
 stylelint-config-standard  13.0.2  →  14.0.0 
 webpack-hot-middleware     2.13.0  →  2.13.1 

Errors:
image-webpack-loader        2.0.0  →   3.0.0 <--- Rolled back
see: https://github.com/tcoopman/image-webpack-loader/issues/51

### CODE REVIEW

**Comment by gihrig** [comment]
@mxstbr Do you know what's up with Coveralls? It completes with a 99% score but blocks the merge?

If you can fix this, or bypass it, please do.

**Comment by avdeev** [comment]
react-router-redux is broken

**Comment by gihrig** [comment]
Please provide details

**Comment by avdeev** [comment]
@gihrig LOCATION_CHANGE action doesnt dispatch on react-router 3.0.0

**Comment by gihrig** [comment]
@avdeev Can you provide details to reproduce?

Here's what I see:

1. Clone/build example app
2. `npm start`
3. Open app in Chrome
4. Open Redux Devtools in Chrome Devtools
5. Click _Features_ link example project

I get LOCATION_CHANGE:

image

Are you seeing something different?
Am I missing something?

**Comment by avdeev** [comment]
@gihrig in my app this upgrade broke router-redux
image

maybe it only happens in my application

**Comment by gihrig** [comment]
@avdeev Have you tried in a fresh clone of react-boilerplate?

**Comment by avdeev** [comment]
@mxstbr No, i started from 3.1.0 and repeated your commits in dev
Perhaps I missed something

**Pull request merged**
