### PR TITLE
HOTFIX fix airbnb dependencies

### PR DESCRIPTION
**Pull request by chaintng**
https://github.com/airbnb/javascript/issues/1088

### CODE REVIEW

**Comment by chaintng** [comment]
@mxstbr @gihrig need hotfix here :)

**Comment by toddsby** [comment]
npm run build fails without this hotfix! +1

**Comment by mxstbr** [comment]
Merging, releasing new version asap! Thanks @chaintng!

**Comment by gihrig** [comment]
This was, apparently, caused by a breaking change in a transient dependency.

_eslint-config-airbnb_ lists _eslint-config-airbnb-base_ as a [dependency](https://www.npmjs.com/package/eslint-config-airbnb). So ~base@latest gets loaded automatically by npm install. ~base 7.2.1 seems to be the cause of the error:

`Configuration for rule "eol-last" is invalid: Value "always" must be an enum value`

As covered in [airbnb/javascript#1088](https://github.com/airbnb/javascript/issues/1088). Thanks @chaintng for getting to the bottom of that!

**Pull request merged**
