### PR TITLE
Explain how to add a new PostCSS plugin

### PR DESCRIPTION
**Pull request by kachkaev**
See https://github.com/mxstbr/react-boilerplate/pull/227#issuecomment-236163902

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview failed.

Built with commit 4e5fe329ac0482c7030455f1afee102f838185f5

https://app.netlify.com/sites/react-boilerplate/deploys/57bf15aad6865d145dc75e12

**Comment by mxstbr** [comment]
Awesome, thanks!

**Comment by kachkaev** [comment]
@mxstbr would you like me to fix or add anything before merging?

**Comment by mxstbr** [comment]
Ah sorry, Github wouldn't let me merge this PR from mobile and then I forgot to do it from my laptop. Thanks for reminding me, this is great!

**Comment by mxstbr** [comment]
Argg now I merged into `master`, I forgot to check that!

Please submit future PRs against the `dev` branch so I can't mess up 😊 Thanks!

**Pull request merged**
