### PR TITLE
OfflinePlugin fixes and improvments

### PR DESCRIPTION
**Pull request by NekR**
* Remove `relativePaths: true` because it's `true` by default
* Add `safeToUseOptionalCaches: true` to remove warnings about additional caches
* Make AppCache cache both sections: `main` and `additional`

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, thanks! Two small linting errors:

```Sh
react-boilerplate\internals\webpack\webpack.prod.babel.js
  101:39  error  Missing trailing comma  comma-dangle
  102:8   error  Missing trailing comma  comma-dangle
 
✖ 2 problems (2 errors, 0 warnings)
```

**Comment by NekR** [comment]
Yeah, sorry, forgot to run tests. I'll fix it once get back to computer.

**Comment by mxstbr** [comment]
Awesome, thanks @NekR!

**Comment by ralomucho** [comment]
@mxstbr are you sure you wanted to merge ino `mxstbr:v3.0.0` ?

**Comment by mxstbr** [comment]
Oooh no, my bad. Would you mind resubmitting this PR against the master branch?

**Comment by NekR** [comment]
Wow. Have you merged v3 to master while I was doing this PR? I'll resubmit
it, no problem.

**Comment by mxstbr** [comment]
We released v3 a week ago! :tada:

**Pull request merged**
