### PR TITLE
added shallow compare

### PR DESCRIPTION
**Pull request by eddiewang**
Replaced react pure render with shallow compare.

shallowCompare is a helper function to achieve the same functionality as PureRenderMixin while using ES6 classes with React.

### CODE REVIEW

**Comment by eddiewang** [comment]
#503

**Comment by eddiewang** [comment]
@mxstbr not sure why appveyor is failing.

**Comment by mxstbr** [comment]
No idea either, seems to be a network connectivity issue on AppVeyor. I've restarted the build there, will review and merge this asap! Thanks! :+1:

**Comment by mxstbr** [comment]
Awesome, thanks @eddiwang!

**Pull request merged**
