### PR TITLE
v3.4.0

### PR DESCRIPTION
**Pull request by mxstbr**
It's time for another release!

Thanks so much for contributing everybody, please test this branch thoroughly and let me know if everything works as expected!

@gihrig @Dattaya et al is there any PRs we need to land before shipping this?

# Changelog

## Main

- **Switch to Jest for testing**, massive thanks to @dmitriiabramov 
- **Update to webpack 2 RC** (includes switching from `System.import` to `import()`), thanks to @Dattaya 
- **Add progress bar while loading code splitted routes**, thanks to @KarandikarMihir 
- **Add the "Hitchhikers Guide to `react-boilerplate` to the docs**, massive thanks to @KarandikarMihir 
- Update all dependencies, as always huge thanks to @gihrig, our master of dependencies
- Enable `import/first` eslint rule and rewrite all imports, huge thanks to @KarandikarMihir 
- Add Node v7 support and deprecate v4 support, thanks to @samit4me @MariusRumpf
- Prevent i18n language duplication, thanks to @harijoe 
- Add the webpack circular dependency plugin to avoid hard to debug errors, thanks to @haikyuu
- Refactor all selectors and generators with new naming convention, thanks to @Dattaya 
- Update generator templates, thanks to @Virsaviya @jeremyadavis 
- Add support for the `--host` parameter when running `npm start`, thanks to @ifedotov 
- Showcase reselects `createStructuredSelector` in the example, thanks to @Dattaya 
- Exclude test files from coverage report, thanks to @samit4me 
- Lint the templates for the generators, thanks to @Dattaya 
- Huge improvement to DX testing a freshly cleaned project, thanks to @outdooricon 

## Other Updates

- **Remove the webpack DedupePlugin** as it leads to errors in production and is now included by default, thanks to @samit4me 
- Remove the `npm run pagespeed` command and all related dependencies and files, thanks to @mkhazov 
- Trigger a full page reload when HMR fails, thanks @kachkaev 
- Don't import all of lodash, thanks to @jwinn 
- Improve `.editconfig`, thanks to @avdeev
- Improve the example components, thanks to @tomazy
- Fix `npm run clean` not working as expected, thanks to @adjnor 
- Fix the i18n button not updating with new state, thanks to @adjnor
- Fix console error when changing language, thanks to @samit4me 
- Fix default polyfill language, thanks to @web2style
- Fix language generation, thanks to @chaintng 
- Switch to new webpack query syntax, thanks to @shrynx
- Add an Introductory document to help people get started, thanks to @KarandikarMihir 
- Add security configuration recommendations for Nginx (`.nginx.conf`), thanks to @supergicko
- Add and fix lots to stuff in the documentation, thanks to @pavlin-policar, @samit4me @outdooricon @PierrickGT @nndung179 @outdooricon @kelsonic @jimmyheaddon 
- A wide variety of small fixes, thanks to @Dattaya @gihrig @outdooricon 

# News

Welcome @KarandikarMihir to the team! Karandikar has been all over the repo, providing fixes and features. Happy to have him on board to make `react-boilerplate` even better!

Special thanks as always to @gihrig for diligently testing everything and keeping our dependencies up to date!

Also, huge props to @samit4me and @Dattaya for being everywhere and fixing so many issues and of course to @KarandikarMihir for all his hard work.

If you want to help us make react-boilerplate great, please use the `dev` branch, test all the things and report all the bugs!

# Supporters

This release was made possible by [Fullstack React](https://www.fullstackreact.com/) and [Serverless](http://serverless.com)! _Want to support us too? [Click here!](http://opencollective.com/react-boilerplate)_

### CODE REVIEW

**Comment by gihrig** [comment]
@mxstbr I would like to see included 3.4.0

- [ ] Recognition of @KarandikarMihir for #1275 
- [ ] #865 - not just worked around, but fixed
- [ ] #1231 'generate container' produces unnecessary return
- [ ] #1232 - Saga effects should be yielded
- [ ] Maybe even #760 'rework setup UX' I've updated that issue, remove my assignment and added a 'PR Welcome'.

I would love to do the above personally, but sadly I've gone way over my RBP time budget already 😭

**Comment by kopax** [comment]
Thanks for all that. I would like to see the loading progress bar. Because it's ux requirement.

**Comment by mxstbr** [comment]
Good calls @gihrig, let's fix those remaining issues!

Not too fussed about #760, I really want to get this out, though that's definitely on the soon-to-be-fixed list.

I don't know about the test coverage, how much are we missing?

**Comment by gihrig** [comment]
>  test coverage, how much are we missing?

Everything not shown is strictly :100:

image
image
image
image
image

**Comment by samit4me** [comment]
I've only just started testing this (sorry had a busy weekend) and I've run into an issue on macOS.

Steps to replicate:

1. `git clone https://github.com/mxstbr/react-boilerplate.git`
1. `cd react-boilerplate`
1. `npm run setup` OR `npm i`
1. `npm start`
```
webpack built 79e8758d269f19c6258b in 4441ms

ERROR in ./app/components/Header/banner.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/sam/fresh/react-boilerplate/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/sam/fresh/react-boilerplate/node_modules/execa/index.js:170:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./app/components/Header/index.js 47:0-34
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main
Child html-webpack-plugin for "index.html":
```

This is not happening on Windows, so it might be just me! Can anyone else replicate?

**Comment by gihrig** [comment]
Hi @samit4me, Did you test `dev` latest or `3.4`? There are still fixes coming in on dev that I am anticipating will get merged into 3.4 branch.

I'm on OS X 10.11.6

In any case, I:
fetched latest `dev`
deleted `node_modules`
`npm i` (I normally use yarn these days)
`npm start` No errors, example app loaded in Chrome no problem.

Can you try,
delete node_modules
`npm cache clean`
`npm i` or better `yarn`

**Comment by samit4me** [comment]
Hi @gihrig, I've tested both `dev` and `3.4` branches and got the same issue.

I'm running macOS Sierrra 10.12.1

Below are some additional steps I've taken.

Using npm:
1. Uninstalled `yarn`
1. Deleted `node_modules`
1. Checked out `dev` branch
1. `npm cache clean`
1. `npm i`
1. During the install I saw the following error:
```
> mozjpeg@4.1.1 postinstall /Users/sam/fresh/react-boilerplate/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/sam/fresh/react-boilerplate/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/sam/fresh/react-boilerplate/node_modules/mozjpeg/vendor" --bindir="/Users/sam/fresh/react-boilerplate/node_modules/mozjpeg/vendor" --libdir="/Users/sam/fresh/react-boilerplate/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

> optipng-bin@3.1.2 postinstall /Users/sam/fresh/react-boilerplate/node_modules/optipng-bin
> node lib/install.js
```

Using yarn:
1. `brew install yarn` installed v0.17.10
1. Deleted `node_modules`
1. Checked out `dev` branch
1. `yarn` completed without error
1. `npm start`
1. Just after the build I got the same error as mentioned previously.

Might be related to macOS I'm not sure, but I'm about to go out for dinner, so don't have a chance to look into it right now, but there appears to be an open issue with `image-webpack-loader` https://github.com/tcoopman/image-webpack-loader/issues/49.

**Comment by samit4me** [comment]
As this will be the first release with Jest, it might also be good to include #1334 as it makes the test coverage look a little cleaner.

**Comment by nndung179** [comment]
In macOS Sierra 10.12. Everything works well.

**Comment by samit4me** [comment]
Thanks for testing @nndung179. It definitely looks like `mozjpeg`, used by `image-webpack-loader`,  has some environmental dependencies, which I must be missing. It certainly appears to be a common issue tho.

Out of interest what versions of the following do you have:
- Xcode, I've got ***v8.1 (8B62)***
- `nasm -v`, I've got  ***0.98.40***

If I downgrade `image-webpack-loader` from `3.0.0` to `2.0.0` it works, which was updated in [this commit](https://github.com/mxstbr/react-boilerplate/commit/33485f41053caa6e90b9cbede8b51c168b38bda4). It appears `image-webpack-loader` switched from [jpegtran to mozjpeg](https://github.com/tcoopman/image-webpack-loader/commit/0cad7983fdae77f5f532a2725a2d997e24949824#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by mxstbr** [comment]
It appears like fixing this at `2.0.0` is actually the recommended solution?

> Is it enough for you if we put a warning in the readme that users of OSX 10.10 should install an older version?

Let's just do that?

**Comment by gihrig** [comment]
> Is it enough for you if we put a warning in the readme that users of OSX 10.10 should install an older version?

I would not object (too much) to holding at `image-webpack-loader@2.0.0` as long as I have a reasonable test to confirm when the hold can be released. I'm talking from an update dependencies perspective here.

On the other hand, having an up to date 'known issues' (`gotchas.md`) is a really good idea.

**Comment by gihrig** [comment]
> Out of interest what versions of the following do you have:
> 
> Xcode, I've got v8.1 (8B62)
> nasm -v, I've got 0.98.40
> 

OS X: 10.11.6
Xcode: 8.1 (8B62)
nasm: 0.98.40

I just built `dev` 4eff7a3b4c733e224166d48de0c0aa11e9cc8e4f  with 
`rem -rf node_modules`
'yarn' 
`npm start` - load home page
`npm start:production` - load home page
no issues.

> It certainly appears to be a common issue tho.

@samit4me I would like to get to the bottom of this before pinning `image-webpack-loader@2.0.0` Can you open a separate issue to track this please.

**Comment by zamrq** [comment]
Running on Ubuntu 14
Fetch -b 3.4
- yarn setup
- yarn run clean
- yarn start

GIt error
```javascript
WARNING in ./app/containers/LanguageProvider/index.js
53:37 export 'selectLocale' was not found in './selectors'
Child html-webpack-plugin for "index.html":
```

**Comment by samit4me** [comment]
@gihrig that sounds good, created #1335 to further investigate the `mozjpeg` issue.

@zamrq thanks for reporting that. It looks like it was changed a few days ago, see [this commit](https://github.com/mxstbr/react-boilerplate/commit/50fef95d9f2e589385174250e2855fbbdd6907fb#diff-f49fd4d84aea666bde1f391d3e0ff9ca). Can you please pull the latest `dev` and let us know how you go?

**Comment by andykenward** [comment]
I found that i had to install `libpng` to solve the issue with `image-webpack-loader` `3.0.0` on macOS `10.12.1`.

If you have brew
`brew install libpng`

**Comment by zamrq** [comment]
@samit4me 
Work after laters pull
https://github.com/mxstbr/react-boilerplate/pull/1322#issuecomment-266310801

**Comment by outdooricon** [comment]
Is #1206 the only thing holding this release back then?

**Comment by KarandikarMihir** [comment]
I feel like I'm pushing it. But can we ship progress bar with 3.4.0?

**Comment by outdooricon** [comment]
Imho, the community really needs this move to jest and the dep updates. Would it be possible to have the progress bar be included in a .1 release maybe?

**Comment by gihrig** [comment]
@outdooricon 
> Is #1206 the only thing holding this release back then?

Yes, I think #1206 Document Jest (replacing Mocha and Karma) is really the only critical outstanding issue. We need someone to take on this docs project.

#1008 (progress bar) and #1366 (beginner's guide) are ready to merge as far as I can see, they're just waiting for a more recent approval from another collaborator.

**Comment by mxstbr** [comment]
@KarandikarMihir getting errors when running the example app and changing pages:

```JS
setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the AppWithProgressBar component.
```

Any ideas what's going on here?

**Comment by KarandikarMihir** [comment]
@mxstbr I'm not able to reproduce this.. Looks fine on my machine. :confused: 

screenshot from 2016-12-26 16 45 37

**Comment by KarandikarMihir** [comment]
@mxstbr I'm not able to reproduce this :confused: 

Local:
screenshot from 2016-12-26 16 45 37

Deploy preview:
screenshot from 2016-12-26 16 50 40

**Comment by gihrig** [comment]
Works for me! 😄 

@mxstbr I would suggest delete `node_modules` and `yarn`.
I updated `react-addons-test-utils`, that just fixes the build failure.

**Comment by outdooricon** [comment]
@gihrig Thank you for the clarification!

I've now got #1390 up as a fix for #1206, so :crossed_fingers: that this will finish out the release requirements.

**Comment by outdooricon** [comment]
Unfortunately, I do believe that I have found a regression with ngrok on 3.4... see #1398

**Comment by outdooricon** [comment]
I have a proposed fix now in #1399

**Comment by KarandikarMihir** [comment]
Can't wait for the release 😅

**Comment by mxstbr** [comment]
Deploy preview failed.

Built with commit dbdce8b935a73cbd890501899405c5bc73f56a78

https://app.netlify.com/sites/react-boilerplate/deploys/58699f6dd6865d3f6019b2a6

**Comment by gihrig** [comment]
@mxstbr Let's ship this thing!

I think all that is needed is:

[x] Update Changelog text, above
[x] Update Changelog.md
[x] Update versions in `package.json` and `internals/config.js`
[ ] Merge #1381 docs(servers): update server conf files for offline-first per #645
[ ] Merge #1393 feature(nginx): integrating mozilla's nginx secure tls configuration
[ ] Merge #1401 docs(toc): include link to new intro document
[ ] Merge `dev` into `3.4`
[ ] Merge `3.4` into `dev`

Ship! 😄

**Comment by mxstbr** [comment]
> If some minor things aren't ready, we can ship them as 3.4.1, etc, right? So I propose to release 3.4 right now.

In an effort to get this release out let's ship it as is. Will wait for CI, update the CHANGELOG and then we should be ready to go!

**Comment by outdooricon** [comment]
Just a heads up, in https://github.com/mxstbr/react-boilerplate/commit/b84f16e5c378d7817f343da482f4ce0a73954db7 the changelog was updated as if #1414 made it in, but it never received the actual final merge.

**Comment by kopax** [comment]
```ruby
Initialising new repository ✓
Done!
> react-boilerplate@3.4.0 postsetup /workspace/module.kopaxgroup.com/styled-components/bootstrap-styled-jest
> npm run build:dll


> react-boilerplate@3.4.0 build:dll /workspace/module.kopaxgroup.com/styled-components/bootstrap-styled-jest
> node ./internals/scripts/dependencies.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/workspace/module.kopaxgroup.com/styled-components/bootstrap-styled-jest/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

```json
 npm version
{ 'react-boilerplate': '3.4.0',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.2.0',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.43',
  zlib: '1.2.8' }

```

**Comment by gihrig** [comment]
@kopax I'm building the 3.4 branch with the command `yarn` (alias for `yarn install`) and having no problems.

OS X 10.11.6
Yarn 0.18.1

We've seen problems lately due to transient dependency issues. I would suggest you try building with `yarn`

Several differences here that may or may not be significant.
```bash
$npm version
{ 'react-boilerplate': '3.4.0',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```

**Comment by Dattaya** [comment]
@kopax, I wasn't able to reproduce on (I used `npm` too):
- Branch: 3.4
- Windows [Version 10.0.14393]
- Node: 5.12.0, 6.6.0, 7.4.0

**Comment by kopax** [comment]
I add to remove some of my workspace because of the space.

When I try to import 3.3.3 component into 3.4 build, I have this failing now : 


```ruby
ERROR in ./src/components/ContainerFluid/index.js
Module parse failed: /workspace/styled-components/bootstrap-styled-jest/node_modules/babel-loader/lib/index.js!/workspace/styled-components/bootstrap-styled-jest/src/components/ContainerFluid/index.js Unexpected token (10:19)
You may need an appropriate loader to handle this file type.
| class ContainerFluid extends React.Component {    // eslint-disable-line react/prefer-stateless-function
| 
|   static propTypes = {
|     className: PropTypes.string,
|     children: PropTypes.node.isRequired,
 @ ./src/index.js 139:0-72
 @ multi main

ERROR in main.8137cd7b4c48077bd824.js from UglifyJs
SyntaxError: Unexpected character '`' [main.8137cd7b4c48077bd824.js:12845,90]


```

What did you change in this way ?

**Comment by outdooricon** [comment]
I had targeted #1414 into dev, so we'll want another dev sync before merging out if we want to pick it up

**Comment by kopax** [comment]
Did anyone of you succeed to mock require.context in Jest ?

This for example doesn't work in jest : 

```jsx
const req = require.context('.', true, /\.js$/);
```

**Comment by Dattaya** [comment]
More good news from `webpack`, info from their release notes:

> If no critial bugs are discovered, we release 2.2.0 in < 10 days.

**Comment by kopax** [comment]
I have found another 3.4 bug.
The new mock of `document` produce a bug in my sagas test.

This is due to a ` browserHistory.push(location);` in my saga

https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living//helpers/document-base-url.js#L42

The url is always parsed as 'failure', this is a bit weird.
And I haven't found a way to jump from a yield to another using generator.next() in my test.

**Comment by gihrig** [comment]
I'm testing as described in #1252 ...

**Comment by gihrig** [comment]
Does Changelog need updating, or have we covered everything?

**Comment by gihrig** [comment]
Some additional issues that I would like to be included in 3.4.

#1381 docs(servers): update server conf files for offline-first per #645
#1347 remove duplicate configuration code?
#1449 @mxstbr's professional writer touch in the intro doc.

**Comment by mxstbr** [comment]
Will test everything and go through the CHANGELOG once more to make sure we got all the things. @jwinn would you mind testing this release on Windows?

**Comment by jwinn** [comment]
```
git clone -b 3.4 --depth=1 https://github.com/mxstbr/react-boilerplate.git react-boilerplate
cd react-boilerplate
git checkout %git_branch%
npm run setup
npm test
npm start
npm run clean
npm test
npm start

--== Environment ==--

# Processors:              8
Architecture:              AMD64
Processor ID:              Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

Git Version:               2.11.0.windows.2
Git Branch:                3.4
Node:                      v7.3.0
NPM:                       3.10.10
```

LGTM 💯 . Anything else that needs run?

**Comment by mxstbr** [comment]
Awesome @jwinn, thanks so much!

There is one last PR I want to land then we're good to: #1460. Can somebody approve please? Then I'll release.

**Comment by mxstbr** [comment]
Anybody? Still need approval here: #1460

**Comment by KarandikarMihir** [comment]
@mxstbr can I do anything?

**Comment by KarandikarMihir** [comment]
Huh. I don't think my review amounts to anything. I tried.

**Comment by mxstbr** [comment]
> Huh. I don't think my review amounts to anything. I tried.

That's weird, you're a Contributor! They should definitely count. Will investigate after the release!

**Comment by KarandikarMihir** [comment]
Maybe only the collaborators can _really_ approve the changes.

**Comment by mxstbr** [comment]
Oh wait, I thought I had added you as a collaborator? Will fix asap

**Comment by KarandikarMihir** [comment]
Wow! That escalated quickly 😄 This is yuge!! Thank you @mxstbr . I'm really honored.

**Comment by mxstbr** [comment]
IT'S TIME, THE RELEASE IS LIVE!

Thanks everybody for your amazing work the recent months, you rock!! 🎉

**Comment by gihrig** [comment]
Yes indeed Thank you _so_ much to everyone who helped to make react-boilerplate 3.4 the best version yet ✨ 

@mxstbr one last detail:

Github shows `dev` as being "24 commits behind master"
image

This is not correct, the only missing item I'm aware of is the final update to Changelog. I can do a 'fast forward' merge from `master` to `dev`, but I can't push to `dev` because of branch protection.

I believe you can do that push as project owner, which would bring `dev` current and avoid the merge conflicts which would occur with a PR. Is there's a better way?

OK so, two final details 😄  We still have .lgtm in `master` and `dev`.

That's all - Thank you Max for pushing this over the finish line 🏅

**Comment by mxstbr** [comment]
> I believe you can do that push as project owner, which would bring dev current and avoid the merge conflicts which would occur with a PR. Is there's a better way?

I can't actually, but I can disable branch protection for 10 seconds, do the merge and push and enable it again 😉 give me two minutes before merging anything into `dev`!

**Comment by gihrig** [comment]
OK - hands off…

**Comment by mxstbr** [comment]
Already done, feel free to go on!

**Comment by gihrig** [comment]
image

Excellent! 💯 

Now all that remains is removing `.lgtm` from `master` and `dev`. (am I being a pest? 😬 )

**Comment by mxstbr** [comment]
I'll leave that PR up to you 😇

**Pull request merged**
