### PR TITLE
Remove static reducer from generator

### PR DESCRIPTION
**Pull request by harijoe**
[#331](https://github.com/mxstbr/react-boilerplate/issues/331) and [former pull request #501](https://github.com/mxstbr/react-boilerplate/pull/501#issuecomment-224637849)

### CODE REVIEW

**Comment by mxstbr** [comment]
This LGTM, I just want to get one last look at this from other collaborators before I merge this.

@oliverturner @somus @datapimp @tsm91 any thoughts against this change? We're code splitting containers, so adding the reducers to the static reducers list doesn't really make sense imo, so I think this is a good change :+1:

**Comment by tsm91** [comment]
LGTM

**Comment by oliverturner** [comment]
Sounds right, looks good 👍

**Comment by mxstbr** [comment]
Awesome, thanks @harijoe!

**Pull request merged**
