### PR TITLE
Testing update

### PR DESCRIPTION
**Pull request by mxstbr**
This is a continuation of #782 by @kane-c, it seems like we need to update some tests! I've started the initial work, would appreciate others looking at the coverage report and finding the places we haven't tested :+1:

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview ready!

Built with commit 380ade09da574f4b0330d5427dfdda9a3f7631ba

http://deploy-preview-795.react-boilerplate.netlify.com

**Comment by mxstbr** [comment]
Hell yeah 99% coverage 😎

**Comment by kane-c** [comment]
Awesome :ok_hand:

**Comment by mxstbr** [comment]
Hell yeah! :shipit:

**Pull request merged**
