### PR TITLE
chore(deps): lock react-addons-test-utils

### LINKED ISSUE #1246: Error with vanilla installation
# React Boilerplate

## Issue Type

- [x] Bug
- [ ] Feature

## Description

With installing the vanilla boilerplate, not doing anything with it and running `npm run build` I get the following error message:

`ERROR in ./~/react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' in '/Users/winkler/Sites/chat/node_modules/react-addons-test-utils'
 @ ./~/react-addons-test-utils/index.js 1:17-56
 @ ./~/react-element-to-jsx-string/index-dist.js
 @ ./~/chai-enzyme/build/assertions/contain.js
 @ ./~/chai-enzyme/build/index.js
 @ ./internals/testing/test-bundler.js`

## Steps to reproduce

`git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git .`
`npm run setup`
`npm run build`

# Versions

- Node/NPM: 7.00/4.0.1

### PR DESCRIPTION
**Pull request by Dattaya**
Trying to fix #1246

### CODE REVIEW

**Comment by Dattaya** [comment]
Something installs `react-addons-test-utils@15.4` and we're bumping into this bug: https://github.com/facebook/react/issues/8314
I don't understand why recent pull requests pass Travis build but fail AppVeyor. On my Windows machine everything works fine.

**Comment by gihrig** [comment]
According to [this comment](https://github.com/facebook/react/issues/8314#issuecomment-261240398), it's not so much a bug as a breaking change in an un-tracked (transient) dependency (react-addons-test-utils).

I have no problem with adding react-addons-test-utils to package.json, but now that react 15.4 has shipped, we should lock react, react-dom and react-addons-test-utils at 15.4. No?

**Comment by Dattaya** [comment]
Yes, if the other packages work fine with React 15.4, it's better to update libraries from React ecosystem instead of merging this fix. I might need to create another fix for the `master` branch in case it's affected too, it seems like it is judging from #1246

**Comment by Dattaya** [comment]
...or update dependencies there too if it's acceptable.

**Comment by gihrig** [comment]
Master branch includes a yarn.lock, but yarn is not an official (required) dependency of react-boilerplate (yet).

Maybe better to release react-boilerplate 3.3.4 to master with react-addons-test-utils as a dependency. That  would be my preference over a hot fix to 3.3.3 master.

@mxstbr, what other open PRs (if any) would you like to see included in 3.3.4?

**Comment by gihrig** [comment]
@Dattaya I have included `react-addons-test-utils@15.4.0` in this week's dependency update #1252. So I'm closing this PR as the issue is fixed in #1252 for dev and IMHO, master should be fixed be fixed by a version update to 3.3.4. I have also closed #1246.

Thank you for taking the time time to research this issue and open the PR! 😄

**Pull request closed without merging**
