### PR TITLE
filter test file from coverage report

### LINKED ISSUE #195: Exclude test files from coverage report
IMO it doesn't make much sense to include test files in the coverage, since they aren't being tested. I'm not sure we can do anything against them being used though – @jbinto any insights?

### PR DESCRIPTION
**Pull request by ktravers**
closes #195

- uses BASH commands to filter `lcov` input being piped to coveralls
- filters out all files with `test` in their path

### CODE REVIEW

**Comment by mxstbr** [comment]
Yes, I like this! Can it possibly be achieved without adding another dependency?

**Comment by ktravers** [comment]
@mxstbr absolutely, good call. since we're piping output to coveralls, we can use a nice simple `grep -v` to filter out any files with `test` in their path. will update description above accordingly

**Comment by mxstbr** [comment]
While I really appreciate you taking the time to fix this, #980 will supersede our current test setup in the next release, so this isn't necessary anymore.

Thanks for submitting this PR, I really appreciate it! I'm sure people that use the current version will find this very helpful 👍

**Comment by ktravers** [comment]
@mxstbr no problem, excited for the move to Jest/Enzyme!

**Pull request closed without merging**
