### PR TITLE
update the Router to 2.0, refactor routes

### PR DESCRIPTION
**Pull request by knowbody**

### CODE REVIEW

**Comment by mxstbr** [comment]
I'm no longer merging anything into the master branch – take a look at the `v3.0.0` branch, where the router is already updated.

Thanks anyhow for the PR, much appreciated!

**Comment by knowbody** [comment]
oh I've missed that one, sorry

**Comment by mxstbr** [comment]
Don't worry, thanks anyway for the effort!

**Comment by grabbou** [comment]
You were not the only one hehe

**Pull request closed without merging**
