### PR TITLE
v3.2.1

### PR DESCRIPTION
**Pull request by mxstbr**
**Patch release to get hotfix from #1031 by @chaintng landed.**

# Changelog

- Updated dependencies (thanks @gihrig!)
- Speed up travis builds (thanks @jstockwin!)
- Test all current Node versions on CI (thanks @amilajack!)
- Use `babel-preset-latest` to get all the ESNext goodies automatically (thanks @samit4me!)
- **Hotfix** eslint-config-airbnb (thanks @chaintng!)

# News

Welcome @amilajack to the team, he'll be around the repo closing issues and answering questions!  Special thanks as always to @gihrig for diligently testing everything and keeping our dependencies up to date!

If you want to help us make react-boilerplate great, please use the `dev` branch, test all the things and report all the bugs!

# Supporters

This release was made possible by [React.js Program](http://reactjsprogram.com), [Fullstack React](https://www.fullstackreact.com/) and [Serverless](http://serverless.com)! _Want to support us too? [Click here!](http://opencollective.com/react-boilerplate)_

### CODE REVIEW

**Comment by mxstbr** [comment]
Please test this locally and report back if everything works, I don't have time at the moment, still on vacation! (cc @amilajack @jwinn @gihrig)

**Comment by jwinn** [comment]
@mxstbr wanted to give an update on my local testing, before I retire for the evening.

I tested the following on the dev branch:
```
git clone --b dev --depth=1 https://github.com/mxstbr/react-boilerplate
npm run setup
npm test
npm start
```
Manually verified changing locale, features, home, and github check (Firefox 49.0)
```
npm run clean
npm test
npm start
```
Manually verified page shows text (Firefox 49.0)

I ran these steps on the following systems:
```
macOS Sierra (10.12)
Git version: 2.10.0
Node version: v6.6.0
NPM version: 3.10.7
```

```
Windows 10 Pro x64 (10.0.14393)
Git version: 2.10.0.windows.1
Node version: v6.6.0
NPM version: 3.10.3
```
Note: on windows, git, node and NPM installed with chocolatey

Everything seemed to work as expected. I'll try and get more time to do more thorough testing.

**Comment by mxstbr** [comment]
Amazing work, thanks @jwinn! As soon as a few more people. Have tested I'll merge this!

**Comment by gihrig** [comment]
Tested on update deps script e.g. #1000 - All pass 💯

**Comment by mxstbr** [comment]
Released, thanks for testing!

**Pull request merged**
