### PR TITLE
Remove vestiges of CSS from generator templates

### PR DESCRIPTION
**Pull request by Virsaviya**
There were a few if-blocks in the generator templates that pulled in CSS if the user wanted it.  Since the move to styled-components, this logic is not unnecessary.

### CODE REVIEW

**Comment by jeremyadavis** [comment]
I just recently went through setting up a new project from clean and had to patch a few other items that where added to the app that were missed in the template.

If memory serves, the OfflinePlugin warning in dev is missing along with the global-styles reference.

Might be good to expand this a bit to ensure the templates are in sync with the default install app.

**Comment by samit4me** [comment]
@jeremyadavis Thanks for sharing, could you please open a new issue detailing what was missing.

@Virsaviya Could you please merge or rebase `dev` into your branch.

**Comment by samit4me** [comment]
LGTM

**Comment by mxstbr** [comment]
LGTM

**Comment by Dattaya** [comment]
I'll submit a follow up PR with the change I requested.
Thanks, @Virsaviya, for helping make this boilerplate better ❤️.

**Pull request merged**
