### PR TITLE
chore(deps): update deps roll-up Dec-03-2016

### PR DESCRIPTION
**Pull request by gihrig**
-- Test script --
npm run setup && npm start
Test Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate component TestComp /w defaults
npm run generate container TestPage /w defaults
npm run generate route TestPage - /test
use TestComp on TestPage
npm start > localhost:3000/test
npm test (expect test failures due to incomplete tests)
git add .
git commit -m "testing..."

 Node 6.9.1
npm 3.10.8
Mac OS 10.11.6
Chrome 54.0.2840.98 (64-bit))

chore(deps): update deps roll-up Dec-03-2016
 fontfaceobserver           2.0.5  →   2.0.7 
 react                     15.4.0  →  15.4.1 
 react-dom                 15.4.0  →  15.4.1 
 styled-components         1.0.11  →   1.1.2 
 css-loader                0.26.0  →  0.26.1 
 eslint                    3.10.2  →  3.11.1 
 eslint-plugin-react        6.6.0  →   6.7.1 
 eslint-plugin-redux-saga   0.1.5  →   0.3.0 
 ngrok                      2.2.3  →   2.2.4 
 offline-plugin             3.4.2  →   4.5.2 
 plop                       1.7.0  →   1.7.2 
 react-addons-test-utils   15.4.0  →  15.4.1
 react-router-redux               4.0.6  →    4.0.7 <--- rolled back to 4.0.6

 - Error:
  Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
  Value "" is the wrong type.
  eslint-plugin-jsx-a11y            2.2.3  →    3.0.1 <--- rolled back
  see: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/116

 - Error:
  ~/react-bp/app/containers/HomePage/tests/sagas.test.js
  39:35  error  put effect must be yielded    redux-saga/yield-effects
  ...
  54:36  error  fork effect must be yielded   redux-saga/yield-effects
  ...
  70:42  error  take effect must be yielded   redux-saga/yield-effects
  eslint-plugin-redux-saga          0.1.5  →    0.2.0 <--- rolled back
  see: https://github.com/pke/eslint-plugin-redux-saga
  Openned #1232

 - Error
  react-bp/app/containers/TestPage/sagas.js
  5:3  error  Unnecessary return statement  no-useless-return
  After `npm run clean` and create components (see test script above)
  Needs to be fixed in generator template
    return; -> return null; Or ???
  Opened #1231

 - Error from deps roll-up Nov-12-2016 (#1225)
  Updating react-router-redux to 4.0.7 causes sagas to be loaded twice 
  due to onEnter handler bug - incurring double sagas.
  react-router-redux               4.0.6  →    4.0.7 <--- rolled back
  see: reactjs/react-router-redux#481 and comments on this PR

   Thanks @DTJB!

### CODE REVIEW

**Comment by gihrig** [comment]
`react-router-redux`               4.0.6  →    4.0.7 <--- rolled back to 4.0.6

see: [#1225 comment](https://github.com/mxstbr/react-boilerplate/commit/33485f41053caa6e90b9cbede8b51c168b38bda4#commitcomment-20063005)

**Comment by Dattaya** [comment]
LGTM

**Comment by Dattaya** [comment]
We're bumping into https://github.com/lgtmco/lgtm/issues/51, @mxstbr, please merge this, because I can't.

**Comment by gihrig** [comment]
> please merge this, because I can't.

We need one more LGTM to merge this. I pushed a change after @mxstbr 's LGTM, which canceled his :-/

Maintainers...

**Comment by mxstbr** [comment]
Sorry about that, merged!

**Pull request merged**
