### PR TITLE
Better assets location

### PR DESCRIPTION
**Pull request by okonet**
This PR contains 2 proposals:

1. Use `index.js` for each component that just export a component to simplify imports
1. Put all assets along with components

This tries to solve https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-172794898 and  https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-172803227

### CODE REVIEW

**Comment by mxstbr** [comment]
Amazing, good work! I'm waiting for CI to complete and then I'll merge!

Thanks so much!

**Comment by okonet** [comment]
The logo example has drawback and not idiomatic. But still IMO it's better as with `assets`. I think the project needs more "real" examples (with images, fonts etc)

**Comment by mxstbr** [comment]
@okonet agreed, I'm looking to copy parts of what I did at https://github.com/mxstbr/login-flow, see https://loginflow.mxstbr.com

**Comment by mxstbr** [comment]
1) The design is much nicer, and looks more "real-worldy"

2) The content is much more interesting for a newcomer

**Comment by okonet** [comment]
Yeah, but then it's not a boilerplate anymore I guess :)

**Comment by mxstbr** [comment]
I'm not looking to copy the whole login/register thing, just the more real-worldy design and the content from the README, that makes a lot of sense.

**Pull request merged**
