### PR TITLE
Use babel latest preset

### PR DESCRIPTION
**Pull request by samit4me**
Update `es2015` preset to `latest`, see issue #1013

### CODE REVIEW

**Comment by amilajack** [comment]
I think it would be good if you could rebase

**Comment by samit4me** [comment]
Hi @amilajack , I'm not very comfortable with rebase, so I just merged to latest changes, it is now up-to-date. [This part of the git docs](https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing) has always made me afraid to use it rebase "**Do not rebase commits that exist outside your repository**". If you have a good learning resource, please share, I would like to not be afraid of rebase.

**Comment by amilajack** [comment]
@mxstbr @gihrig is this okay?

**Comment by gihrig** [comment]
Considering that GitHub has a "Squash and merge" mode, which is the default, I think merge is fine. I also echo @samit4me's feelings about rebase.

The official word for this project can found [here](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests), note that it allows for either.

> 5. **_Locally_** merge (or rebase) the upstream dev branch into your topic branch:
> 
> git pull [--rebase] upstream dev

(emphasis mine).

**Comment by amilajack** [comment]
@gihrig Thanks for the clarification. Merged 🎉

**Comment by samit4me** [comment]
Thank you both @gihrig @amilajack

**Pull request merged**
