### PR TITLE
Removed ShallowCompare

### PR DESCRIPTION
**Pull request by eddiewang**
---referencing from gitter
app/container/homepge/index.js
line 46-49
shouldComponentUpdate(nextProps, nextState) { return shallowCompare(this, nextProps, nextState); }
React-redux connect internally takes care of this . @gearon read the source youTube video talks about this ... Shallowcompare is useful if it's not connected to redux store ...

looks like we don't need this if connected to redux store.... removed the code.

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, thanks @eddiewang!

**Comment by gihrig** [comment]
Should `react-addons-shallow-compare` then be removed from `package.json`?
It's not used elsewhere in the project that I can see.

**Comment by eddiewang** [comment]
Thought I removed it.... If not I'll make a PR tonight.

**Comment by gihrig** [comment]
@eddiewang actually you did :blush: It was my error updating my local project - sorry for the noise.

**Pull request merged**
