### PR TITLE
Update docs for removing Redux saga and Reselect

### PR DESCRIPTION
**Pull request by KarandikarMihir**
This is pertaining to #934.

### CODE REVIEW

**Comment by sedubois** [comment]
NB: PRs should target `dev`.

**Comment by KarandikarMihir** [comment]
@sedubois I'm sorry, I didn't branch off from `dev`. I thought I did. What do I do now? :|

**Comment by sedubois** [comment]
I changed it (you can also do it if happens again: Edit button at the right of PR title).

**Comment by KarandikarMihir** [comment]
@sedubois Thank you. I'll be careful next time.

**Comment by mxstbr** [comment]
Awesome, looks good to me, thanks!

**Pull request merged**
