### PR TITLE
chore(deps): update deps roll-up Oct-01-2016

### PR DESCRIPTION
**Pull request by gihrig**
-- Test script --
npm run setup
Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate component TestComp /w defaults
npm run generate container TestPage /w defaults
use TestComp on TestPage
npm run generate route TestPage - /test
npm start > localhost:3000/test
npm test (expect test failures due to incomplete tests)
git add .
git commit -m "testing..."

  Node 6.6.0
npm 3.10.8
Mac OS 10.11.6
Chrome 53.0.2785.143 (64-bit)

 babel-polyfill             6.13.0  →  6.16.0 
 babel-cli                  6.14.0  →  6.16.0 
 babel-core                 6.14.0  →  6.17.0 
 babel-eslint                6.1.2  →   7.0.0 
 babel-preset-latest        6.14.0  →  6.16.0 
 babel-preset-react         6.11.1  →  6.16.0 
 babel-preset-stage-0        6.5.0  →  6.16.0 
 eslint                      3.6.0  →   3.7.0 
 eslint-config-airbnb       11.2.0  →  12.0.0 <--- rollback to 11.2.0 pending #1027, #1032
 eslint-config-airbnb-base   7.1.0  →   8.0.0 <--- rollback to 7.1.0	     "	
 eslint-plugin-import       1.16.0  →   2.0.0 
 mocha                       3.0.2  →   3.1.0 
 webpack-dev-middleware      1.8.2  →   1.8.3

### CODE REVIEW

**Comment by sedubois** [comment]
There are now warnings upon `npm i`:

```
npm WARN eslint-config-airbnb@11.2.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@7.2.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@7.1.0 requires a peer of eslint-plugin-import@^1.14.0 but none was installed.
```

**Comment by gihrig** [comment]
We have more-or-less always had those, or similar. Maybe I wasn't paying attention, but did #1058 fix those too?

The solution is to explicitly request older (but unneeded) versions of `eslint-plugin-import`?

1. They are just warnings, everything works AFAICT.
2. Do you think it's worth down loading requested, but un-needed packages just to clear the warnings?

**Comment by sedubois** [comment]
Yes #1058 had fixed the last warning that remained on `npm i`. Now with merge of #1067, warnings are:

```
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
```

**Comment by gihrig** [comment]
I guess I don't understand what's going on:

Changing `package.json` to:
```
"eslint-plugin-import": "1.16.0",
"eslint-plugin-import": "2.0.0",
```
Does not remove the warnings. Even manually installing `eslint-plugin-import@1.16.0` with an empty `node_modules` then doing a normal install does not help.

However, if I `git checkout` 42005e364d03155fe8206692e142d53598ce41be (that's the #1058 commit), I get no warnings on the main install (is that just luck?). There are several warnings from preinstall events.

I honestly think these are beyond our control, just a fact of npm and its ecosystem. If someone could point out a better way I would love to hear about it, but for now, this will have to do...

`npm run setup` manages to suppress or avoid the preinstall warnings and does not show the main install results. So, I'm not too concerned about these warnings.

**Pull request merged**
