### PR TITLE
chore(deps): update deps roll-up aug-20-2016

### PR DESCRIPTION
**Pull request by gihrig**
chore(deps): update deps roll-up aug-20-2016

npm run setup
Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate container Test /w defaults
npm run generate component TestComp /w defaults
use TestComp on TestPage
npm run generate route Test - /test
git commit -m "testing..."
npm start > localhost:3000/test

Node 6.3.1 
npm 3.10.5
 Mac OS 10.11.6
Chrome 52.0.2743.116 (64-bit)

 react                  15.3.0  →  15.3.1
 react-dom              15.3.0  →  15.3.1
 react-router            2.6.1  →   2.7.0
 react-router-scroll     0.2.1  →   0.3.1 <--- rolled back
 redux-immutable         3.0.7  →   3.0.8
 babel-loader            6.2.4  →   6.2.5
 eslint                  3.3.0  →   3.3.1
 eslint-plugin-import   1.12.0  →  1.13.0
 eslint-plugin-react     6.0.0  →   6.1.2
 karma-chrome-launcher   1.0.1  →   2.0.0
 postcss-loader          0.9.1  →  0.10.1

ERROR: app.js?2de9:126 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_10_react_router_scroll___default(...) is not a function

Caused by  react-router-scroll         0.2.1  →   0.3.0

Rolled back to 0.2.1 apparently waiting for react-router 3 https://github.com/taion/react-router-scroll/issues/28

### CODE REVIEW

**Comment by mxstbr** [comment]
Amazing! :shipit: please merge this

**Comment by gihrig** [comment]
"included' the removal of the unused `history` see #879 thanks to @brandondurham

**Comment by gihrig** [comment]
@mxstbr While waiting for netlify, poking around, I noticed we have a merge conflict brewing when `master` gets ahead of `dev`. Currently `dev` is 3 commits ahead, 4 commits behind master.

IMO the solution is to merge `master` into `dev` when any changes are made to `master`, which should be rare.

Do you see any reason why this should not be done now? If it's OK with you I can do this, if you like.

**Comment by mxstbr** [comment]
Please do!

**Comment by gihrig** [comment]
@mxstbr Netlify seems to have decided to deploy all open PRs and jammed... Any ideas?

**Comment by mxstbr** [comment]
Yeah, ignore and merge :wink:

**Comment by gihrig** [comment]
> Yeah, ignore and merge 😉

@mxstbr Would that be a "manual merge" from the cli?

Thanks for taking care of this, I have been out all day.

**Comment by mxstbr** [comment]
No, I can merge PRs even when certain status checks haven't yet passed. _whistle_ I've made Netlify un-required for now!

**Pull request merged**
