### PR TITLE
Update all deps to latest semver

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by sedubois** [comment]
What is the rationale behind removing `yarn.lock`?

**Comment by amilajack** [comment]
This PR wasnt intended to add yarn support, which is still being discussed.

**Comment by sedubois** [comment]
I might have misunderstood, but yarn support was added in PR https://github.com/mxstbr/react-boilerplate/pull/1092 which was approved and merged by @mxstbr, wasn't it?

**Comment by amilajack** [comment]
Ahh. I must have missed that PR in my notifications. I'll add the `yarn.lock` file. Thanks for reviewing!

**Comment by sedubois** [comment]
Sure :)

**Comment by amilajack** [comment]
Fixed 🎉

**Comment by gihrig** [comment]
@amilajack Wondering why you decided to make this PR?

You do realize that I had taken on the responsibility of keeping dependencies up to date? (search PRs for `is:pr author:gihrig`)

I had a work emergency and didn't get to it this weekend, no big deal...

So if you really want to take this on, I'm OK with that, but I would expect that at a minimum you support the level of quality I have established, or a reasonable substitute.

Specifically:

 1. Title or description: There was some thought to move toward a standardized commit message format. See #766 and PR search above, but I guess the community has abandoned that idea. Still the title/description provided "Update all deps to latest server" is not right. I think you meant "semver" not "server"? Even so, "semver" is not correct. This project has abandoned relying on semver as unreliable. That's why versions are "pinned", no "^" or "~" in version numbers. See  #598.

 2. Most importantly, what have you done to test the project with this version update? Each dependency update that I submitted included a detailed description of what was updated, what was rolled back because of incompatibility, the error caused by that incompatibility or the fix applied and a summary of the tests run to confirm the validity of the updated dependencies.

As I said, if this is something you want to commit to doing, and you are willing to put in the time and attention keep the quality up - I don't object. I have a "script" that I follow to ensure that most of the project gets tested with each new update.

```
Update Dependencies

--- In react-bolierplate parent dir --
git clone https://github.com/mxstbr/react-boilerplate.git react-bp && cd react-bp && git checkout dev
ncu -u (update all dependencies to latest)
--- Test as below ---

--- In react-bolierplate project --
Update (fetch/merge) local dev branch 
git checkout dev
git checkout -b update-deps
copy package.json from react-bp
git add .
git commit -m "chore(deps): update deps roll-up Aug-27-2016" <-- fix date
git push -u origin update-deps
Open PR from origin update-deps to upstream dev


-- Test script --
npm run setup && npm start
Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate component TestComp /w defaults
npm run generate container TestPage /w defaults
npm run generate route TestPage - /test
use TestComp on TestPage
npm start > localhost:3000/test
npm test (expect test failures due to incomplete tests)
git add .
git commit -m "testing..."
```

**Comment by sedubois** [comment]
@gihrig I have the feeling that everyone would be happy (I would be at least) for you to continue performing these upgrades and it's not a big deal that you didn't have time recently, like for everyone else 😊 Maybe you could document those procedures you mentioned in the wiki? Then if sometimes you are too busy, someone else can take care of it, ensuring the same level of quality.

**Comment by amilajack** [comment]
> You do realize that I had taken on the responsibility of keeping dependencies up to date? (search PRs for is:pr author:gihrig)

By bad. I had no idea. Wasn't aware of these conventions until now. I'll keep them in mind next time. Closing this for now

**Comment by gihrig** [comment]
> By bad. I had no idea. Wasn't aware of these conventions until now. I'll keep them in mind next time. 

@amilajack Next time? How about now, with this commit? Seriously, I don't mind, I'm still busy, won't get to it again until this weekend.

If you have the time and want to clean up and submit this PR, go for it. The "script" is posted above. If you don't want to do that it's OK I'll try again this Saturday or Sunday.

**Pull request closed without merging**
