### PR TITLE
feature(nginx): integrating mozillas nginx secure tls configuration i…

### PR DESCRIPTION
**Pull request by supergicko**
Pull Request for #1392 

This PR updated .nginx.conf and its TLS configuration based on [Mozillas Recommendations](https://mozilla.github.io/server-side-tls/ssl-config-generator/) 

- enabled only TLS 1.2, disabled TLS 1.0, 1.1
- added HSTS Header
- disabled weak ciphersuites
- enabled strong ciphersuites
- enabled ssl_prefer_server_ciphers to prevent possible downgrading attempts in Client Hello
- provided configs for own DH Param (commented out, optional)
- provided configs for OCSP (commented out, optional)

### CODE REVIEW

**Comment by supergicko** [comment]
ping

@gihrig 

what about a merger? its approved without a merge for a while now :)

**Comment by gihrig** [comment]
@supergicko @collaborators We are trying to get two collaborators to approve PRs before merging, but that doesn't seem to be happening 😭 

Travis CI build is failing for unrelated reasons.

**Comment by supergicko** [comment]
@gihrig ah ojk i see, failed after pulling in the new updates of dev branch :S

**Comment by gihrig** [comment]
Don't want this to get lost...
As this PR has been available for comment for several days, and as it's basically a documentation update, I'm going to merge it with only one approval.

**Pull request merged**
