### PR TITLE
React-Helmet support for updating title, meta tags

### PR DESCRIPTION
**Pull request by ankitduseja**
Ability to update title, meta, link tags in the head. This also brings partial support for SEO for search engines that support indexing of javascript content.

PS: This is my first contribution to this repo. If I am missing something, please let me know.

### CODE REVIEW

**Comment by ankitduseja** [comment]
@mxstbr Please check this. This should close #376

**Comment by gihrig** [comment]
@ankitduseja I would love to see this feature added, though the final decision is for @mxstbr 

To help in that process, please merge the current Master into your PR branch.

**Comment by gihrig** [comment]
@ankitduseja bump, (again) sorry.

**Comment by ankitduseja** [comment]
@gihrig Done!

**Comment by gihrig** [comment]
@mxstbr @ankitduseja I have put this PR through it's paces.

- All tests pass (except generated test skeleton, which is expected)
- Builds and executes generated /test page in dev mode
- Builds and executes generated /test page in production mode (after removing test skeleton)
- Home, Features and generated Test pages have title and description provided by Helmet
- Docs look good

As far as I can see, this PR is ready for merge 💯

**Comment by mxstbr** [comment]
@ankitduseja this might be the most high quality PR this project has ever seen! 😍  First try: adds documentation and adds the option the generators – amazing!! Incredibly good job!

Thanks for testing this @gihrig, let's land this!

**Comment by ankitduseja** [comment]
@gihrig @mxstbr Thank you guys! This is an awesome repo, I have learned a lot from here, it deserves such PR's! :)

I'l keep contributing in future too. Cheers! 🎉

**Comment by mxstbr** [comment]
Awesome, glad to have you aboard @ankitduseja!

**Comment by robbue** [comment]
Is there any way to make this work for the Facebook crawler as well?

**Comment by ankitduseja** [comment]
@robbue I guess facebook doesn't parse JS and hence it would require server side rendering. Check #174 and #625.

**Comment by robbue** [comment]
@ankitduseja No, they don't. I dont need full SSR for now, but at least I need meta tags. I'll try to find a solution - all suggestions is appreciated!

**Comment by hungryzi** [comment]
@robbue I'm facing the same problem. Have you found any solution to this?

**Comment by robbue** [comment]
@hungryzi Unfortunally I have not had the time to look into it yet

**Comment by KATT** [comment]
@robbue - you can use a service like prerender.io, it's free if you don't have many pages.

```js
app.use(require('prerender-node')
  .set('prerenderToken', 'your-token')
);
setup(app, {
// ...
```

(ended up here after reading the SSR thread, I know this is old, just thought I'd mention it)

**Comment by ItsMrAkhil** [comment]
@KATT will you please look at this link http://stackoverflow.com/questions/41843145/react-prerender-io-fetch-as-google-is-not-working

**Pull request merged**
