### PR TITLE
Test against modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by gihrig** [comment]
@amilajack Thanks for doing that 😄

**Comment by gihrig** [comment]
This is a great addition. Ready to merge AFAICT 💯 

Passes travis.yml [validation](http://lint.travis-ci.org/)

Travis build passes on my fork:

image

**Comment by mxstbr** [comment]
Awesome, let's :shipit:! Thanks @amilajack!

**Comment by amilajack** [comment]
No problem! I'm willing to provide long-term support for this project. Where do you recommend I look for things to help out with? I've found the [todos project tab](https://github.com/mxstbr/react-boilerplate/projects/1). Is it recommended that I start there?

**Comment by mxstbr** [comment]
> I'm willing to provide long-term support for this project.

Amazing, that's great to hear, we'd love to have you!

The [`v3.3` project](https://github.com/mxstbr/react-boilerplate/projects/1) is definitely the best place to start, but feel free to open issue to discuss new features, removals or things you want to have in this boilerplate!

**Pull request merged**
