### PR TITLE
changing default port number from cmd arguments

### PR DESCRIPTION
**Pull request by rcholic**
To run the app on a custom port number (e.g. 5000), execute:
npm start -- -p 5000

### CODE REVIEW

**Comment by rcholic** [comment]
btw, this PR is for the issue reported here [@462](https://github.com/mxstbr/react-boilerplate/issues/462)

**Comment by mxstbr** [comment]
Well, you have to use the `intendedPort` variable somewhere too! :grin:

**Comment by rcholic** [comment]
@mxstbr sorry, it is my bad, I forgot to use the `intendedPort` variable, now I've fixed it in my branch. Please reconsider the PR. Thanks! 👍

**Comment by mxstbr** [comment]
Thank you! :tada:

**Comment by jamesmbowler** [comment]
Did this get reverted? I don't see it in Master, or the other branches.

**Pull request merged**
