### PR TITLE
Prevent language duplication

### PR DESCRIPTION
**Pull request by harijoe**
Resolves [#1234](https://github.com/mxstbr/react-boilerplate/issues/1234)

### CODE REVIEW

**Comment by Dattaya** [comment]
Great job, @harijoe, thanks. Could you please submit another pull request to the dev branch instead of master?

**Comment by gihrig** [comment]
@harijoe I think you can just change the "commit into" control on your PR page. No need for a new PR.

**Comment by gihrig** [comment]
Also, the [AppVeyor error](https://ci.appveyor.com/project/mxstbr/react-boilerplate/build/1620/job/4xqm75w30r8o4bw1#L1757) should go away when the PR is submitted against `dev`.

**Comment by Dattaya** [comment]
I did that, but that commit still need to be rebased

**Comment by gihrig** [comment]
@dattaya That can be done from the "Update Branch" button below the checks panel at the bottom of the PR. I'll let you do that :smile:

**Comment by gihrig** [comment]
@Dattaya I don't have time to test this work ATM, but if you have tested it, go ahead a commit. That's why we have a `dev` branch 😄

**Comment by Dattaya** [comment]
Well, I was waiting for the LGTM system, but I don't mind merging everything I think is ready :shipit: 😃 

What do I do now, "rebase and merge"? I don't think I should squash all this stuff: 
image

We're also going to merge this:
image

**Comment by mxstbr** [comment]
No, this PR needs to be rebased on top of `dev` I'm pretty sure

**Comment by gihrig** [comment]
@mxstbr Hey, good to see you! 😄 

>No, this PR needs to be rebased on top of dev I'm pretty sure

I thought that was what was done by the "Update branch" feature here on this PR page. No??

@Dattaya and @mxstbr 
> What do I do now, "rebase and merge"? I don't think I should squash all this stuff:

Why not? it looks kind of scaryy, but I think it was just done by "Update branch" here on GitHub.

Am I missing something?

**Comment by mxstbr** [comment]
If we squash merge this, I think it's going to do all of those changes again. Take a look at the diff above, we don't want to squash merge all those changes!

**Comment by gihrig** [comment]
>  I think it's going to do all of those changes again. 

This is what I see on the "Files Changed" tab
image

I kinda assumed that was the final result of the PR, but yes, the "Commits (7)" tab is a point of concern. I think the seven commits are what was required to bring  the `harijoe:prevent-language-duplication` branch up to date with `dev`. But you have more experience with this stuff than I do, so I'll gladly accept your view.

**Comment by harijoe** [comment]
It should be okay now :)

**Pull request merged**
