### PR TITLE
Change resolve.packageMains ==> resolve.mainFields

### PR DESCRIPTION
**Pull request by mgmcdermott**
Noticed this in my own project and thought I'd submit a PR here. If you look in the source code of webpack, https://github.com/webpack/webpack/blob/6b0c20a53ad7b04d4282a8a5c334ea0982fd364c/lib/WebpackOptionsDefaulter.js#L82, you'll see that the actual name of packageMains is mainFields. Easiest way to see the implementation is by checking out the source code: https://github.com/webpack/webpack/search?utf8=%E2%9C%93&q=mainFields

### CODE REVIEW

**Comment by mxstbr** [comment]
Probably a v2 change that wasn't mentioned in the documentation, thanks for digging in!

CI is failing due to these errors:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 build script 'cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\react-boilerplate\npm-debug.log
```

Any idea what the problem could be?

**Comment by mgmcdermott** [comment]
Correct, it was a change in v2. When running with stats on, the following error is shown:
```
> react-boilerplate@3.0.0 build /Users/mcdermmg/dev/react-boilerplate
> cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p

something is very odd, it is being called twice
Hash: 7dad5970cf73fbb93c7a
Time: 14843ms
 [602] multi main 28 bytes {0} [built]
    + 648 hidden modules

ERROR in ./app/containers/App/banner-metal.jpg
Module build failed: Error: spawn /Users/mcdermmg/dev/react-boilerplate/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/containers/App/index.js 18:0-40
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
Child __offline_serviceworker:
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

Seems to be an npm error? https://github.com/tcoopman/image-webpack-loader/issues/16

Also might be nice to see a grep for packages that use the jsnext:main field (now that they're actually being used):
```
node_modules/history/package.json:  "jsnext:main": "es6/index",
node_modules/is-natural-number/package.json:  "jsnext:main": "index.jsnext.js",
node_modules/lodash-es/package.json:  "jsnext:main": "lodash.js",
node_modules/react-router/package.json:  "jsnext:main": "es6/index",
node_modules/redux/package.json:  "jsnext:main": "es/index.js",
node_modules/redux-saga/package.json:  "jsnext:main": "src/index.js",
node_modules/reselect/package.json:  "jsnext:main": "es/index.js",
node_modules/scroll-behavior/package.json:  "jsnext:main": "es/index.js",
```

**Comment by mgmcdermott** [comment]
@mxstbr Looking at this again briefly, I still don't see how this change is causing `image-webpack-loader` issues that didn't exist already.

**Comment by andykenward** [comment]
I get an issue with redux-saga when I make this change to the boilerplate latest [commit](https://github.com/mxstbr/react-boilerplate/commit/c9807b5f29a31b67232028ac8000ec5df2b7e0af) 

```ERROR in ./~/redux-saga/src/internal/utils.js
Module parse failed: /Users/andykenward/Documents/_github/mxstbr/react-boilerplate/node_modules/redux-saga/src/internal/utils.js Unexpected token (42:13)
You may need an appropriate loader to handle this file type.
|
| export function deferred(props = {}) {
|   let def = {...props}
|   const promise = new Promise((resolve, reject) => {
|     def.resolve = resolve
 @ ./~/redux-saga/src/index.js 8:0-48
Child html-webpack-plugin for "index.html":```

Not having issues with `image-webpack-loader` myself

**Comment by mgmcdermott** [comment]
That seems like more of an issue on redux-saga's part. By specifying a jsnext:main and using stage 2 features, they are requiring everyone importing that to parse stage 2 as well. They should be doing something like react-router: https://github.com/reactjs/react-router/blob/master/package.json#L20

**Comment by mxstbr** [comment]
Waiting for @yelouafi to release a new version with the fixed `jsnext:main`…

**Comment by andykenward** [comment]
@mgmcdermott [`redux-saga` ](https://github.com/yelouafi/redux-saga/releases/tag/v0.11.0)has been updated to 0.11.0 with the jsnext fix https://github.com/yelouafi/redux-saga/pull/398 you did 👍 . So it should be good to merge this to master?

**Comment by mxstbr** [comment]
Let's merge master into this, then wait for CI to pass and get this landed! :tada:

**Comment by mgmcdermott** [comment]
Just updated the branch. Stay tuned.

**Comment by mxstbr** [comment]
For some reason this still fails when building, but webpack isn't showing any errors?

**Comment by andykenward** [comment]
@mgmcdermott I think you need to update `redux-saga` to `0.11.0`. Then it should build. Haven't tested it yet. Will do in a few mins.

**Comment by mxstbr** [comment]
Done by @andykenward in #831! Thanks for the work on `redux-saga` @mgmcdermott ❤

**Comment by chaintan17** [comment]
After merge current master branch to my project, webpack build give `exit 2` without any error.
I tried change `mainFields` back to `packageMains` and it now buildable.
Not sure what's going on here 😕 

I used OSX El Capitan
i tried `rm -rf node_modules` and `npm install` but no luck.

**Comment by gihrig** [comment]
@chaintan17 How about `npm cache clean`, `rm -rf node_modules` and `npm install` ?

**Comment by chaintan17** [comment]
@gihrig still not work.
I guess it's about one of my dependencies. because the sample project works fine.
Not sure if it something to do with `redux-form` like you what it just fixed in `redux-saga`?

**Comment by gihrig** [comment]
It is odd that `packageMains` appears in the WebPack [docs](https://webpack.github.io/docs/configuration.html#resolve-packagemains) and a Google search for `mainFields site:webpack.github.io/docs` returns nothing.

On the other hand a Webpack repository search for `packageMains` returns nothing.

Perhaps this confusion is due to a forth-coming change when webpack@210 is landed?

Looking further I see that there is evidence for the existence of [`packageMains`](https://github.com/webpack/webpack/issues?utf8=%E2%9C%93&q=is%3Aissue%20packageMains) and [`mainFields`](https://github.com/webpack/webpack/issues?utf8=%E2%9C%93&q=is%3Aissue%20mainFields)

I'm curious to know what version of WebPack you actually have installed according `node_modules/webpack/package.json`?

**Comment by chaintan17** [comment]
@gihrig i check in `webpack` folder under `node_modules` and its version is `webpack@2.1.0-beta.15`

However, during install this dependencies, it give me below error

```
 UNMET PEER DEPENDENCY webpack@2.1.0-beta.15

npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
npm ERR! code 1
```

**Comment by gihrig** [comment]
@chaintan17 

> i also tried switch to latest beta, but it gave different error.

This is a known issue, latest beta (20) does not work with react-boilerplate.

Some ideas:

1. If you run `npm install` again, without deleting anything, does that remove the npm errors? I get no errors on subsequent runs of `npm install`.
2. If you are able to get 'clean' `npm install`, does that have any effect on the original build error?

**Comment by andykenward** [comment]
@chaintan17 `redux-form` `v5.3.2` has the same [issue](https://github.com/yelouafi/redux-saga/pull/398) that `redux-saga` had. The [`jsnext:main`](https://github.com/erikras/redux-form/blob/v5.3.2/package.json#L6) in the the `package.json` just points straight to the `src` folder. 

Looks like it is [fixed](https://github.com/erikras/redux-form/pull/240#issuecomment-235919346) in `v6` of `redux-form`. Try installing the pre-release `npm i -S -E redux-form@6.0.0-rc.4`. (Seems to be a few[ breaking changes](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4) though)

**Comment by chaintan17** [comment]
@andykenward i already have latest version (v6.0 rc-4)
Then, is it possible that it's one of my other dependencies?
Bad thing is that i don't how could i reveal that :(...

**Comment by mgmcdermott** [comment]
@chaintan17 In the base webpack config, change stats to true ([here](https://github.com/mxstbr/react-boilerplate/blob/8786eec8d441c0614ad7e96ebea1d8dc6fe2ee6e/internals/webpack/webpack.base.babel.js#L85)) and re-run webpack. Not guaranteed, but that will most likely show you the errors. Also a `grep -r "jsnext:main" node_modules` may help.

**Comment by chaintan17** [comment]
setting stats to true did have some console output.

image

```
ERROR in main.2630e0e529f24c9b8154.js from UglifyJs
SyntaxError: Unexpected token: name (ExtendableError) [main.2630e0e529f24c9b8154.js:31910,6]

ERROR in main.2630e0e529f24c9b8154.js from UglifyJs
SyntaxError: Unexpected token: name (ExtendableError) [main.2630e0e529f24c9b8154.js:31910,6]
```

**Comment by mgmcdermott** [comment]
Could be related: https://github.com/erikras/redux-form/issues/1513

**Comment by javatask** [comment]
When building bundle ES6 "es6-error" lib code is included but we need ES5
+1

Quick fix
Point
from "jsnext:main": "./src/index"
to "jsnext:main": "./lib/index"
in es6-error

This is react-boilerplate issue, I suppose

**Comment by chaintan17** [comment]
@mxstbr should we reopen this issue pls?

**Comment by mxstbr** [comment]
> This is react-boilerplate issue, I suppose

Nope, this is an issue with `es6-error` – they are wrongly pointing the `jsnext:main` field directly at their src.

> should we reopen this issue pls?

This is a merged PR, can't reopen anything here 😉

**Comment by wdhorton** [comment]
@chaintan17 for a temporary fix, try configuring babel-loader in your webpack config to transpile `node_modules/es6-error`. Specific syntax depends on if you're doing an `include` or an `exclude` in the config.

**Comment by chaintan17** [comment]
Hi @wdhorton, Thanks for your info.
i tried set `exclude: /node_modules\/(?!es6-error)/,` in this line https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L18
and also add additional object
```
{
      test: /es6-error\/.*\.js$/,
      loader: 'babel',
      query: options.babelQuery,
}
```
But no lock, it still show the same error.

My guess is that UglifyJS still try to minify ES6 script file.
So i try to disable UglifyJS to test it by removing this object https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L58

However, the error still show the same, which is weird....
didn't it should stop minify JS files?

Any advice would be really appreciated, thanks.

**Comment by mxstbr** [comment]
> However, the error still show the same, which is weird....

You need to remove the `-p` flag from the webpack command in the npm script. That automatically adds UglifyJS

**Pull request closed without merging**
