### PR TITLE
Header nav

### PR DESCRIPTION
**Pull request by sedubois**
- simplifies code with `Link` instead of `dispatch(push(...))`
- moves navigation buttons to header to be accessible from all pages and reduce code repetition
- highlights nav buttons when their target matches current browser location, to make more clear what current page is
- makes it easier for projects to then quickly customise navigation

Tested redux + react-router integration still works as expected using Redux DevTools, can replay navigation changes.

screen shot 2016-10-06 at 12 47 05

### CODE REVIEW

**Comment by mxstbr** [comment]
I'm not a big fan of the coverage decrease, can you fix that, rebase on top of #1110 and resolve any conflicts left? Thanks!

**Comment by sedubois** [comment]
@mxstbr I don't know how to rebase onto another fork's branch -- but I guess this can just wait for its merge to `dev`

**Comment by sedubois** [comment]
@mxstbr I rebased ;)

**Comment by sedubois** [comment]
NB: due to conflict with styled-components, I removed the react-router `active` style feature from this PR's scope.

**Comment by mxstbr** [comment]
Thanks so much!

**Pull request merged**
