### PR TITLE
Remove OccurrenceOrderPlugin

### PR DESCRIPTION
**Pull request by alexanbj**
Removed explicit OccurrenceOrderPlugin in webpack configuration as it enabled by default
and no longer needed in webpack 2. 

See https://gist.github.com/sokra/27b24881210b56bbaff7#occurrence-order

### CODE REVIEW

**Comment by mxstbr** [comment]
>  it enabled by default and no longer needed in webpack 2.

Do you have a source for this somewhere? /cc @TheLarkinn

**Comment by GGAlanSmithee** [comment]
@mxstbr it does say so on the [official website](https://webpack.js.org/how-to/upgrade-from-webpack-1/#occurrenceorderplugin-is-now-on-by-default)

**Comment by mxstbr** [comment]
Awesome, thanks @GGAlanSmithee!

**Comment by mxstbr** [comment]
Would you mind making a new PR against the dev branch please? Thank you!

**Comment by alexanbj** [comment]
Oh, you can ignore this. It has already been applied in dev: https://github.com/mxstbr/react-boilerplate/commit/908605046e4833a7d315db32d9d8a344aeef8c5c#diff-9d2385d35fa4b2a324625077e621fca4L37

**Pull request closed without merging**
