### PR TITLE
Add memoized selector example with reselect

### PR DESCRIPTION
**Pull request by Egor-Sapronov**
Add an example how to create memoized selectors with reselect library

### CODE REVIEW

**Comment by mxstbr** [comment]
What's the benefit of memoizing the state selection?

**Comment by Egor-Sapronov** [comment]
Perfomance, you could create selectors not only on full state, but on state branches like
```
{
  branch1: {},
  branch2: {}
}
```
Create selectors form one branch and you can use it in actions too, it's a good way to use store only for storing data and making decisions in actions by query data from state with same selectors

**Comment by mxstbr** [comment]
I see, that's quite nice!

Sadly, I don't think it's suitable for integration by default, because it's too advanced for beginners.

You got me thinking that we need to add documentation for advanced patterns though. I've added your code example to the todo list (see #14) and if you're so inclined i'd love if you could write about the benefits and use cases of reselect!

Thanks so much for taking the time to submit this PR, very much appreciated!! :heart:

**Comment by mxstbr** [comment]
@Egor-Sapronov you were right, reselect is actually really useful. :100:

Sorry for not including it before, I've now worked with it for a while and have decided to integrate it into the boilerplate by default. (Take a look at the `v3.0.0` branch of this repo)

**Pull request closed without merging**
