### PR TITLE
fixing setup.js eslint errors

### PR DESCRIPTION
**Pull request by zanedev**
setup.js is throwing a ton of eslint errors when running new precommit hook.  not sure how these got in there if precommit hook is running properly for other people :)

`> lint-staged

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

/Projects/my-project/internals/scripts/setup.js
   3:1   error    Unexpected var, use let or const instead                         no-var
   4:1   error    Unexpected var, use let or const instead                         no-var
   5:1   error    Unexpected var, use let or const instead                         no-var
   5:10  error    Multiple spaces found before '='                                 no-multi-spaces
   6:1   error    Unexpected var, use let or const instead                         no-var
   7:1   error    Unexpected var, use let or const instead                         no-var
   8:1   error    Unexpected var, use let or const instead                         no-var
  13:1   error    All 'var' declarations must be at the top of the function scope  vars-on-top
  13:1   error    Unexpected var, use let or const instead                         no-var
  16:1   error    All 'var' declarations must be at the top of the function scope  vars-on-top
  16:1   error    Unexpected var, use let or const instead                         no-var
  18:1   error    'cleanRepo' was used before it was defined                       no-use-before-define
  18:16  error    Unexpected function expression                                   prefer-arrow-callback
  18:16  warning  Missing function expression name                                 func-names
  21:14  warning  Missing function expression name                                 func-names
  21:14  error    Unexpected function expression                                   prefer-arrow-callback
  27:3   error    'installDeps' was used before it was defined                     no-use-before-define
  27:15  error    Unexpected function expression                                   prefer-arrow-callback
  27:15  warning  Missing function expression name                                 func-names
  33:5   error    'deleteFileInCurrentDir' was used before it was defined          no-use-before-define
  33:40  error    Unexpected function expression                                   prefer-arrow-callback
  33:40  warning  Missing function expression name                                 func-names
  37:7   error    'initGit' was used before it was defined                         no-use-before-define
  37:20  error    Unexpected function expression                                   prefer-arrow-callback
  37:20  warning  Missing function expression name                                 func-names
  49:20  error    'dir' is already declared in the upper scope                     no-shadow
  56:18  error    'dir' is already declared in the upper scope                     no-shadow

✖ 27 problems (22 errors, 5 warnings)

Linter eslint exited with code 1`

### CODE REVIEW

**Comment by mxstbr** [comment]
This will break setup on Node < 4.0, which isn't necessarily what we want. This sounds like a bug in lint-staged, since this file is .eslintignored, /cc @okonet

**Comment by okonet** [comment]
That's weird. I need to check this out and try myself but seems like eslint not respecting ignores when called explicitly with the file path

**Comment by mxstbr** [comment]
I'll close this for now since we definitely can't fix it like this, waiting for @okonet to fix lint-staged I guess!

Thanks for notifying us and submitting this PR @zanedev, much appreciated! :pray:

**Comment by okonet** [comment]
@mxstbr I've just checked the repository and could not find any mention of `.eslintignore` file. Can you point me to it?

**Comment by okonet** [comment]
Found it here: https://github.com/mxstbr/react-boilerplate/blob/master/package.json#L34

**Pull request closed without merging**
