### PR TITLE
fix stats webpack option to output analyze json correctly

### PR DESCRIPTION
**Pull request by chaintng**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [x] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/mxstbr/react-boilerplate/blob/master/LICENSE.md).

------------

fix https://github.com/mxstbr/react-boilerplate/issues/964#issuecomment-249101175

### CODE REVIEW

**Comment by mxstbr** [comment]
I think this might make development output a lot more noisy. Can you try running `npm run start` and posting what you see in the console when you edit a file and it hot reloads?

**Comment by chaintan17** [comment]
I can't see the difference 😕 
please check this gif
http://g.recordit.co/Ss8TSU6Qej.gif
image

**Comment by mxstbr** [comment]
Amazing! Let's get this merged! – AppVeyor is failing though, is that related to this PR?

**Comment by chaintng** [comment]
@mxstbr branch updated. Ready to merge now :)

**Comment by mxstbr** [comment]
Amazing, thanks @chaintng!

**Pull request merged**
