### PR TITLE
V3.0.0

### PR DESCRIPTION
**Pull request by learntoswim**

### CODE REVIEW

**Comment by learntoswim** [comment]
Damn it. This was a mistake. Sorry.

**Comment by mxstbr** [comment]
No worries, did you want to submit a PR?

**Comment by learntoswim** [comment]
Hey, no - I was trying to back merge this into my fork to keep it updated. Mis-read the options.

**Comment by mxstbr** [comment]
:+1: Nice to hear you have a fork that you keep updated, are you using the boilerplate for something?

**Comment by learntoswim** [comment]
I've been evaluating a lot of different boilerplates. Really I've needed something setup with webpack, react, react-router, react-redux and either postcss or sass. I like this one the most as it introduced to me the concept of sagas, but it is missing a few things that I like in other boilerplates (decorations, authentication, etc). You've done an amazing job!

**Pull request closed without merging**
