### PR TITLE
config(travis.yaml): move test and build to script section

### PR DESCRIPTION
**Pull request by gihrig**
Minor edits to `.travis.yaml` as suggested [here](https://github.com/mxstbr/react-boilerplate/pull/1432#issuecomment-272398963).

Should have no effect on operation.

### CODE REVIEW

**Comment by Dattaya** [comment]
@gihrig, have you seen #1453? or you don't want to bring back `install` section of the config as I did in that PR?

**Comment by gihrig** [comment]
@Dattaya Sorry, I had not seen #1453 - comment there...

**Comment by gihrig** [comment]
@Dattaya Thanks for the review 🎉 

As I commented in #1453, this is not the reason for #1322 Travis build failure.  I'm looking into that, but running out of time for RBP today... See #1322 for updates.

**Comment by Dattaya** [comment]
> As I commented in #1453, this is not the reason for #1322 Travis build failure. 

I think it is, all builds are passing now 😃

**Pull request merged**
