### PR TITLE
Add npm install to instructions

### PR DESCRIPTION
**Pull request by thomaschaaf**
Could hinder a beginner ;)

### CODE REVIEW

**Comment by mxstbr** [comment]
`$ npm run initProject` runs [this script file](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/webpack/init#L52), have a look at line 52!

```JS
exec('npm install')
```

Thank you for taking the time to submit this PR, please do tell me what you think about current state of v3!

**Comment by thomaschaaf** [comment]
Hmm weird something is not working as it should:
```
Thomass-MacBook-Pro:test thomaschaaf$ git clone git@github.com:mxstbr/react-boilerplate
Cloning into 'react-boilerplate'...
remote: Counting objects: 1321, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 1321 (delta 45), reused 0 (delta 0), pack-reused 1227
Receiving objects: 100% (1321/1321), 372.71 KiB | 688.00 KiB/s, done.
Resolving deltas: 100% (737/737), done.
Checking connectivity... done.
Thomass-MacBook-Pro:test thomaschaaf$ git checkout v3.0.0
fatal: Not a git repository (or any of the parent directories): .git
Thomass-MacBook-Pro:test thomaschaaf$ cd react-boilerplate/
Thomass-MacBook-Pro:react-boilerplate thomaschaaf$ git checkout v3.0.0
Branch v3.0.0 set up to track remote branch v3.0.0 from origin.
Switched to a new branch 'v3.0.0'
Thomass-MacBook-Pro:react-boilerplate thomaschaaf$ npm run initProject

> reactjs-boilerplate@2.4.0 initProject /Users/thomaschaaf/develop/test/react-boilerplate
> NODE_ENV=initialisation ./webpack/init


Cleaning old repository...
Installing dependencies...
Initialising new repository...
Thomass-MacBook-Pro:react-boilerplate thomaschaaf$ npm start

> reactjs-boilerplate@2.4.0 start /Users/thomaschaaf/develop/test/react-boilerplate
> NODE_ENV=development node webpack/server.dev.js

module.js:340
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/thomaschaaf/develop/test/react-boilerplate/webpack/server.dev.js:4:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/thomaschaaf/.nvm/versions/node/v5.1.1/bin/node" "/Users/thomaschaaf/.nvm/versions/node/v5.1.1/bin/npm" "start"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! reactjs-boilerplate@2.4.0 start: `NODE_ENV=development node webpack/server.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs-boilerplate@2.4.0 start script 'NODE_ENV=development node webpack/server.dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactjs-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node webpack/server.dev.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls reactjs-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomaschaaf/develop/test/react-boilerplate/npm-debug.log
Thomass-MacBook-Pro:react-boilerplate thomaschaaf$
```

**Comment by mxstbr** [comment]
Very interesting, reopened! Will try myself soon!

----

*Love this, happens to me every time:*

```
Thomass-MacBook-Pro:test thomaschaaf$ git checkout v3.0.0
fatal: Not a git repository (or any of the parent directories): .git
Thomass-MacBook-Pro:test thomaschaaf$ cd react-boilerplate/
```

**Comment by mxstbr** [comment]
I'm going to close this PR, because this is a bug in the init script that I need to fix, which this PR (sadly) doesn't do.

Thanks for noticing and telling me there's something wrong, much appreciated!

**Comment by mxstbr** [comment]
Should be fixed in 95eae19, would you mind giving it a try?

**Pull request closed without merging**
