### PR TITLE
feat(intl): Use `appLocales` to populate i18n toggle

### PR DESCRIPTION
**Pull request by justingreenberg**
use `i18n.js#appLocales` as source of locales, remove hard coded array

### CODE REVIEW

**Comment by mxstbr** [comment]
Have you tried adding a new language? I'm 99% sure this will throw because there is no text in `messages.js` for the new language.

**Comment by mxstbr** [comment]
Just tried this locally, this throws because we need add a message with the key to the `LocalToggle/messages.js`!

**Comment by justingreenberg** [comment]
@mxstbr that makes sense... i will take a few mins tomorrow (later today for you) to see if i can find a workaround, if not will close... hard coding the locales in numerous places just feels wrong

**Comment by justingreenberg** [comment]
we could populate messages.js in generator

**Comment by justingreenberg** [comment]
@mxstbr threw up a super simple solution that works out of the box as you generate more languages... not priority by any means, feel free to merge or close :)

**Comment by mxstbr** [comment]
Hah I love it! Great work @justingreenberg! 🔥

**Pull request merged**
