### PR TITLE
Fix HMR for sync reducers

### PR DESCRIPTION
**Pull request by justingreenberg**
regarding #379 - 

- fixes issue pointed out by @saschatimme
- switches from legacy require.ensure to system loader

however i was not able to get this working with async reducers (yet)... i have several projects working with vanilla webpack HMR (and async reducers), but they not using react-transform or webpack v2

basically, with async imports the dependency graph requires instrumenting module.hot at the root to accept routes.js to rebuild... as @tsm91 pointed out in his console log:

```
[HMR] Updated modules:
[HMR]  - ./app/containers/HomePage/reducer.js
[HMR]  - ./app/routes.js
[HMR]  - ./app/app.js    <--- needs to capture update and re-render routes
```

can be resolved using vanilla hmr, but local component state will be lost on reloads. this also might be solved with react-hot-loader v3, but requires more investigation.

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, since we're getting rid of static reducers hopefully (ref #331), will this still be needed?

**Comment by justingreenberg** [comment]
@mxstbr totally up to you! actually i didn't realize you guys were planning on removing sync reducers... i think there's a case to be made for leaving them ie for core ui, locale and auth state

**Comment by mxstbr** [comment]
> i think there's a case to be made for leaving them ie for core ui, locale and auth state

Yeah, makes sense, we'll have to discuss that a little bit more!

Lets merge this PR, could you copy and paste the changes to `internals/templates/store.js`? Thanks! :+1:

**Comment by ralomucho** [comment]
I didn't want to  get rid off static reducers but to make the difference inside  generators between static and async ones !

**Comment by mxstbr** [comment]
Yeah, I misunderstood that, totally agree! Lets get this updated and merged @justingreenberg :shipit:

**Comment by justingreenberg** [comment]
@mxstbr updated 👍

**Comment by mxstbr** [comment]
Awesome, thanks Justin!

**Comment by petemill** [comment]
I'm pretty sure this doesn't work. Not only is the code in the template file from store.js different from that in the sample file for store.js, once implementing the `module.hot.accept('./reducers')` syntax, none of the static or async reducers are reoloadable.

**Comment by justingreenberg** [comment]
nice catch -- fixed in #1154

i'm not sure why HMR is not working for reducers, since this has been a solid pattern forever. it could be related to recent webpack updates.. i'm way too busy with work at the moment to investigate but please let me know if you figure it out :)

**Pull request merged**
