### PR TITLE
Clean up code in script files

### PR DESCRIPTION
**Pull request by lvarayut**
This PR contains small changes of script files to make the scripts cleaner and easier to read. The changes are:

- Using `const` and `let` instead of `var`.
- Checking existence of callback function before calling it in `checkmark.js`
- Reusing addCheckMark in `clean.js`. 
- Adding semicolons in `dependencies.js`

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [x] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

### CODE REVIEW

**Comment by gihrig** [comment]
@lvarayut This looks really good 😄 

Since the project supports Node 3 versions back (currently 4+) I'm wondering if these changes have been tested against node version 4?

Node 4 support for `const` and `let` is [incomplete](https://kangax.github.io/compat-table/es6/#node4)

It's probably  worth mentioning that [Travis](https://github.com/mxstbr/react-boilerplate/blob/master/.travis.yml#L4) and [AppVeyor](https://github.com/mxstbr/react-boilerplate/blob/master/appveyor.yml#L14) are testing against Node 5, so passing CI builds may not be sufficient.

**Comment by lvarayut** [comment]
Thanks @gihrig for taking a look. It has been tested against v4.0.0 on my machine. 

I'm just curious why don't we setup both Travis and AppVeyor to test against Node 4 also? So, all the functionalities will work well on 4+.

**Comment by gihrig** [comment]
> I'm just curious why don't we setup both Travis and AppVeyor to test against Node 4 also? So, all the functionalities will work well on 4+.

Perhaps @mxstbr can answer that?

**Comment by lvarayut** [comment]
@gihrig, @mxstbr Any update on this?

**Comment by mxstbr** [comment]
> I'm just curious why don't we setup both Travis and AppVeyor to test against Node 4 also? So, all the functionalities will work well on 4+.

True, we should do that :+1: 

I haven't gotten to trying out all the changed scripts on Node 4 yet, will try to do that soon!

**Comment by mxstbr** [comment]
Sorry for the delay here, would love to land this! Would you mind rebasing and merging the conflicts? Thanks!

**Comment by lvarayut** [comment]
@mxstbr, sorry for late reply. I rebased the commit and fixed conflicts.

**Comment by sedubois** [comment]
Apologies for this, but I merged before realizing this targets `master` instead of` dev`. I'll revert the code in https://github.com/mxstbr/react-boilerplate/pull/1114.

@lvarayut could you re-submit one last time with `dev` as target?

**Comment by lvarayut** [comment]
Sure.

**Comment by sedubois** [comment]
Thanks 😊

**Comment by mxstbr** [comment]
Happens to the best of us! 😉

**Pull request merged**
