### PR TITLE
various spelling error resolutions

### PR DESCRIPTION
**Pull request by stevenspiel**

### CODE REVIEW

**Comment by gihrig** [comment]
@stevenspiel This looks great. it never hurts to have little 'polish'.

There's just one thing. Can you please direct this PR to the dev branch per [CONTRIBUTING.md](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests).

Thanks for the help!

**Comment by kachkaev** [comment]
@stevenspiel just curious: what were you using to find these errors? I've been trying [eslint-plugin-spellcheck](https://www.npmjs.com/package/eslint-plugin-spellcheck) in a couple of projects, which is good but not perfect.

The greatest thing is that you keep all your spelling rules and word white-list together with your source and share these with colleagues. A small disadvantage is that the rules cannot be inherited, so there is no way to have base config and additional project-specific exceptions. Multiple dictionaries is also not supported.

**Comment by stevenspiel** [comment]
@kachkaev I use JetBrains IDEs, and use the Inspect Code tool to look for spelling. It has its own list of whitelisted words that you can easily add to, but its global for all projects, and I'm not sure the feasibility of sharing it with colleagues, nor if multiple dictionaries are supported. Anyway, this is a great project. Well done!

**Comment by mxstbr** [comment]
Awesome, thanks @stevenspiel!

**Pull request merged**
