### PR TITLE
Import PropTypes from react

### PR DESCRIPTION
**Pull request by Lesuk**
Import PropTypes from react like in A component.

### CODE REVIEW

**Comment by mxstbr** [comment]
It appears that this change (for some unknown reason) decreases test coverage, which is not desireable. Any ideas how to fix that? (I like your style a lot more!)

**Comment by Lesuk** [comment]
No, I just saw the difference

**Comment by maxmantz** [comment]
I guess has to do with the fact that the prop types aren't covered in tests. You would have to test each components prop types like this:

instead of `Button.propTypes` try the following:

    export const propTypes = {
       // prop types here...
    };

    Button.propTypes = propTypes;

Then in tests:

    import { propTypes } from './index';

    // ...
    expect(renderedComponent.propTypes).toEqual(propTypes);

**Comment by justingreenberg** [comment]
alternatively, proptypes can be destructured.... ie

```js
import React from 'react'

const Img = ({ className, src, alt }) =>
  <img className={className} src={src} alt={alt} />

const { PropTypes: { string } } = React

Img.propTypes = {
  src: string.isRequired,
  alt: string.isRequired,
  className: string,
}

export default Img
```

allows clean namespace import of react and makes adding new props painless

can also be used for React.Component...

```js
const { PropTypes: { string }, Component } = React

class Img extends Component {
  static propTypes = {
      src: string.isRequired,
      //...
  }
}
```

**Comment by oliverturner** [comment]
2 questions: 
1. Doesn't this simply highlight the arbitrary nature of the coverage tests?
2. I like the cleanliness of the approach, but is it worth investing time in managing proptypes when Flow will inevitably replace them? If it is, isn't something like https://www.npmjs.com/package/babel-plugin-flow-react-proptypes a more forward-compatible approach?

**Comment by mxstbr** [comment]
Of course coverage is completely arbitrary, I was mostly kidding. Sorry for not merging this earlier, I got sidetracked with other things.

Would you mind resolving the conflicts @Lesuk and then I'll land this? I really like this pattern!

**Comment by mxstbr** [comment]
Realised I could just as well solve that tiny merge conflict myself. Thanks so much @Lesuk! :tada:

**Pull request merged**
