### PR TITLE
make frontEnd middleware async and handle 404 errors

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by mxstbr** [comment]
Linting error:

```
/home/travis/build/mxstbr/react-boilerplate/server/middlewares/frontendMiddleware.js
  33:2  error  Parsing error: Unexpected token
```

**Comment by FezVrasta** [comment]
@mxstbr it should be okay now

**Comment by mxstbr** [comment]
Awesome, thanks @FezVrasta!

**Comment by FezVrasta** [comment]
yw

**Pull request merged**
