### PR TITLE
Buttons display inline-block.

### PR DESCRIPTION
**Pull request by adjohnson916**

### CODE REVIEW

**Comment by philihp** [comment]
Can you make this change to the v3.0.0 branch?

**Comment by adjohnson916** [comment]
@philihp Looks like it's already in v3.0.0: https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/app/components/Button/Button.css#L7

I didn't realize you were working on v3.0.0, is master still being maintained?

**Comment by mxstbr** [comment]
Master is still being maintained, but I'm not merging any big changes. `v3.0.0` is where the party's at!

**Comment by mxstbr** [comment]
Thanks so much for contributing and the PR! Have a look at `v3.0.0` and see if you like it!

**Pull request merged**
