### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sahat**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [ ] You have followed our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Internal code generators and templates are updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/mxstbr/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by mxstbr** [comment]
Is this incorrect? I'm not sure, ESL and all that… Any english native speakers here?

**Comment by gihrig** [comment]
Yes it's correct.

[loose](https://www.google.com/search?q=define+loose&oq=define+loose&aqs=chrome..69i57j0l5.3791j0j1&sourceid=chrome&ie=UTF-8) = not tight.

[lose](https://www.google.com/search?num=100&q=define+lose&oq=define+lose&gs_l=serp.3..0i67k1j0l3j0i10k1l2j0l4.79435.79435.0.81298.1.1.0.0.0.0.92.92.1.1.0....0...1c.1.64.serp..0.1.91.mYn9G-_2H20) = unable to find or not have control.

"we don't recommend this as you lose the benefits of code splitting." is no longer having the benefits.

This should be merged when brought up to date with base branch.

**Comment by orta** [comment]
Aye, confirmed 👍

**Comment by sahat** [comment]
Should be good to merge.

**Comment by mxstbr** [comment]
Thanks @sahat!

**Pull request merged**
