### PR TITLE
Remove React Transform, use vanilla HMR instead

### LINKED ISSUE #220: Remove React Transform
See [here](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.so70l3qv0) for a very elaborate explanation why React Transform is going away soon.

We should move to a "cold reloading" setup, something like this: https://github.com/reactjs/redux/pull/1455

### PR DESCRIPTION
**Pull request by LorbusChris**
Fixes #220
In order to get vanilla hot reloading to work, I had to split out the render function from `app.js` into its own file (`index.js` but could also be called render.js or else): 
`app.js` exports `rootContainer` which is imported by `index.js` for rendering.

I used this for guidance: https://github.com/reactjs/redux/pull/1455
[redbox-react](www.github.com/KeywordBrain/redbox-react) is used for displaying errors (as in the redux example).

@mxstbr please review :smiley:  

PS: I also removed the wepback server files, they aren't used anymore as of using express, or am I wrong?

### CODE REVIEW

**Comment by mxstbr** [comment]
Thanks so much for taking a look at this! I tried it locally and got this error and no reload:

```
Provider.js:29 <Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/rackt/react-redux/releases/tag/v2.0.0 for the migration instructions.warnAboutReceivingStore @ Provider.js:29Provider.componentWillReceiveProps @ Provider.js:67updateComponent @ ReactCompositeComponent.js:458ReactCompositeComponent_updateComponent @ ReactPerf.js:66receiveComponent @ ReactCompositeComponent.js:405receiveComponent @ ReactReconciler.js:87_updateRenderedComponent @ ReactCompositeComponent.js:562_performComponentUpdate @ ReactCompositeComponent.js:544updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66receiveComponent @ ReactCompositeComponent.js:405receiveComponent @ ReactReconciler.js:87performUpdateIfNecessary @ ReactCompositeComponent.js:417performUpdateIfNecessary @ ReactReconciler.js:102runBatchedUpdates @ ReactUpdates.js:129perform @ Transaction.js:136perform @ Transaction.js:136perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66closeAll @ Transaction.js:202perform @ Transaction.js:149batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24enqueueElementInternal @ ReactUpdateQueue.js:252(anonymous function) @ ReactMount.js:425scrollMonitor @ ReactMount.js:413_updateRootComponent @ ReactMount.js:424_renderSubtreeIntoContainer @ ReactMount.js:523render @ ReactMount.js:570React_render @ ReactPerf.js:66render @ index.js:9render @ index.js:30
browser.js:49 Warning: [react-router] You cannot change <Router history>; it will be ignoredwarning @ browser.js:49routerWarning @ routerWarning.js:19Router_componentWillReceiveProps @ Router.js:167updateComponent @ ReactCompositeComponent.js:458ReactCompositeComponent_updateComponent @ ReactPerf.js:66receiveComponent @ ReactCompositeComponent.js:405receiveComponent @ ReactReconciler.js:87_updateRenderedComponent @ ReactCompositeComponent.js:562_performComponentUpdate @ ReactCompositeComponent.js:544updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66receiveComponent @ ReactCompositeComponent.js:405receiveComponent @ ReactReconciler.js:87_updateRenderedComponent @ ReactCompositeComponent.js:562_performComponentUpdate @ ReactCompositeComponent.js:544updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66receiveComponent @ ReactCompositeComponent.js:405receiveComponent @ ReactReconciler.js:87performUpdateIfNecessary @ ReactCompositeComponent.js:417performUpdateIfNecessary @ ReactReconciler.js:102runBatchedUpdates @ ReactUpdates.js:129perform @ Transaction.js:136perform @ Transaction.js:136perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66closeAll @ Transaction.js:202perform @ Transaction.js:149batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24enqueueElementInternal @ ReactUpdateQueue.js:252(anonymous function) @ ReactMount.js:425scrollMonitor @ ReactMount.js:413_updateRootComponent @ ReactMount.js:424_renderSubtreeIntoContainer @ ReactMount.js:523render @ ReactMount.js:570React_render @ ReactPerf.js:66render @ index.js:9render @ index.js:30
browser.js:49 Warning: [react-router] You cannot change <Router routes>; it will be ignored
```

Any ideas what might be happening here?

**Comment by LorbusChris** [comment]
Hm not sure why this doesnt work for you. I'm on Fedora 23 Linux and it works for me locally. Travis and Appveyor also pass this. Any ideas?

**Comment by mxstbr** [comment]
Yeah Travis and AppVeyor pass since they don't try changing anything in a file! Which file did you change to make sure the module reloading works?

**Comment by LorbusChris** [comment]
Whenever messing up a JSX Tag (e.g `<H1>text</H1>` -> `<x1>text</H1>`) it will produce the error overlay. Importing a lib from an unknown/false location also does this.
I cannot reproduce any errors that would result in the redbox being shown (I got that yesterday when I randomly deleted code, not sure what exactly triggers it.)

For me, lots of other changes do not result in Hot Reload even though webpack seemingly rebuilds the JS, for example:  `<H1>text</H1>` -> `<H1>toast</H1>` will not trigger hot reloading. Also upon introduction of compiler errors, the website is not hot-reloaded.

I dont know if this is a limitation of the hot relading API or if the setup's just not right, yet.

**Comment by mxstbr** [comment]
Well currently those do get hot reloaded, so if that doesn't work anymore this setup must've some problem...

**Comment by mxstbr** [comment]
Any updates here, any ideas why that doesn't work anymore? I'm inclined to leave the current HMR setup as-is if this can't be fixed since the whole point of HMR is that it hot reloads every change and development is very smooth...

**Comment by LorbusChris** [comment]
No news from my side. Still not sure why it behaves like this. If nobody else takes another stab at this I will revisit once webpack 2 is in. Closing for now.

**Pull request closed without merging**
