### PR TITLE
Add empty style file so stylelint doesn't fail the build after a clean.

### PR DESCRIPTION
**Pull request by marcdel**
I was also confused by the stylelint error discussed in #320. It seems to me an improved developer experience would be getting a green build after running a `git run clean` on a new clone.

It wasn't immediately obvious to me that the tests were failing because there were no css files in the app or even that this would be a failure case, so it would be nice to set newer developers up for success.

This is the least intrusive workaround I could come up with, but I realize it isn't super intuitive either (hence the comment). Let me know what you think, or if you have other suggestions!

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, what about adding that next to the default component?

**Comment by marcdel** [comment]
Not sure what you mean by default component. The components folder is removed during clean, no? 
Unless you mean the app container, which I considered, but figured it might encourage global styles more than you'd like.

**Comment by mxstbr** [comment]
Yeah that's true, hmm. Let me have a think about this!

**Comment by gihrig** [comment]
> Not sure what you mean by default component. The components folder is removed during clean, no? 

The components folder is removed and repopulated on `npm run clean`, so a basic styles css could be added to` /internals/templates` folder and then copied to `app/containers/App` in `clean.js`. 

The stub css file could be as simple as a header comment:
```
/**
 * styles.css 
 *
 * App container styles
 */
```
This solves the issue of this PR and gives us a project 'stub' after `clean` that passes tests and displays a page in the browser after `npm start`. A win win IMO.

By describing it as 
> App container styles

I don't think that encourages global styles, thoughts?

**Comment by mxstbr** [comment]
Yeah, I do prefer that solution too @gihrig. Would you mind updating the PR that way @marcdel?

**Comment by marcdel** [comment]
Sure, I'll update the PR in a moment.

However, one thing I noticed will spiking that solution the other day is that the linter will fail if you import the file but don't reference it. So we can copy the file to `app/containers/App` and stop there, or we can include it in the appContainer template and give it an empty `.container {}` style or something to slap on the div so it doesn't complain.

**Comment by gihrig** [comment]
I like the empty .container style. It creates a smoother experience for first time users. But when I create that file with:
```
/* App container styles */
.container {

}
```
and `npm run lint:css` I get an error:
```
app/containers/App/styles.css
 2:12  ✖  Unexpected empty block   block-no-empty
```
Placing a comment in the `.container` block removes the error
/* App container styles \*/
.container {
  /* Place styles for App here if needed */
}

**Comment by marcdel** [comment]
@gihrig I couldn't leave it empty, unfortunately. I went with `display: block` since it's a div, but it could be anything really.

**Comment by mxstbr** [comment]
Thanks @marcdel, this is awesome!

**Comment by marcdel** [comment]
Woo! 🎉

**Pull request merged**
