### PR TITLE
Fix cheerio dependency warning

### PR DESCRIPTION
**Pull request by sedubois**
Gets rid of this during `npm install`:

```
└── UNMET PEER DEPENDENCY cheerio@0.22.0

npm WARN chai-enzyme@0.5.1 requires a peer of cheerio@0.19.x || 0.20.x but none was installed.
```

(and I also left the auto npm JSON reformatting to make future PRs cleaner.)

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, looking at the `chai-enzyme` package.json, they explicitly state `0.22.x` is fine. I think the solution here might to bump `chai-enzyme`? https://github.com/producthunt/chai-enzyme/blob/master/package.json#L29

Man, I can't wait to merge #980…

**Comment by sedubois** [comment]
@mxstbr `package.json` already references the latest `chai-enzyme` `0.5.1`

**Comment by mxstbr** [comment]
That's weird! @ayrton @vesln any ideas what could be happening here?

**Comment by ayrton** [comment]
@mxstbr we loosened up the peer dependencies, but we haven't published a new version on npm yet. I'll do this tonight/tomorrow.

**Comment by ayrton** [comment]
Upgrade to chai-enzyme@0.5.2 and you should be good to go using cheerio@0.22.0.

**Comment by sedubois** [comment]
Thanks, I upgraded. (Just noting cheerio still gets installed a second time because enzyme references `cheerio@^0.20.0`.)

**Comment by mxstbr** [comment]
Thank you @ayrton and @sedubois!

**Pull request merged**
