### PR TITLE
chore(deps): updated redux-saga version

### PR DESCRIPTION
**Pull request by Andarist**
Just a simple version bump. 0.13 -> 0.14 does not include any breaking changes, but few depractions only. I think `redux-saga` is on its way to the 1.0 version, so the sooner ppl straighten those out the better for everybody.

### CODE REVIEW

**Comment by gihrig** [comment]
@Andarist Hi, as you may have seen when searching all PRs for "chore" I'm the guy doing routine dependency updates.

In recent weeks we have had a few breaking changes resulting from subtle changes in tracked dependencies. Since we are working on releasing a new boilerplate version (#1322) I have not been updating dependencies while that process moves forward. I would rather have a solid release with stable dependencies than the very latest with possible unknown issues.

Soon after 3.4 goes out, I expect to revisit dependency updates, I'm sure there will be _many_ packages to be updated.

Was there a specific reason you chose redux-saga to update? 
Does this update solve any specific issue? (beyond the deprecations you mentioned)

So, while I don't think we'll be merging this PR, I do appreciate the effort!

Thanks for contributing!

**Comment by Andarist** [comment]
> Was there a specific reason you chose redux-saga to update? Does this update solve any specific issue?

Well, I chose this library as Im a maintainer of it and just wanted to spread the word about new version being available. `react-boilerplate` is a great starting point for many people and it would be a shame if it uses outdated version especially as our docs are promoting preferred ways of doing things instead of deprecated ones (obviously ;) ), so one searching for documentation might stumble upon inconsistencies caused by the old version.

That being said the new version add new APIs (just new versions of the deprecated ones), fixes 1 minor scheduling problem and provides some of the missing typings, so it might be desired for people using TypeScript.

> I would rather have a solid release with stable dependencies than the very latest with possible unknown issues.

As mentioned above - we pay much attention lately to not break any APIs as we are reaching the stability point, so its completely safe to upgrade.

**Comment by gihrig** [comment]
@Andarist Thanks for the additional info. 

> it would be a shame if it uses outdated version especially as our docs are promoting preferred ways of doing things instead of deprecated ones

In that case it seems that updating the `redux-saga` library is only the first small step. The larger, more significant issue is updating `react-boilerplate` to take advantage of the new API.

Is there a guide to deprecated API and updated replacements?

**Comment by Andarist** [comment]
[0.14 Release notes](https://github.com/redux-saga/redux-saga/releases/tag/v0.14.0).

I've already updated the code on my local branch but needs to update the tests too, hopefully Ill have time to do it 2morrow.

**Comment by Andarist** [comment]
I've pushed the updated sample code + tests and even managed to increase a coverage (+0.4% ftw o/)

**Comment by mxstbr** [comment]
This LGTM, thanks!! @gihrig I feel like we should land this?

**Comment by gihrig** [comment]
@mxstbr AppVeyor is still being difficult 😦 , but go ahead and merge this 🎉 

@Andarist Thank you for contributing, much appreciated! ✨

**Pull request merged**
