### PR TITLE
Make ngrok usage opt-in instead of default

### PR DESCRIPTION
**Pull request by datapimp**
This makes the ngrok tunnel feature opt-in instead of the default behavior.

To enable the tunnel you can `npm run start:tunnel` as usual.

Arguments could be made against

- overloading ngrok which is a free service
- against opening up people's development machines to outside traffic 
  without them explicitly asking and being aware.

Although I'm not really passionate about these.

My motivation is mainly that I don't use it often enough and I am not sure most 
people would need this feature at the boilerplate phase of their project, and can easily
enable it in the future if and when they do need to use it.

If this gets merged, we can make ngrok an optional dependency.

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, not quite sure we don't want to make this a default. It's an interesting suggestion for sure, but I fear it might hide the feature behind a large wall of commands…

**Comment by tsm91** [comment]
i think sometimes less is more, this is one of the features i immediately removed from my fork of react-boilerplate

furthermore i also removed the whole express and webpack-middleware machinery, i got rid of a bunch of code and devDependency

also, no one will serve static content via express.js, they will do it via nginx, one less layer and much more efficient (they will run the nodes as a reverse proxy)

the whole development server is [6 sloc](https://github.com/tsm91/react-seed/blob/master/tools/webpack/webpack.dev.babel.js#L52-L57) in the fork

my opinioon: we got the whole implementation lets write a wiki page about it and let it go

**Comment by mxstbr** [comment]
> also, no one will serve static content via express.js, they will do it via nginx, one less layer and much more efficient (they will run the nodes as a reverse proxy)

So, the thing is, we introduced express.js because it was the first step towards server-side rendering (ref #174), which is the next big topic we'll be looking into.
I love to hear how easy it was for you to rip all of the stuff out you don't need, and we need to work on keeping that as easy because that's really important, but the express implementation is definitely staying.

> My motivation is mainly that I don't use it often enough and I am not sure most 
people would need this feature at the boilerplate phase of their project, and can easily
enable it in the future if and when they do need to use it.

I agree with you. I'll let this sit for a few more hours and think about it, but I'm positive this is a good change! Thanks @datapimp!

**Comment by tsm91** [comment]
@mxstbr ahh ok

**Comment by mxstbr** [comment]
Thanks @datapimp for keeping us real, love it!

**Comment by datapimp** [comment]
@frixid can you share details?

current master:

screenshot 2016-06-09 04 14 30

you will need to `npm run start:tunnel` directly as it is no longer the default when running `npm start`.

I'll make sure to update any missing documentation

**Comment by frixid** [comment]
@datapimp 
captura de pantalla 2016-06-09 a las 13 42 10

**Comment by datapimp** [comment]
Delete ngrok and reinstall it looks like an error in their script

**Pull request merged**
