### PR TITLE
removed useless globals

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by FezVrasta** [comment]
Oh, didn't spotted that test... It's the only place where we use chai...

I'm rewriting it to use `expect`

**Comment by FezVrasta** [comment]
Ok I guess we should keep Chai, it's useful for this kind of stuff...

**Comment by mxstbr** [comment]
Ahhh, `chaiEnzyme` is the reason we have it in there! Then the question becomes, shouldn't we get rid of `mjackson/expect` instead?

**Comment by FezVrasta** [comment]
I like the way spy functions are managed by mjackson/expect

**Comment by mxstbr** [comment]
True. Thanks @FezVrasta!

**Pull request merged**
