### PR TITLE
Adding global css documentation

### PR DESCRIPTION
**Pull request by bobkocisko**
Adding global css documentation per https://github.com/mxstbr/react-boilerplate/issues/741

### CODE REVIEW

**Comment by mxstbr** [comment]
The documentation itself looks awesome, thanks so much @bobkocisko! Would you mind moving that to `css-modules.md` as another heading? Thanks!

**Comment by bobkocisko** [comment]
Ok done and rebased.  But for some reason now it says there are conflicts and it doesn't give me the option to `Update branch`.  Did my rebase mess up the history?

**Comment by gihrig** [comment]
@bobkocisko Yeah, something is wrong, I don't think rebase was the right thing to do (but I'm no Git wizard). You might consider looking into [GitUp](http://gitup.co/). It has learning curve to be sure, but it makes things alot clearer IMO.

The changes to `internals/webpack/webpack.prod.babel.js` and `package.json` have already been committed to the project, your `docs/css/css-modules.md` does not seem to have the original content.

The simplest fix is probably:
1. Save your `docs/css/css-modules.md` in a safe location
2. Clone a new copy of react-boilerplate
3. Edit `docs/css/css-modules.md` to include your changes to the new clone
4. Open a new PR
5. Close this one

Git can be like that 😦

**Comment by bobkocisko** [comment]
Closing this per @gihrig's request

**Comment by bobkocisko** [comment]
@gihrig, I opened up a new request (https://github.com/mxstbr/react-boilerplate/pull/802) and then I realized that the problem with my fork was that somehow two commits from you landed in my fork!??  I removed them via rebase and then the merge succeeded in the context of the new pull request.  I'm not sure how those two commits landed in my fork...please review and make sure that those are unnecessary now because if not then I think you'll need to commit them again.

https://github.com/mxstbr/react-boilerplate/pull/777/commits/eb6e31892a1e102e52230212af3968d6e0db5ae2
https://github.com/mxstbr/react-boilerplate/pull/777/commits/529551e4b949500acf9707fc139ff12021d0cff6

**Comment by gihrig** [comment]
@bobkocisko I did confirm the two commits you refer to _are_ in project master. Thanks for the heads up.

**Pull request closed without merging**
