### PR TITLE
Add JSCS

### PR DESCRIPTION
**Pull request by gonzochic**
Hi, 
I added JSCS to the project (first commit) and then fixed the jscs linting errors (second commit). It is quite okay, but the only thing which annoys me is:  In js/app.js I had to disable a JSCS rule because there is an empty block. It could disturb (new) developers by asking themselves what these comments are doing ;).

Cheers

### CODE REVIEW

**Comment by gonzochic** [comment]
Just saw that you are explicitly allowing trailing commas. So this should be adapted in the jscs config. Additionally i need to revert my addition of the trailing commas. Just leave me a comment on whether you want to enforce trailing comas or not ;)

**Comment by mxstbr** [comment]
Oh no @gonzochic, this is a very lovely PR but sadly against the wrong branch! We've been hard at work on v3, would you mind resubmitting it against the `v3.0.0` branch? 

Thank you so much for taking the time to contribute, so sorry I have to close this PR!

**Comment by gonzochic** [comment]
Yes I will resubmit ;)

**Comment by mxstbr** [comment]
Thank you! :+1: Looking forward!

**Pull request closed without merging**
