### PR TITLE
:fire: HOTFIX (maybe not but simple) null offset for `connect` args

### PR DESCRIPTION
**Pull request by tbash**
Generator update: First arg passed into `connect` should be `null` if `mapDispatchToProps` is all that is needed

reference: https://github.com/reactjs/react-redux/blob/ea53d6fb076359a864a1d543568d951d4b3eab3d/src/components/connect.js#L35

### CODE REVIEW

**Comment by tobyl** [comment]
I've tested this with 3.0.2 and seen some strange behaviour - specifically no error message when dispatching from a container which has `mapDispatchToProps`, no `mapStateToProps` and only `mapDispatchToProps` as an argument to `connect()`. My saga simply wouldn't pick up the dispatched action. after adding `null` as the first argument to `connect()` the action dispatched and was instantly picked up by the saga. (providing details for anyone searching in future for this frustrating bug)

**Comment by gihrig** [comment]
@tobyl thanks for the test results.
@tbash would you mind bringing this up to date and merging into dev branch instead of master (see [CONTRIBUTING.md](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests)).
@mxstbr I know you are 'on the road', but do you see any reason not to merge this?

closes #971

**Comment by mxstbr** [comment]
Don't see any reason not to merge this, feel free to go ahead once it's updated and submitted against the dev branch!

**Comment by tbash** [comment]
@gihrig no I do not mind, on this now!

**Comment by tbash** [comment]
The original repo this PR was made from has been deleted

Closing and created new PR here: https://github.com/mxstbr/react-boilerplate/pull/973

**Pull request closed without merging**
