### PR TITLE
Add logs #81

### PR DESCRIPTION
**Pull request by 7rulnik**
So, I made this. Maybe add some styling via [Chalk](https://github.com/chalk/chalk)?
#81

### CODE REVIEW

**Comment by mxstbr** [comment]
Nice work! :+1:

One suggestion: We should only log source and not destination, since we don't actually write any files when those servers are started, so the destination doesn't even exist. That makes sense, right?

How would you style the output with chalk? I haven't worked with that at all, but would love for you to check it out!

**Comment by 7rulnik** [comment]
Thx!
Ok, I can continue tomorrow. 
I wanna do something like [this](https://monosnap.com/file/HjsLOWKuklHMPlhN21jiG62A2fC1zH) (browser-sync)

**Comment by mxstbr** [comment]
I would absolutely love that, those logs look great! Feel free to make them as nice looking as you want!

**Comment by mxstbr** [comment]
How is it going with this @7rulnik, need any help?

**Comment by 7rulnik** [comment]
Was busy at work. I will finish it at this week.

**Comment by mxstbr** [comment]
I just updated the `server.prod.js` a bit, see commit 94487c8!

**Comment by 7rulnik** [comment]
@mxstbr 
Are we really support Node 0.10? I think that few people use it.
I wanna use template strings for logs.

**Comment by mxstbr** [comment]
I can't find them right now, but I remember seeing Node version usage statistics and a large percentage was still on 0.10, which is why I decided to support it.

If you can find statistics that contradict that, we can talk about it, but I'd much rather be on the safe side.

**Pull request closed without merging**
